function my_intlab_config()
%MY_INTLAB_CONFIG Initialize INTLAB and add all project paths
%
%   This function:
%     1. Adds all project source directories to MATLAB path
%     2. Initializes INTLAB for interval arithmetic
%
%   Directory structure:
%       src/algorithms/  - Paper verification algorithms (Algorithm2, Algorithm3)
%       src/fem/         - FEM functions (eigenvalue bounds, shape derivatives)
%       src/mesh/        - Mesh generation utilities
%       src/interval/    - Interval arithmetic interface (I_inf, I_sup, etc.)
%       src/lib/         - External libraries (VFEM2D components)
%       inputs/          - Input data (cell_def.csv)
%       results/         - Verification results and checkpoints
%       tests/           - Test files
%
%   Usage:
%       my_intlab_config();

    global INTERVAL_MODE;
    INTERVAL_MODE = 1;

    % The computation was tested with gmsh version 4.8.4. 
    %For mesh generated by other versions of gmsh, the results may vary slightly.
    global gmsh_command 
    gmsh_command = '/path/to/your/gmsh'  %Path of gmsh command.;

    % Place to save temporary mesh files.
    global mesh_path
    mesh_path = '/path/to/your/LowerBoundsIneq/src/mesh'

    % Get project root directory
    project_root = fileparts(mfilename('fullpath'));

    % Add project source directories
    addpath(fullfile(project_root, 'src', 'algorithms'));
    addpath(fullfile(project_root, 'src', 'fem'));
    addpath(fullfile(project_root, 'src', 'mesh'));
    addpath(fullfile(project_root, 'src', 'interval'));
    addpath(fullfile(project_root, 'src'));

    % External libraries
    addpath(fullfile(project_root, 'src', 'lib', 'VFEM2D', 'lib_eigenvalue_bound'));
    addpath(fullfile(project_root, 'src', 'lib', 'VFEM2D_revised'));
    addpath(fullfile(project_root, 'src', 'lib', 'veigs'));

    % Add other directories
    addpath(fullfile(project_root, 'inputs'));
    addpath(fullfile(project_root, 'results'));
    addpath(fullfile(project_root, 'tests'));
    addpath(fullfile(project_root, 'tools'));
    addpath(project_root);

    % INTLAB toolbox    
    intlab_root = '/path/to/your/Intlab_V12';
    addpath(intlab_root);

    % Initialize INTLAB
    try
        pattern = '*_Intlab_Version_12_*.mat';
        delete(fullfile(intlab_root, pattern));


        startintlab;
        fprintf('LowerBoundInequalities paths configured.\n');
        fprintf('Project root: %s\n', project_root);
        fprintf('INTLAB initialized.\n');
    catch ME
        error('An error occurred while executing startintlab: %s', ME.message);
    end

end
