function test_upper_global_manifest_combiner()
%TEST_UPPER_GLOBAL_MANIFEST_COMBINER Recompute both component summaries.

if exist('OCTAVE_VERSION','builtin')
    fprintf(['test_upper_global_manifest_combiner: ', ...
        'skipped in Octave (MATLAB SHA-256 runtime required)\n']);
    return;
end
rounding_cleanup = local_round_to_nearest_guard(); %#ok<NASGU>
this_file = mfilename('fullpath');
project_root = fileparts(fileparts(this_file));
addpath(fullfile(project_root,'scripts_run'),'-begin');

directory = tempname;
mkdir(directory);
cleanup = onCleanup(@() local_remove_directory(directory));
compact_csv = fullfile(directory,'compact.csv');
residual_csv = fullfile(directory,'residual.csv');
compact_json = fullfile(directory,'compact.json');
residual_json = fullfile(directory,'residual.json');
output_json = fullfile(directory,'global.json');

canonical_y_top = sqrt(3)/2;
canonical_y_bottom = canonical_y_top-0.122;
canonical_x_right = 0.5+2*0.122;
local_write_compact_csv(compact_csv,false);
local_write_residual_csv(residual_csv, ...
    canonical_x_right,canonical_y_bottom,canonical_y_top,false);
[compact,residual] = local_manifests( ...
    compact_csv,residual_csv,canonical_x_right, ...
    canonical_y_bottom,canonical_y_top);
local_write(compact_json,jsonencode(compact));
local_write(residual_json,jsonencode(residual));

combined = verify_upper_conjecture_global_manifests( ...
    compact_json,residual_json,output_json);
assert(combined.complete_certificate);
assert(exist(output_json,'file') == 2);
assert(combined.margins.compact_lower == 0.01);
assert(combined.margins.residual_JUP_upper == -0.03);

% Numeric coverage fields are checked, not just the manifest's true flag.
bad = residual;
bad.domain_coverage.grid_y_top_lower = canonical_y_top+0.001;
local_write(residual_json,jsonencode(bad));
local_expect_invalid(@() verify_upper_conjecture_global_manifests( ...
    compact_json,residual_json,''));

% Rectangle/axis counts must equal Nx*Ny and Ny_axis.
bad = residual;
bad.summary.num_axis_intervals = 0;
local_write(residual_json,jsonencode(bad));
local_expect_invalid(@() verify_upper_conjecture_global_manifests( ...
    compact_json,residual_json,''));

% Only the canonical split functional scope is accepted.
bad = residual;
bad.functional_scope.name = 'all';
local_write(residual_json,jsonencode(bad));
local_expect_invalid(@() verify_upper_conjecture_global_manifests( ...
    compact_json,residual_json,''));

% The maximum is recomputed from required certified JUP rows.
bad = residual;
bad.summary.maximum_JUP_upper = -0.02;
local_write(residual_json,jsonencode(bad));
local_expect_invalid(@() verify_upper_conjecture_global_manifests( ...
    compact_json,residual_json,''));

% Axis identity is read back from the CSV after updating its hash.
local_write_residual_csv(residual_csv, ...
    canonical_x_right,canonical_y_bottom,canonical_y_top,true);
bad = residual;
bad.hashes.csv = ver10_file_sha256(residual_csv);
local_write(residual_json,jsonencode(bad));
local_expect_invalid(@() verify_upper_conjecture_global_manifests( ...
    compact_json,residual_json,''));
local_write_residual_csv(residual_csv, ...
    canonical_x_right,canonical_y_bottom,canonical_y_top,false);
residual.hashes.csv = ver10_file_sha256(residual_csv);

% Per-row scope is also reconstructed instead of trusting the JSON scope.
local_write_residual_csv(residual_csv, ...
    canonical_x_right,canonical_y_bottom,canonical_y_top,false,true);
bad = residual;
bad.hashes.csv = ver10_file_sha256(residual_csv);
local_write(residual_json,jsonencode(bad));
local_expect_invalid(@() verify_upper_conjecture_global_manifests( ...
    compact_json,residual_json,''));
local_write_residual_csv(residual_csv, ...
    canonical_x_right,canonical_y_bottom,canonical_y_top,false);
residual.hashes.csv = ver10_file_sha256(residual_csv);

% Strong-residual diagnostics are part of each required cell certificate.
bad_csv = strrep(fileread(residual_csv), ...
    ',-0.04,1,1.0,0.01,0.02,verified', ...
    ',-0.04,1,-1.0,0.01,0.02,verified');
local_write(residual_csv,bad_csv);
bad = residual;
bad.hashes.csv = ver10_file_sha256(residual_csv);
local_write(residual_json,jsonencode(bad));
local_expect_invalid(@() verify_upper_conjecture_global_manifests( ...
    compact_json,residual_json,''));
local_write_residual_csv(residual_csv, ...
    canonical_x_right,canonical_y_bottom,canonical_y_top,false);
residual.hashes.csv = ver10_file_sha256(residual_csv);

% Thin and compact endpoints must be identical.
bad_compact = compact;
bad_compact.thin.y_max = 0.059;
local_write(compact_json,jsonencode(bad_compact));
local_write(residual_json,jsonencode(residual));
local_expect_invalid(@() verify_upper_conjecture_global_manifests( ...
    compact_json,residual_json,''));

% Compact strip geometry is reconstructed from the CSV and gaps fail.
local_write_compact_csv(compact_csv,true);
bad_compact = compact;
bad_compact.atlas.number_of_cells = 2;
bad_compact.atlas.number_verified = 2;
bad_compact.hashes.cells_csv = ver10_file_sha256(compact_csv);
local_write(compact_json,jsonencode(bad_compact));
local_expect_invalid(@() verify_upper_conjecture_global_manifests( ...
    compact_json,residual_json,''));

% Hash changes and source changes remain independently fatal.
local_write_compact_csv(compact_csv,false);
compact.hashes.cells_csv = ver10_file_sha256(compact_csv);
local_write(compact_json,jsonencode(compact));
local_write(residual_csv, ...
    "task_id,kind\n1,rectangle\n");
local_write(residual_json,jsonencode(residual));
local_expect_invalid(@() verify_upper_conjecture_global_manifests( ...
    compact_json,residual_json,''));
local_write_residual_csv(residual_csv, ...
    canonical_x_right,canonical_y_bottom,canonical_y_top,false);
residual.hashes.csv = ver10_file_sha256(residual_csv);
residual.source.git_commit = 'different';
local_write(residual_json,jsonencode(residual));
local_expect_invalid(@() verify_upper_conjecture_global_manifests( ...
    compact_json,residual_json,''));

fprintf('test_upper_global_manifest_combiner: PASS\n');
clear cleanup
end


function [compact,residual] = local_manifests( ...
    compact_csv,residual_csv,x_right,y_bottom,y_top)
source = struct( ...
    'git_commit','0123456789abcdef', ...
    'git_status_available',true, ...
    'git_dirty',false, ...
    'source_unchanged_after_run',true);

compact = struct();
compact.schema = 'lowerboundsineq.upper_conjecture.v1';
compact.mode = 'interval';
compact.rigor = 'certified_interval';
compact.component_complete_certificate = true;
compact.source = source;
compact.thin = struct( ...
    'y_min',0,'y_max',0.06, ...
    'scaled_margin_lower',0.02, ...
    'verified',true);
compact.atlas = struct( ...
    'y_min',0.06,'y_up',0.851,'x_min',0.5, ...
    'number_of_cells',1,'number_verified',1, ...
    'cover_generation_complete',true,'all_verified',true, ...
    'minimum_margin_lower',0.01);
compact.connection = struct( ...
    'residual_y_start',0.85,'atlas_y_end',0.851);
compact.files = struct('cells_csv','compact.csv');
compact.hashes = struct( ...
    'cells_csv',ver10_file_sha256(compact_csv));

scope = struct( ...
    'name','split', ...
    'JUP_y_min',0.85, ...
    'JUP_y_min_lower',0.85, ...
    'JUP_y_min_upper',0.85, ...
    'J1_requested',true, ...
    'J2_requested',true, ...
    'JUP_requested',true);
coverage = struct( ...
    'schema', ...
        'lowerboundsineq.omega-up-residual-domain-coverage.v1', ...
    'grid_x_left_lower',0.5, ...
    'grid_x_left_upper',0.5, ...
    'grid_x_right_lower',x_right, ...
    'grid_x_right_upper',x_right, ...
    'grid_y_bottom_lower',y_bottom, ...
    'grid_y_bottom_upper',y_bottom, ...
    'grid_y_top_lower',y_top, ...
    'grid_y_top_upper',y_top, ...
    'axis_y_bottom_lower',y_bottom, ...
    'axis_y_bottom_upper',y_bottom, ...
    'axis_y_top_lower',y_top, ...
    'axis_y_top_upper',y_top, ...
    'canonical_eps_up',0.122, ...
    'canonical_x_right_lower',x_right, ...
    'canonical_x_right_upper',x_right, ...
    'canonical_y_bottom_lower',y_bottom, ...
    'canonical_y_bottom_upper',y_bottom, ...
    'canonical_ver10_omega_up_covered',true, ...
    'JUP_rectangle_y_start',y_bottom, ...
    'JUP_axis_y_start',y_bottom, ...
    'JUP_certified_y_start_upper',y_bottom, ...
    'JUP_requested_band_covered',true);

residual = struct();
residual.schema = ...
    'lowerboundsineq.omega_up_all_residual.manifest.v2';
residual.mode = 'interval';
residual.rigor = 'certified_interval';
residual.source = source;
residual.functional_scope = scope;
residual.domain_coverage = coverage;
residual.config = struct( ...
    'schema','lowerboundsineq.omega_up_all_residual.config.v3', ...
    'Nx',1,'Ny',1,'Ny_axis',1, ...
    'full_task_count',2,'selected_task_count',2, ...
    'coverage_complete',true,'selection_mode','all', ...
    'selected_task_ids',[], ...
    'functional_scope',scope, ...
    'domain_coverage',coverage);
residual.summary = struct( ...
    'num_tasks',2, ...
    'num_rectangles',1, ...
    'num_axis_intervals',1, ...
    'num_unique_task_ids',2, ...
    'num_missing_task_ids',0, ...
    'num_unexpected_task_ids',0, ...
    'num_duplicate_task_ids',0, ...
    'num_errors',0, ...
    'num_JUP_required',2, ...
    'num_JUP_certified',2, ...
    'exact_full_task_id_coverage',true, ...
    'coverage_complete',true, ...
    'canonical_ver10_omega_up_covered',true, ...
    'JUP_requested_band_covered',true, ...
    'JUP_certified_y_start_upper',y_bottom, ...
    'JUP_complete_certificate',true, ...
    'maximum_JUP_upper',-0.03);
residual.files = struct('csv','residual.csv');
residual.hashes = struct( ...
    'csv',ver10_file_sha256(residual_csv));
end


function local_write_compact_csv(filename,with_gap)
header = [ ...
    'cell_id,rigor,verified,x_lo,x_hi,y_lo,y_hi,margin_lower', ...
    newline];
if with_gap
    rows = [ ...
        '1,certified_interval,1,0.5,0.7,0.06,0.851,0.01',newline, ...
        '2,certified_interval,1,0.71,1,0.06,0.851,0.02',newline];
else
    rows = [ ...
        '1,certified_interval,1,0.5,1,0.06,0.851,0.01',newline];
end
local_write(filename,[header,rows]);
end


function local_write_residual_csv( ...
    filename,x_right,y_bottom,y_top,bad_axis_id,bad_scope)
if nargin < 6
    bad_scope = false;
end
axis_id = 2;
if bad_axis_id
    axis_id = 3;
end
rectangle_JUP_scope = 1;
rectangle_scoped_count = 3;
if bad_scope
    rectangle_JUP_scope = 0;
    rectangle_scoped_count = 2;
end
header = [ ...
    'task_id,kind,ix,iy,x_lo,x_hi,y_lo,y_hi,', ...
    'domain_applicable,computed,rigorous,', ...
    'J1_in_scope,J2_in_scope,JUP_in_scope,', ...
    'num_scoped_functionals,JUP_upper,JUP_certified,', ...
    'residual_gap_lower,eigenfunction_strong_residual_upper,', ...
    'material_strong_residual_upper,status',newline];
rectangle = sprintf([ ...
    '1,rectangle,1,1,0.5,%.17g,%.17g,%.17g,', ...
    '1,1,1,1,1,%d,%d,-0.04,1,1.0,0.01,0.02,verified\n'], ...
    x_right,y_bottom,y_top, ...
    rectangle_JUP_scope,rectangle_scoped_count);
axis = sprintf([ ...
    '%d,axis,0,1,0.5,0.5,%.17g,%.17g,', ...
    '1,1,1,1,1,1,3,-0.03,1,1.0,0.01,0.02,verified\n'], ...
    axis_id,y_bottom,y_top);
local_write(filename,[header,rectangle,axis]);
end


function local_write(filename,text)
fid = fopen(filename,'w');
assert(fid >= 0);
cleanup = onCleanup(@() fclose(fid));
fprintf(fid,'%s',char(text));
clear cleanup
end


function local_expect_invalid(action)
threw = false;
try
    action();
catch ME
    threw = strcmp(ME.identifier, ...
        'verify_upper_conjecture_global_manifests:InvalidCertificate');
end
assert(threw);
end


function local_remove_directory(directory)
if exist(directory,'dir')
    rmdir(directory,'s');
end
end


function cleanup = local_round_to_nearest_guard()
cleanup = [];
if exist('getround','file') == 2 || exist('getround','file') == 3
    old_round = getround;
    setround(0);
    cleanup = onCleanup(@() setround(old_round));
end
end
