clear; clc;
global INTERVAL_MODE; INTERVAL_MODE = 1;

mesh_params = struct( ...
    'N_LG',8, ...
    'N_rho',64, ...
    'fem_ord_LG',2, ...
    'save_intermediate',false, ...
    'results_dir','results');

% conjecture_type, eps_up, Nx, Ny, Ny_axis, N_spec, mesh_params

[is_verified, results, diagnostics] = Algorithm2_VerifyOmegaUp( ...
    'J1', 0.12, 20, 100, 100, 1, mesh_params)

disp(is_verified);