function test_residual_hessian_general_index()
%TEST_RESIDUAL_HESSIAN_GENERAL_INDEX  End-to-end i=2 INTLAB regression.
%
% This exercises the arbitrary-index path with CR/Liu lower bounds,
% verified conforming Ritz upper bounds through lambda_{i+1}, a bordered
% material solve, and a shifted RT residual.  It deliberately uses a
% scalene triangle where lambda_2 is simple.

project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root,'scripts_run'));
omega_up_all_prepare_worker(project_root,'interval');

triangle = I_intval([0,0,1,0,0.37,0.82]);
direction = I_intval([1,0]);
options = struct( ...
    'bound_order',2, ...
    'trial_order',2, ...
    'N_trial',8, ...
    'eigenfunction_error_method','eigenvalue_width', ...
    'lambda2_analytic_lower',false, ...
    'rt_solve_strategy','midpoint-defect');

[lambda,~,ddlower,ddupper,diagnostics] = ...
    calc_ddlami_residual_bounds( ...
        2,triangle,triangle,direction,8,32,2,2,options);

assert(I_inf(lambda) > 0);
assert(I_inf(ddlower) <= I_sup(ddupper));
assert(I_inf(diagnostics.core.C_minus) > 0);
assert(I_inf(diagnostics.core.C_plus) > 0);
assert(~diagnostics.core.upper_only);
assert(strcmp( ...
    diagnostics.verified_eigenvalue_diagnostics.method, ...
    'CR-Liu-lower-plus-conforming-upper'));
assert(~diagnostics.verified_eigenvalue_diagnostics. ...
    requires_upper_cluster_dimension);

fprintf(['test_residual_hessian_general_index: PASS ', ...
    'lambda_2=[%.12g,%.12g], dd=[%.12g,%.12g]\n'], ...
    I_inf(lambda),I_sup(lambda),I_inf(ddlower),I_sup(ddupper));
end
