function test_omega_mid_artifact_binding()
%TEST_OMEGA_MID_ARTIFACT_BINDING Lightweight immutable-bundle tamper test.

project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root,'scripts_run'));
temporary_dir = tempname;
mkdir(temporary_dir);
cleanup = onCleanup(@() local_remove_tree(temporary_dir));

paths = struct( ...
    'J1_csv',fullfile(temporary_dir,'J1.csv'), ...
    'J2_csv',fullfile(temporary_dir,'J2.csv'), ...
    'geometric_coverage_json', ...
        fullfile(temporary_dir,'coverage.json'), ...
    'mat',fullfile(temporary_dir,'results.mat'), ...
    'config_mat',fullfile(temporary_dir,'config.mat'), ...
    'json',fullfile(temporary_dir,'unified.json'));
local_write_text(paths.J1_csv,'J1 fixture\n');
local_write_text(paths.J2_csv,'J2 fixture\n');
gzip_path = fullfile(temporary_dir,'J1.csv.gz');
gzip_certificate = ver10_deterministic_gzip(paths.J1_csv,gzip_path);
assert(gzip_certificate.roundtrip_verified);
assert(gzip_certificate.independent_encodings_identical);
assert(strcmp(gzip_certificate.file_sha256, ...
    ver10_file_sha256(gzip_path)));
assert(strcmp(gzip_certificate.expanded_content_sha256, ...
    ver10_file_sha256(paths.J1_csv)));

runtime = struct('engine','synthetic','intlab_tree_sha256', ...
    repmat('a',1,64),'gmsh_binary_sha256',repmat('f',1,64));
runtime_sha256 = local_sha256_bytes(uint8(jsonencode(runtime)));
fingerprint_payload = sprintf( ...
    'synthetic artifact-binding fixture|runtime=%s|',runtime_sha256);
fingerprint = local_sha256_bytes(uint8(fingerprint_payload));
input_sha = repmat('b',1,64);
proof_sha = repmat('c',1,64);
selected_sha = repmat('d',1,64);
config = struct( ...
    'schema','lowerboundsineq.omega_mid_unified.config.v3', ...
    'value',17,'runtime',runtime,'runtime_sha256',runtime_sha256, ...
    'worker_runtime_validation_policy', ...
        'full-runtime-json-all-workers-before-and-after-dispatch-v1');
selection = struct( ...
    'mode','explicit-cell-ids', ...
    'selected_ids_sha256',selected_sha, ...
    'manifest_cell_ids',7);
summary = struct( ...
    'complete_certificate',false, ...
    'exact_full_input_id_coverage',false, ...
    'geometric_coverage_certified',true);
geometric_coverage = struct( ...
    'complete',true,'rigorous',true, ...
    'input',struct('sha256',input_sha), ...
    'hashes',struct('proof_payload',proof_sha));
attempt = struct('ordinal',1,'strict_checks_passed',true);
leaf = struct( ...
    'attempts',attempt,'eigenvalue_attempts',1, ...
    'selected_attempt_ordinal',1,'strict_checks_passed',true);
records = {struct( ...
    'cell_id',7,'input_row',3,'leaf_count',1,'leaves',leaf, ...
    'completed',true,'strict_checks_passed',true)};
save(paths.mat,'records','config','selection','summary', ...
    'geometric_coverage','fingerprint','-v7.3');
save(paths.config_mat,'config','fingerprint', ...
    'fingerprint_payload','-v7');
local_write_json(paths.geometric_coverage_json,geometric_coverage);

manifest = struct();
manifest.schema = 'lowerboundsineq.omega_mid_unified.manifest.v2';
manifest.fingerprint = fingerprint;
manifest.complete_certificate = false;
manifest.input = struct('sha256',input_sha,'cell_count',1);
manifest.selection = struct( ...
    'mode',selection.mode, ...
    'selected_cell_count',1, ...
    'selected_ids_sha256',selected_sha, ...
    'target_cell_ids',selection.manifest_cell_ids, ...
    'full_input_coverage',false);
manifest.config = config;
manifest.summary = summary;
manifest.geometric_coverage = geometric_coverage;
manifest.source = struct('source_state_sha256',repmat('e',1,64));
manifest.runtime = runtime;
manifest.runtime_sha256 = runtime_sha256;
manifest.runtime_rechecked_after_run = true;
serial_before = local_serial_worker_report( ...
    runtime_sha256,'fixture-before-dispatch');
serial_after = local_serial_worker_report( ...
    runtime_sha256,'fixture-after-dispatch');
manifest.worker_runtime_validation = struct( ...
    'policy',config.worker_runtime_validation_policy, ...
    'before_dispatch',serial_before, ...
    'after_dispatch',serial_after, ...
    'all_computation_workers_checked',true, ...
    'runtime_sha256',runtime_sha256);
manifest.execution = struct('leaf_acceptance_policy', ...
    'strict-CR-or-LG-J1-and-J2-v1');
manifest.files = struct( ...
    'J1_csv','J1.csv','J2_csv','J2.csv', ...
    'geometric_coverage_json','coverage.json', ...
    'mat','results.mat','config_mat','config.mat', ...
    'json','unified.json');
manifest.hashes = struct( ...
    'algorithm','SHA-256', ...
    'input',input_sha, ...
    'J1_csv',ver10_file_sha256(paths.J1_csv), ...
    'J2_csv',ver10_file_sha256(paths.J2_csv), ...
    'geometric_coverage_json', ...
        ver10_file_sha256(paths.geometric_coverage_json), ...
    'mat',ver10_file_sha256(paths.mat), ...
    'config_mat',ver10_file_sha256(paths.config_mat));
local_write_json(paths.json,manifest);

options = local_options(paths);
bundle = validate_omega_mid_unified_artifacts( ...
    manifest,temporary_dir,'require_complete',false,options{:});
assert(bundle.records_variable_count == 1);
assert(bundle.leaf_count == 1 && bundle.attempt_count == 1);
assert(strcmp(bundle.leaf_attempt_evidence, ...
    'mat:records(:).leaves(:).attempts'));

hash_fields = {'J1_csv','J2_csv','geometric_coverage_json', ...
    'mat','config_mat'};
option_names = {'J1_file','J2_file','coverage_file', ...
    'mat_file','config_file'};
for k = 1:numel(hash_fields)
    source = paths.(hash_fields{k});
    tampered = fullfile(temporary_dir,sprintf('tampered_%d',k));
    [ok,message] = copyfile(source,tampered,'f');
    assert(ok,message);
    local_append_byte(tampered);
    bad_options = options;
    index = find(strcmp(bad_options,option_names{k}),1);
    bad_options{index+1} = tampered;
    local_assert_rejected(@() validate_omega_mid_unified_artifacts( ...
        manifest,temporary_dir,'require_complete',false, ...
        bad_options{:}), ...
        'validate_omega_mid_unified_artifacts:ArtifactHashMismatch');
end

for k = 1:3
    bad_manifest = manifest;
    if k == 1
        bad_manifest.summary.geometric_coverage_certified = false;
    elseif k == 2
        bad_manifest.config.value = 18;
    else
        bad_manifest.complete_certificate = 2;
    end
    bad_json = fullfile(temporary_dir,sprintf( ...
        'semantic_tamper_%d.json',k));
    local_write_json(bad_json,bad_manifest);
    bad_options = options;
    index = find(strcmp( ...
        bad_options,'unified_manifest_file'),1);
    bad_options{index+1} = bad_json;
    local_assert_rejected(@() validate_omega_mid_unified_artifacts( ...
        manifest,temporary_dir,'require_complete',false, ...
        bad_options{:}), ...
        ['validate_omega_mid_unified_artifacts:', ...
         'UnifiedManifestMismatch']);
end

% Updating both the config-file hash and copied unified JSON still cannot
% conceal a fingerprint payload whose SHA-256 is stale.
bad_config_file = fullfile(temporary_dir,'internally_bad_config.mat');
fingerprint_payload = 'altered payload with stale fingerprint';
save(bad_config_file,'config','fingerprint', ...
    'fingerprint_payload','-v7');
forged_manifest = manifest;
forged_manifest.hashes.config_mat = ...
    ver10_file_sha256(bad_config_file);
forged_json = fullfile(temporary_dir,'forged_unified.json');
local_write_json(forged_json,forged_manifest);
bad_options = options;
index = find(strcmp(bad_options,'config_file'),1);
bad_options{index+1} = bad_config_file;
index = find(strcmp(bad_options,'unified_manifest_file'),1);
bad_options{index+1} = forged_json;
local_assert_rejected(@() validate_omega_mid_unified_artifacts( ...
    forged_manifest,temporary_dir,'require_complete',false, ...
    bad_options{:}), ...
    'validate_omega_mid_unified_artifacts:ConfigMetadataMismatch');

local_test_publication_generation(paths,temporary_dir);

fprintf(['test_omega_mid_artifact_binding: PASS ', ...
    ['(five file-hash, three unified-metadata, and one config-payload ', ...
     'tamper cases rejected; eight generation payload tamper cases ', ...
     'gzip-content/pointer/boolean tamper and unlisted-file cleanup ', ...
     'rejected)\n']]);
clear cleanup
local_remove_tree(temporary_dir);
end


function local_test_publication_generation(source_paths,temporary_root)
generation_dir = fullfile(temporary_root,'publication_generation');
mkdir(generation_dir);
names = struct( ...
    'J1_OmegaMid_csv_gz','J1_OmegaMid.csv.gz', ...
    'J2_OmegaMid_csv_gz','J2_OmegaMid.csv.gz', ...
    'verification_summary_json','verification_summary.json', ...
    'verification_summary_markdown','verification_summary.md', ...
    'omega_mid_geometric_coverage_manifest', ...
        'omega_mid_geometric_coverage_manifest.json', ...
    'omega_mid_unified_manifest','omega_mid_unified_manifest.json', ...
    'omega_mid_unified_results_mat', ...
        'omega_mid_unified_results_fixture.mat', ...
    'config_mat','config.mat');
fields = fieldnames(names);
generation_paths = struct();
for k = 1:numel(fields)
    generation_paths.(fields{k}) = fullfile( ...
        generation_dir,names.(fields{k}));
end
J1_gzip = ver10_deterministic_gzip(source_paths.J1_csv, ...
    generation_paths.J1_OmegaMid_csv_gz);
J2_gzip = ver10_deterministic_gzip(source_paths.J2_csv, ...
    generation_paths.J2_OmegaMid_csv_gz);
local_write_text(generation_paths.verification_summary_json, ...
    '{"fixture":true}\n');
local_write_text(generation_paths.verification_summary_markdown, ...
    '# fixture\n');
copy_pairs = { ...
    source_paths.geometric_coverage_json, ...
        generation_paths.omega_mid_geometric_coverage_manifest; ...
    source_paths.json,generation_paths.omega_mid_unified_manifest; ...
    source_paths.mat,generation_paths.omega_mid_unified_results_mat; ...
    source_paths.config_mat,generation_paths.config_mat};
for k = 1:size(copy_pairs,1)
    [ok,message] = copyfile(copy_pairs{k,1},copy_pairs{k,2},'f');
    assert(ok,message);
end

generation = struct();
generation.schema = ...
    'lowerboundsineq.omega_mid_publication_generation.v2';
generation.files = names;
generation.sha256 = struct();
for k = 1:numel(fields)
    field = fields{k};
    generation.sha256.(field) = ...
        ver10_file_sha256(generation_paths.(field));
end
generation.sha256.J1_OmegaMid_csv_expanded_content = ...
    J1_gzip.expanded_content_sha256;
generation.sha256.J2_OmegaMid_csv_expanded_content = ...
    J2_gzip.expanded_content_sha256;
generation.compression = struct( ...
    'algorithm','gzip','options','-n -9', ...
    'roundtrip_verified',true, ...
    'independent_encodings_identical',true);
generation.artifact_resolution = struct( ...
    'results_mat_release_asset',struct( ...
        'owner','fixture-owner','repo','fixture-repo', ...
        'repository','fixture-owner/fixture-repo', ...
        'tag','fixture-tag', ...
        'name',names.omega_mid_unified_results_mat, ...
        'url',['https://github.com/fixture-owner/fixture-repo/', ...
            'releases/download/fixture-tag/', ...
            names.omega_mid_unified_results_mat], ...
        'sha256',generation.sha256.omega_mid_unified_results_mat));
generation.leaf_attempt_evidence = struct( ...
    'file',names.omega_mid_unified_results_mat, ...
    'sha256',generation.sha256.omega_mid_unified_results_mat, ...
    'config_file',names.config_mat, ...
    'config_sha256',generation.sha256.config_mat);
manifest_path = fullfile(generation_dir,'publication_manifest.json');
local_write_json(manifest_path,generation);
manifest_sha256 = ver10_file_sha256(manifest_path);
decoded = validate_omega_mid_publication_generation( ...
    generation_dir,manifest_sha256);
assert(strcmp(jsonencode(decoded),jsonencode(generation)));

pointer_path = fullfile(generation_dir,'.omega_mid_current.json');
local_write_text(pointer_path,'{"fixture_pointer":true}\n');
pointer_sha256 = ver10_file_sha256(pointer_path);
validate_omega_mid_publication_generation( ...
    generation_dir,manifest_sha256, ...
    'staging_pointer_sha256',pointer_sha256);
local_append_byte(pointer_path);
local_assert_rejected(@() ...
    validate_omega_mid_publication_generation( ...
        generation_dir,manifest_sha256, ...
        'staging_pointer_sha256',pointer_sha256), ...
    ['validate_omega_mid_publication_generation:', ...
     'StagingPointerHashMismatch']);
delete(pointer_path);

extra_path = fullfile(generation_dir,'.unlisted-user-data.txt');
local_write_text(extra_path,'must not be deleted');
local_assert_rejected(@() ...
    validate_omega_mid_publication_generation( ...
        generation_dir,manifest_sha256), ...
    ['validate_omega_mid_publication_generation:', ...
     'UnexpectedDirectoryEntry']);
delete(extra_path);

bad_boolean_generation = generation;
bad_boolean_generation.compression.roundtrip_verified = 2;
local_write_json(manifest_path,bad_boolean_generation);
bad_boolean_manifest_sha256 = ver10_file_sha256(manifest_path);
local_assert_rejected(@() ...
    validate_omega_mid_publication_generation( ...
        generation_dir,bad_boolean_manifest_sha256), ...
    'validate_omega_mid_publication_generation:BadManifest');
local_write_json(manifest_path,generation);
assert(strcmp(ver10_file_sha256(manifest_path),manifest_sha256));

for k = 1:numel(fields)
    field = fields{k};
    artifact = generation_paths.(field);
    backup = fullfile(temporary_root,sprintf( ...
        'generation_payload_%d.backup',k));
    [ok,message] = copyfile(artifact,backup,'f');
    assert(ok,message);
    local_append_byte(artifact);
    local_assert_rejected(@() ...
        validate_omega_mid_publication_generation( ...
            generation_dir,manifest_sha256), ...
        ['validate_omega_mid_publication_generation:', ...
         'ArtifactHashMismatch']);
    [ok,message] = copyfile(backup,artifact,'f');
    assert(ok,message);
    delete(backup);
end

bad_generation = generation;
bad_generation.sha256.J1_OmegaMid_csv_expanded_content = ...
    repmat('0',1,64);
local_write_json(manifest_path,bad_generation);
bad_manifest_sha256 = ver10_file_sha256(manifest_path);
local_assert_rejected(@() ...
    validate_omega_mid_publication_generation( ...
        generation_dir,bad_manifest_sha256), ...
    'ver10_verify_gzip_artifact:ContentHashMismatch');
local_write_json(manifest_path,generation);
assert(strcmp(ver10_file_sha256(manifest_path),manifest_sha256));
end


function options = local_options(paths)
options = { ...
    'J1_file',paths.J1_csv, ...
    'J2_file',paths.J2_csv, ...
    'coverage_file',paths.geometric_coverage_json, ...
    'mat_file',paths.mat, ...
    'config_file',paths.config_mat, ...
    'unified_manifest_file',paths.json};
end


function local_write_text(filename,value)
fid = fopen(filename,'w');
if fid < 0
    error('test_omega_mid_artifact_binding:WriteFailed', ...
        'Could not create %s.',filename);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid,'%s',value);
clear cleanup
end


function local_write_json(filename,value)
try
    encoded = jsonencode(value,'PrettyPrint',true);
catch
    encoded = jsonencode(value);
end
local_write_text(filename,[encoded,sprintf('\n')]);
end


function local_append_byte(filename)
fid = fopen(filename,'ab');
if fid < 0
    error('test_omega_mid_artifact_binding:TamperFailed', ...
        'Could not alter %s.',filename);
end
cleanup = onCleanup(@() fclose(fid));
fwrite(fid,uint8(10),'uint8');
clear cleanup
end


function local_assert_rejected(callback,identifier)
caught = false;
try
    callback();
catch ME
    if ~strcmp(ME.identifier,identifier)
        rethrow(ME);
    end
    caught = true;
end
assert(caught);
end


function local_remove_tree(pathname)
if exist(pathname,'dir')
    rmdir(pathname,'s');
end
end


function digest = local_sha256_bytes(bytes)
engine = javaMethod( ...
    'getInstance','java.security.MessageDigest','SHA-256');
bytes = uint8(bytes(:));
if ~isempty(bytes)
    engine.update(typecast(bytes,'int8'));
end
raw = typecast(engine.digest(),'uint8');
digest = lower(reshape(dec2hex(raw,2).',1,[]));
end


function report = local_serial_worker_report(runtime_sha256,phase)
report = struct( ...
    'schema','lowerboundsineq.worker-runtime-validation.v1', ...
    'phase',phase, ...
    'runtime_sha256',runtime_sha256, ...
    'worker_count',0, ...
    'all_workers_returned',true, ...
    'all_workers_full_runtime_json_match',true);
end
