%RUN_OMEGA_UP_RESIDUAL_FULL  Production Omega_up residual certificate.
%
% This script uses the exact grid and global Bernstein strong-residual
% estimator cited in the ver10 manuscript.  Per-task checkpoints make the
% computation safely resumable on liulabhpc.

project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root,'scripts_run'));
spectral_atlas_path = getenv('VER10_SPECTRAL_ATLAS');
if isempty(spectral_atlas_path) || ~exist(spectral_atlas_path,'file')
    error('run_omega_up_residual_full:MissingSpectralAtlas', ...
        ['Set VER10_SPECTRAL_ATLAS to the rigorous CR--LG atlas MAT ', ...
         'created by run_omega_up_spectral_atlas.']);
end
certificate_root = getenv('VER10_CERTIFICATE_ROOT');
if isempty(certificate_root)
    error('run_omega_up_residual_full:MissingCertificateRoot', ...
        ['Set VER10_CERTIFICATE_ROOT to a directory outside the clean ', ...
         'Git checkout.']);
end
output_dir = fullfile(certificate_root,'omega_up_all_residual');

mesh_params = struct( ...
    'estimator_backend','bernstein-strong', ...
    'bernstein_degree',11, ...
    'N_LG',16, ...
    'N_rho',64, ...
    'bound_order',2, ...
    'trial_order',4, ...
    'N_trial',8, ...
    'RT_order',4, ...
    'spectral_atlas_path',spectral_atlas_path, ...
    'eigenfunction_error_method','residual_flux', ...
    'lambda2_analytic_lower',true, ...
    'rt_solve_strategy','midpoint-defect');

manifest = run_omega_up_all_residual_parallel( ...
    'mode','interval', ...
    'workers',20, ...
    'eps_up','0.122', ...
    'Nx',976, ...
    'Ny',488, ...
    'Ny_axis',1952, ...
    'functional_scope','split', ...
    'jup_y_min','0.85', ...
    'mesh_params',mesh_params, ...
    'output_dir',output_dir, ...
    'run_name','ver10_omega_up_bernstein_split_prod', ...
    'resume',true, ...
    'retry_failed',true);

fprintf('Omega_up production certificate completed.\n');
fprintf('complete certificate: %d\n',manifest.summary.complete_certificate);
fprintf('errors: %d\n',manifest.summary.num_errors);
if ~manifest.summary.complete_certificate
    error('run_omega_up_residual_full:IncompleteCertificate', ...
        'The production run did not certify every requested functional.');
end
