%RUN_OMEGA_UP_RECTANGLE_TARGETED_SMOKE  Difficult production x-cells.
%
% The selected cells test the equilateral corner, the bottom strip next to
% the symmetry axis and the circular boundary, and the lower edge of the
% local JUP band.  They use exactly the production rectangle widths and
% degree-11 global Bernstein strong-residual estimator.

project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root,'scripts_run'));
spectral_atlas_path = getenv('VER10_SPECTRAL_ATLAS');

Nx = 976;
Ny = 488;
Ny_axis = 1952;
task_id = @(ix,iy) (ix-1)*Ny+iy;
target_task_ids = [ ...
    task_id(1,1), ...       % equilateral corner
    task_id(1,488), ...     % bottom strip, symmetry-axis side
    task_id(672,488), ...   % bottom strip, near circular boundary
    task_id(1,65), ...      % y=0.85 crossing, symmetry-axis side
    task_id(105,65)];       % y=0.85 crossing, off-axis side

mesh_params = struct( ...
    'estimator_backend','bernstein-strong', ...
    'bernstein_degree',11, ...
    'N_LG',16, ...
    'N_rho',64, ...
    'bound_order',2, ...
    'trial_order',4, ...
    'N_trial',8, ...
    'RT_order',4, ...
    'spectral_atlas_path',spectral_atlas_path, ...
    'eigenfunction_error_method','residual_flux', ...
    'lambda2_analytic_lower',true, ...
    'rt_solve_strategy','midpoint-defect');

manifest = run_omega_up_all_residual_parallel( ...
    'mode','interval', ...
    'workers',5, ...
    'eps_up','0.122', ...
    'Nx',Nx, ...
    'Ny',Ny, ...
    'Ny_axis',Ny_axis, ...
    'functional_scope','split', ...
    'jup_y_min','0.85', ...
    'mesh_params',mesh_params, ...
    'task_ids',target_task_ids, ...
    'output_dir',fullfile(project_root,'results','omega_up_all_residual'), ...
    'run_name','production_rectangle_bernstein_targeted_smoke', ...
    'resume',true, ...
    'retry_failed',true);

payload = load(fullfile(project_root,manifest.files.mat),'records');
fprintf('Targeted rectangle smoke (coverage_complete is intentionally false):\n');
for k = 1:numel(payload.records)
    record = payload.records{k};
    fprintf([ ...
        '  task=%d ix=%d iy=%d x=[%.17g,%.17g] y=[%.17g,%.17g] ', ...
        'JUP_scope=%d J1=%.8g J2=%.8g JUP=%.8g status=%s\n'], ...
        record.task_id,record.ix,record.iy, ...
        record.x_lo,record.x_hi,record.y_lo,record.y_hi, ...
        record.JUP_in_scope,record.J1_lower,record.J2_lower, ...
        record.JUP_upper,record.status);
end
