%RUN_OMEGA_UP_RESIDUAL_SMOKE  One production-size interval cell.
%
% This is an end-to-end INTLAB smoke, not a complete Omega_up certificate.
% The full-grid counts are retained so that the selected first cell has the
% same width and production mesh parameters as the final 20-worker run.

project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root,'scripts_run'));
output_dir = fullfile(project_root,'results','omega_up_all_residual');

manifest = run_omega_up_all_residual_parallel( ...
    'mode','interval', ...
    'workers',0, ...
    'eps_up','0.122', ...
    'Nx',976, ...
    'Ny',488, ...
    'Ny_axis',1952, ...
    'functional_scope','split', ...
    'jup_y_min','0.85', ...
    'max_tasks',1, ...
    'output_dir',output_dir, ...
    'run_name','production_bernstein_one_cell_smoke', ...
    'resume',true, ...
    'retry_failed',true);

fprintf('Omega_up unified residual smoke completed.\n');
fprintf('errors: %d\n',manifest.summary.num_errors);
fprintf('J1 required/certified: %d/%d\n', ...
    manifest.summary.num_J1_required, ...
    manifest.summary.num_J1_certified);
fprintf('J2 required/certified: %d/%d\n', ...
    manifest.summary.num_J2_required, ...
    manifest.summary.num_J2_certified);
fprintf('JUP required/certified: %d/%d\n', ...
    manifest.summary.num_JUP_required, ...
    manifest.summary.num_JUP_certified);
