%RUN_OMEGA_UP_AXIS_TARGETED_SMOKE  Two difficult production axis cells.
%
% This INTLAB smoke evaluates exactly
%   (1) the y=0.85 crossing interval, where JUP is still in scope, and
%   (2) the bottom axis interval, where J1/J2 are in scope and JUP is not.
% The production axis grid has width 0.122/1952=0.0000625.

project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root,'scripts_run'));
spectral_atlas_path = getenv('VER10_SPECTRAL_ATLAS');

eps_up = 0.122;
Nx = 976;
Ny = 488;
Ny_axis = 1952;
y_top = sqrt(3)/2;
axis_step = eps_up/Ny_axis;
iy_cross = ceil((y_top-0.85)/axis_step);
assert(iy_cross == 257);
assert(y_top-iy_cross*axis_step <= 0.85);
assert(0.85 <= y_top-(iy_cross-1)*axis_step);

first_axis_task = Nx*Ny;
target_task_ids = [ ...
    first_axis_task+iy_cross, ...
    first_axis_task+Ny_axis];

mesh_params = struct( ...
    'estimator_backend','bernstein-strong', ...
    'bernstein_degree',11, ...
    'N_LG',16, ...
    'N_rho',64, ...
    'bound_order',2, ...
    'trial_order',4, ...
    'N_trial',8, ...
    'RT_order',4, ...
    'spectral_atlas_path',spectral_atlas_path, ...
    'eigenfunction_error_method','residual_flux', ...
    'lambda2_analytic_lower',true, ...
    'rt_solve_strategy','midpoint-defect');

manifest = run_omega_up_all_residual_parallel( ...
    'mode','interval', ...
    'workers',2, ...
    'eps_up','0.122', ...
    'Nx',Nx, ...
    'Ny',Ny, ...
    'Ny_axis',Ny_axis, ...
    'functional_scope','split', ...
    'jup_y_min','0.85', ...
    'mesh_params',mesh_params, ...
    'task_ids',target_task_ids, ...
    'output_dir',fullfile(project_root,'results','omega_up_all_residual'), ...
    'run_name','production_axis_bernstein_targeted_smoke', ...
    'resume',true, ...
    'retry_failed',true);

payload = load(fullfile(project_root,manifest.files.mat),'records');
fprintf('Targeted axis smoke (coverage_complete is intentionally false):\n');
for k = 1:numel(payload.records)
    record = payload.records{k};
    fprintf([ ...
        '  task=%d iy=%d y=[%.17g,%.17g] JUP_scope=%d ', ...
        'J1=%.8g J2=%.8g JUP=%.8g status=%s\n'], ...
        record.task_id,record.iy,record.y_lo,record.y_hi, ...
        record.JUP_in_scope,record.J1_lower,record.J2_lower, ...
        record.JUP_upper,record.status);
end
