%RUN_UPPER_CONJECTURE_ATLAS_FULL  Production INTLAB certificate on liulabhpc.
%
% Environment variables expected on the compute node:
%   INTLAB_ROOT
%   LOWERBOUNDS_MESH_PATH
%   GMSH_COMMAND

certificate_root = getenv('VER10_CERTIFICATE_ROOT');
if isempty(certificate_root)
    error('run_upper_conjecture_atlas_full:MissingCertificateRoot', ...
        ['Set VER10_CERTIFICATE_ROOT to a directory outside the clean ', ...
         'Git checkout.']);
end
manifest = run_upper_conjecture_atlas( ...
    'mode','interval', ...
    'backend','p4', ...
    'trial_order',4, ...
    'N_trial',8, ...
    'workers',20, ...
    'y_min',0.06, ...
    'y_up',0.851, ...
    'residual_y_start',0.85, ...
    'dx',0.001, ...
    'dy',0.001, ...
    'output_dir',fullfile(certificate_root,'upper_conjecture'));
if ~manifest.component_complete_certificate
    error('run_upper_conjecture_atlas_full:IncompleteCertificate', ...
        'The thin-plus-compact atlas component is incomplete.');
end
