%RUN_MUHAT1_RAYLEIGH_HPC  Canonical HPC/INTLAB thin-sector certificate.
%
% Required environment variables:
%   INTLAB_ROOT             external INTLAB installation
%   VER10_CERTIFICATE_ROOT  output root outside the clean Git checkout

if isempty(getenv('INTLAB_ROOT'))
    error('run_muhat1_rayleigh_hpc:MissingIntlab', ...
        'Set INTLAB_ROOT to the external INTLAB installation.');
end
if isempty(getenv('VER10_CERTIFICATE_ROOT'))
    error('run_muhat1_rayleigh_hpc:MissingCertificateRoot', ...
        ['Set VER10_CERTIFICATE_ROOT to a fresh directory outside the ', ...
         'clean Git checkout.']);
end

[manifest,validation] = run_muhat1_rayleigh_certificate( ...
    'mode','interval', ...
    't','0.38', ...
    'degree',10, ...
    's_cells',200, ...
    's_lo','0', ...
    's_hi','1', ...
    'down_y_max','0.19', ...
    'down_y_cells',40, ...
    'progress_every',10, ...
    'production',true);

if ~manifest.complete_certificate || ~validation.complete
    error('run_muhat1_rayleigh_hpc:IncompleteCertificate', ...
        'The canonical thin-sector artifact did not pass final replay.');
end
