function [manifest,validation] = run_muhat1_rayleigh_certificate(varargin)
%RUN_MUHAT1_RAYLEIGH_CERTIFICATE Build and replay the thin-sector proof.
%
% A production certificate is accepted only for the canonical parameters
%
%   t0=0.38, s in [0,1], degree=10, 200 s-cells,
%   y in [0,0.19], and 40 cells in r=y^(1/3).
%
% Proof endpoints and frozen binary64 coefficients are written losslessly
% as IEEE hexadecimal strings.  The manifest is finalized only after an
% independent replay by VALIDATE_MUHAT1_RAYLEIGH_CERTIFICATE.

project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root,'src','degenerate'));
addpath(fullfile(project_root,'scripts_run'));

p = inputParser;
addParameter(p,'mode','interval',@(x) ischar(x) || isstring(x));
addParameter(p,'t','0.38',@(x) isnumeric(x) || ischar(x) || isstring(x));
addParameter(p,'degree',10,@(x) isnumeric(x) && isscalar(x));
addParameter(p,'s_cells',200,@(x) isnumeric(x) && isscalar(x));
addParameter(p,'s_lo','0',@(x) isnumeric(x) || ischar(x) || isstring(x));
addParameter(p,'s_hi','1',@(x) isnumeric(x) || ischar(x) || isstring(x));
addParameter(p,'down_y_max','0.19', ...
    @(x) isnumeric(x) || ischar(x) || isstring(x));
addParameter(p,'down_y_cells',40,@(x) isnumeric(x) && isscalar(x));
addParameter(p,'progress_every',10,@(x) isnumeric(x) && isscalar(x));
addParameter(p,'production',true,@(x) islogical(x) && isscalar(x));
addParameter(p,'output_dir','',@(x) ischar(x) || isstring(x));
parse(p,varargin{:});
opt = p.Results;
opt.mode = lower(char(opt.mode));
opt.t = local_decimal_text(opt.t,'t');
opt.s_lo = local_decimal_text(opt.s_lo,'s_lo');
opt.s_hi = local_decimal_text(opt.s_hi,'s_hi');
opt.down_y_max = local_decimal_text(opt.down_y_max,'down_y_max');
opt.degree = local_positive_integer(opt.degree,'degree');
opt.s_cells = local_positive_integer(opt.s_cells,'s_cells');
opt.down_y_cells = local_positive_integer( ...
    opt.down_y_cells,'down_y_cells');
opt.progress_every = local_nonnegative_integer( ...
    opt.progress_every,'progress_every');
if ~strcmp(opt.mode,'interval')
    error('run_muhat1_rayleigh_certificate:IntervalRequired', ...
        ['Certificate artifacts require mode=''interval''.  Call ', ...
         'muhat1_rayleigh_cover directly for exploratory double runs.']);
end
omega_up_all_prepare_worker(project_root,'interval');
global INTERVAL_MODE
if isempty(INTERVAL_MODE) || ~logical(INTERVAL_MODE)
    error('run_muhat1_rayleigh_certificate:IntervalInitFailed', ...
        'INTLAB interval mode was not enabled before runtime capture.');
end

if isempty(opt.output_dir)
    certificate_root = getenv('VER10_CERTIFICATE_ROOT');
    if isempty(certificate_root)
        error('run_muhat1_rayleigh_certificate:MissingOutputRoot', ...
            ['Set VER10_CERTIFICATE_ROOT or pass output_dir.  Proof ', ...
             'artifacts must not be written implicitly into the source tree.']);
    end
    opt.output_dir = fullfile(certificate_root,'muhat1_rayleigh_t038');
else
    opt.output_dir = char(opt.output_dir);
end

production_parameters_match = local_production_parameters_match(opt);
source = ver10_source_provenance(project_root);
if opt.production
    if ~strcmp(opt.mode,'interval') || ~production_parameters_match
        error('run_muhat1_rayleigh_certificate:NoncanonicalProduction', ...
            'A production run must use the canonical interval parameters.');
    end
    if ~source.git_status_available || source.git_dirty ...
            || isempty(source.git_commit)
        error('run_muhat1_rayleigh_certificate:DirtyProductionTree', ...
            'A production run requires a clean Git checkout at one commit.');
    end
    if local_is_within(opt.output_dir,project_root)
        error('run_muhat1_rayleigh_certificate:OutputInsideSourceTree', ...
            'The production output directory must be outside the checkout.');
    end
end

% Freeze the complete numerical runtime before forming any proof value.
% The independent replay below checks the same record again, but this
% before/after gate also prevents one artifact from spanning a dependency
% change during its original computation.
runtime = ver10_runtime_metadata();
runtime_payload = jsonencode(runtime);
runtime_sha256 = local_sha256_bytes(uint8(runtime_payload));

result = muhat1_rayleigh_cover( ...
    'mode',opt.mode, ...
    't',opt.t, ...
    'degree',opt.degree, ...
    's_cells',opt.s_cells, ...
    's_lo',opt.s_lo, ...
    's_hi',opt.s_hi, ...
    'down_y_max',opt.down_y_max, ...
    'down_y_cells',opt.down_y_cells, ...
    'progress_every',opt.progress_every);
source = ver10_assert_source_unchanged(project_root,source);
runtime_after = ver10_runtime_metadata();
runtime_after_payload = jsonencode(runtime_after);
runtime_after_sha256 = local_sha256_bytes(uint8(runtime_after_payload));
if ~strcmp(runtime_payload,runtime_after_payload) ...
        || ~strcmp(runtime_sha256,runtime_after_sha256)
    error('run_muhat1_rayleigh_certificate:RuntimeChanged', ...
        ['The proof runtime changed during the thin-sector computation. ', ...
         'One artifact cannot combine different INTLAB, Gmsh, or engine ', ...
         'states.']);
end

if ~isfolder(opt.output_dir)
    mkdir(opt.output_dir);
end
paths = local_artifact_paths(opt.output_dir);
local_require_new_artifact_paths(paths);
local_write_coefficients( ...
    paths.coefficients,result.coefficients, ...
    result.polynomial_lower,result.polynomial_upper);
local_write_cells(paths.cells,result.cells,opt.s_cells);
local_write_down_cells(paths.down_cells,result);

source_files = local_source_file_hashes(project_root);
artifact_hashes = struct( ...
    'algorithm','SHA-256', ...
    'coefficients_csv',ver10_file_sha256(paths.coefficients), ...
    'cells_csv',ver10_file_sha256(paths.cells), ...
    'down_cells_csv',ver10_file_sha256(paths.down_cells));

all_masses_positive = all(isfinite([result.cells.mass_lower])) ...
    && all([result.cells.mass_lower] > 0);
all_rayleigh_finite = all(isfinite([result.cells.rayleigh_lower])) ...
    && all(isfinite([result.cells.rayleigh_upper]));
all_down_finite = all(isfinite(result.down_scaled_lower_grid(:))) ...
    && all(isfinite(result.down_scaled_upper_grid(:)));
all_down_strict = all_down_finite ...
    && all(result.down_scaled_upper_grid(:) < 0);
candidate_complete = opt.production ...
    && production_parameters_match ...
    && strcmp(opt.mode,'interval') ...
    && source.git_status_available ...
    && ~source.git_dirty ...
    && source.source_unchanged_after_run ...
    && all_masses_positive ...
    && all_rayleigh_finite ...
    && all_down_strict ...
    && result.down_conjecture_verified;

manifest = struct();
manifest.schema = 'lowerboundsineq.muhat1-rayleigh.manifest.v2';
manifest.created_utc = local_utc_timestamp();
manifest.theorem = [ ...
    'lambda1(T) <= pi^2*P(T)^2/(12*A(T)^2) ', ...
    '+ sqrt(3)*pi^2/(3*A(T)) on the thin sector'];
manifest.rigor = local_if(strcmp(opt.mode,'interval'), ...
    'certified_interval_replay','exploratory_double');
manifest.profile = struct( ...
    'production_requested',opt.production, ...
    'production_parameters_match',production_parameters_match, ...
    'canonical_name','thin-rayleigh-t038-y019-v2');
manifest.config = struct( ...
    'mode',opt.mode, ...
    't_text',opt.t, ...
    'degree',opt.degree, ...
    's_cells',opt.s_cells, ...
    's_lo_text',opt.s_lo, ...
    's_hi_text',opt.s_hi, ...
    'down_y_max_text',opt.down_y_max, ...
    'down_y_cells',opt.down_y_cells, ...
    's_partition','uniform exact-rational index partition', ...
    'r_partition',[ ...
        'uniform binary64 partition through an outward upper endpoint ', ...
        'of the exact interval power down_y_max^(1/3)']);
manifest.cover = struct( ...
    's_closed_hull_text',{{opt.s_lo,opt.s_hi}}, ...
    'y_closed_hull_text',{{'0',opt.down_y_max}}, ...
    'theorem_s_domain','0 <= s < 1', ...
    'theorem_y_domain','0 < y <= 0.19', ...
    'closed_hull_is_safe_superset',true, ...
    'exact_s_cell_id_coverage',true, ...
    'exact_r_cell_id_coverage',true);
manifest.proof_representation = struct( ...
    'exact_rational_interval_exponents',true, ...
    'decimal_parameters_enter_intlab_as_text',true, ...
    'binary64_trial_generation_rounding','nearest via INTLAB setround(0)', ...
    'frozen_coefficient_encoding','IEEE-754 binary64 hex via num2hex', ...
    'proof_trial_encoding',[ ...
        'directed interval endpoints of the final monomial ', ...
        'polynomial p(z), replayed without rebuilding Legendre data'], ...
    'interval_endpoint_encoding','directed binary64 endpoint hex', ...
    'decimal_extrema_are_display_only',true, ...
    'replay_does_not_recompute_eigenvectors',true, ...
    'authoritative_trial_form','phi(z)=(1-z^2)*p(z)', ...
    'q_role',[ ...
        'binary64 midpoint Legendre coordinates retained for diagnostics; ', ...
        'serialized monomial intervals are authoritative']);
manifest.source = source;
manifest.source_files = source_files;
manifest.runtime = runtime;
manifest.runtime_sha256 = runtime_sha256;
manifest.runtime_rechecked_after_run = true;
manifest.summary = struct( ...
    'number_of_s_cells',opt.s_cells, ...
    'number_of_r_cells_per_s_cell',opt.down_y_cells, ...
    'number_of_down_cells',opt.s_cells*opt.down_y_cells, ...
    'all_masses_strictly_positive',all_masses_positive, ...
    'all_rayleigh_bounds_finite',all_rayleigh_finite, ...
    'all_down_bounds_finite',all_down_finite, ...
    'all_down_upper_bounds_strictly_negative',all_down_strict, ...
    'max_rayleigh_upper_display',result.max_rayleigh_upper, ...
    'max_rayleigh_upper_hex',local_hex(result.max_rayleigh_upper), ...
    'max_rayleigh_cell_id',result.max_cell_id, ...
    'max_down_scaled_upper_display',result.max_down_scaled_upper, ...
    'max_down_scaled_upper_hex',local_hex(result.max_down_scaled_upper), ...
    'max_down_s_cell_id',result.max_down_cell_id, ...
    'down_conjecture_verified',result.down_conjecture_verified);
manifest.files = struct( ...
    'manifest_json','manifest.json', ...
    'coefficients_csv','frozen_coefficients.csv', ...
    'cells_csv','cells.csv', ...
    'down_cells_csv','down_cells.csv', ...
    'checksums_sha256','checksums.sha256');
manifest.hashes = artifact_hashes;
manifest.self_validation = struct( ...
    'required',true, ...
    'status','pending', ...
    'validator_sha256',source_files.validator.sha256, ...
    'replay_from_frozen_coefficients',true);
manifest.complete_certificate = false;
manifest.complete_certificate_reason = ...
    'Pending independent replay of the serialized artifact.';

local_write_json(paths.manifest,manifest);
local_write_checksums(paths,artifact_hashes);
validation = validate_muhat1_rayleigh_certificate( ...
    paths.manifest, ...
    'require_complete_certificate',false, ...
    'allow_pending_self_validation',true);

manifest.self_validation.status = 'passed';
manifest.self_validation.replayed_max_down_scaled_upper_hex = ...
    validation.replayed_max_down_scaled_upper_hex;
manifest.self_validation.replayed_s_cells = validation.number_of_s_cells;
manifest.self_validation.replayed_down_cells = ...
    validation.number_of_down_cells;
manifest.complete_certificate = candidate_complete;
if candidate_complete
    manifest.complete_certificate_reason = ...
        'Canonical clean-source artifact passed lossless INTLAB replay.';
else
    manifest.complete_certificate_reason = [ ...
        'The artifact replayed successfully but is not a canonical ', ...
        'clean-source production certificate.'];
end
local_write_json(paths.manifest,manifest);
local_write_checksums(paths,artifact_hashes);

validation = validate_muhat1_rayleigh_certificate( ...
    paths.manifest, ...
    'require_complete_certificate',candidate_complete);
if candidate_complete && ~validation.complete
    error('run_muhat1_rayleigh_certificate:FinalValidationFailed', ...
        'The finalized production artifact did not pass replay.');
end
% The validator rechecks all proof-source file hashes.  This final Git
% comparison additionally catches a commit-only or status change during
% serialization and replay.
ver10_assert_source_unchanged(project_root,source);

fprintf('thin Rayleigh artifact: %s\n',paths.manifest);
fprintf('max Rayleigh upper: %.17g\n',result.max_rayleigh_upper);
fprintf('max thin scaled upper: %.17g\n',result.max_down_scaled_upper);
fprintf('complete certificate: %d\n',manifest.complete_certificate);
end


function paths = local_artifact_paths(output_dir)
paths = struct( ...
    'manifest',fullfile(output_dir,'manifest.json'), ...
    'coefficients',fullfile(output_dir,'frozen_coefficients.csv'), ...
    'cells',fullfile(output_dir,'cells.csv'), ...
    'down_cells',fullfile(output_dir,'down_cells.csv'), ...
    'checksums',fullfile(output_dir,'checksums.sha256'));
end


function local_require_new_artifact_paths(paths)
names = fieldnames(paths);
for k = 1:numel(names)
    filename = paths.(names{k});
    if isfile(filename)
        error('run_muhat1_rayleigh_certificate:ExistingArtifact', ...
            ['Refusing to overwrite %s.  Use a new empty output ', ...
             'directory for each certificate run.'],filename);
    end
end
end


function local_write_coefficients( ...
        filename,coefficients,polynomial_lower,polynomial_upper)
fid = fopen(filename,'wt');
if fid < 0
    error('run_muhat1_rayleigh_certificate:CannotWrite', ...
        'Cannot write %s.',filename);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid,'id');
for j = 1:size(coefficients,2)
    fprintf(fid,',q%02d_hex',j);
end
for j = 1:size(polynomial_lower,2)
    fprintf(fid,',p%02d_lo_hex,p%02d_hi_hex',j,j);
end
fprintf(fid,'\n');
for i = 1:size(coefficients,1)
    fprintf(fid,'%d',i);
    for j = 1:size(coefficients,2)
        fprintf(fid,',%s',local_hex(coefficients(i,j)));
    end
    for j = 1:size(polynomial_lower,2)
        fprintf(fid,',%s,%s', ...
            local_hex(polynomial_lower(i,j)), ...
            local_hex(polynomial_upper(i,j)));
    end
    fprintf(fid,'\n');
end
clear cleanup
end


function local_write_cells(filename,cells,partition_count)
fid = fopen(filename,'wt');
if fid < 0
    error('run_muhat1_rayleigh_certificate:CannotWrite', ...
        'Cannot write %s.',filename);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid,[ ...
    'id,s_left_index,s_right_index,s_partition_count,', ...
    's_eval_lo_hex,s_eval_hi_hex,mass_lower_hex,mass_upper_hex,', ...
    'midpoint_ritz_hex,rayleigh_lower_hex,rayleigh_upper_hex,', ...
    'target_11_5_verified,down_scaled_upper_hex\n']);
for i = 1:numel(cells)
    c = cells(i);
    fprintf(fid,'%d,%d,%d,%d,%s,%s,%s,%s,%s,%s,%s,%d,%s\n', ...
        c.id,i-1,i,partition_count, ...
        local_hex(c.s_eval_lo),local_hex(c.s_eval_hi), ...
        local_hex(c.mass_lower),local_hex(c.mass_upper), ...
        local_hex(c.midpoint_ritz),local_hex(c.rayleigh_lower), ...
        local_hex(c.rayleigh_upper),c.target_11_5_verified, ...
        local_hex(c.down_scaled_upper));
end
clear cleanup
end


function local_write_down_cells(filename,result)
n_s = size(result.down_scaled_upper_grid,1);
n_r = size(result.down_scaled_upper_grid,2);
fid = fopen(filename,'wt');
if fid < 0
    error('run_muhat1_rayleigh_certificate:CannotWrite', ...
        'Cannot write %s.',filename);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid,[ ...
    's_cell_id,r_cell_id,r_eval_lo_hex,r_eval_hi_hex,', ...
    'scaled_lower_hex,scaled_upper_hex\n']);
for i = 1:n_s
    for j = 1:n_r
        fprintf(fid,'%d,%d,%s,%s,%s,%s\n', ...
            i,j,local_hex(result.r_eval_lo(j)), ...
            local_hex(result.r_eval_hi(j)), ...
            local_hex(result.down_scaled_lower_grid(i,j)), ...
            local_hex(result.down_scaled_upper_grid(i,j)));
    end
end
clear cleanup
end


function source_files = local_source_file_hashes(project_root)
entries = { ...
    'algorithm','src/degenerate/muhat1_rayleigh_cover.m'; ...
    'driver','scripts_run/run_muhat1_rayleigh_certificate.m'; ...
    'production_wrapper','scripts_run/run_muhat1_rayleigh_hpc.m'; ...
    'validator','src/degenerate/validate_muhat1_rayleigh_certificate.m'; ...
    'source_provenance','scripts_run/ver10_source_provenance.m'; ...
    'source_unchanged','scripts_run/ver10_assert_source_unchanged.m'; ...
    'runtime_metadata','scripts_run/ver10_runtime_metadata.m'; ...
    'runtime_tree_hash','scripts_run/ver10_directory_sha256.m'; ...
    'intlab_init_lock','scripts_run/ver10_acquire_intlab_init_lock.m'; ...
    'intlab_config','my_intlab_config.m'; ...
    'intlab_worker_config','scripts_run/my_intlab_config_worker.m'; ...
    'runtime_prepare_worker','scripts_run/omega_up_all_prepare_worker.m'; ...
    'file_sha256','scripts_run/ver10_file_sha256.m'};
source_files = struct();
for k = 1:size(entries,1)
    relative = entries{k,2};
    filename = fullfile(project_root,strrep(relative,'/',filesep));
    source_files.(entries{k,1}) = struct( ...
        'path',relative, ...
        'sha256',ver10_file_sha256(filename));
end
end


function local_write_json(filename,value)
fid = fopen(filename,'wt');
if fid < 0
    error('run_muhat1_rayleigh_certificate:CannotWrite', ...
        'Cannot write %s.',filename);
end
cleanup = onCleanup(@() fclose(fid));
try
    encoded = jsonencode(value,'PrettyPrint',true);
catch
    encoded = jsonencode(value);
end
fprintf(fid,'%s\n',encoded);
clear cleanup
end


function local_write_checksums(paths,artifact_hashes)
manifest_hash = ver10_file_sha256(paths.manifest);
fid = fopen(paths.checksums,'wt');
if fid < 0
    error('run_muhat1_rayleigh_certificate:CannotWrite', ...
        'Cannot write %s.',paths.checksums);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid,'%s  manifest.json\n',manifest_hash);
fprintf(fid,'%s  frozen_coefficients.csv\n', ...
    artifact_hashes.coefficients_csv);
fprintf(fid,'%s  cells.csv\n',artifact_hashes.cells_csv);
fprintf(fid,'%s  down_cells.csv\n',artifact_hashes.down_cells_csv);
clear cleanup
end


function tf = local_production_parameters_match(opt)
tf = strcmp(opt.mode,'interval') ...
    && strcmp(opt.t,'0.38') ...
    && opt.degree == 10 ...
    && opt.s_cells == 200 ...
    && strcmp(opt.s_lo,'0') ...
    && strcmp(opt.s_hi,'1') ...
    && strcmp(opt.down_y_max,'0.19') ...
    && opt.down_y_cells == 40;
end


function tf = local_is_within(candidate,parent)
candidate = local_canonical_path(candidate);
parent = local_canonical_path(parent);
tf = strcmp(candidate,parent) ...
    || startsWith(candidate,[parent,filesep]);
end


function canonical = local_canonical_path(filename)
try
    file_object = javaObject('java.io.File',char(filename));
    canonical = char(file_object.getCanonicalPath());
catch
    canonical = char(filename);
end
while numel(canonical) > 1 && canonical(end) == filesep
    canonical(end) = [];
end
end


function value = local_decimal_text(value,name)
if isnumeric(value) && isscalar(value) && isfinite(value)
    value = sprintf('%.17g',value);
elseif ischar(value) || (isstring(value) && isscalar(value))
    value = strtrim(char(value));
else
    error('%s must be a finite scalar or decimal string.',name);
end
if isempty(regexp(value, ...
        '^[+-]?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[eE][+-]?[0-9]+)?$', ...
        'once')) || ~isfinite(str2double(value))
    error('%s must be a finite decimal string.',name);
end
end


function value = local_positive_integer(value,name)
if ~(isfinite(value) && value >= 1 && value == floor(value))
    error('%s must be a positive integer.',name);
end
value = double(value);
end


function value = local_nonnegative_integer(value,name)
if ~(isfinite(value) && value >= 0 && value == floor(value))
    error('%s must be a nonnegative integer.',name);
end
value = double(value);
end


function encoded = local_hex(value)
if ~(isnumeric(value) && isscalar(value) && isreal(value))
    error('run_muhat1_rayleigh_certificate:InvalidHexValue', ...
        'Only real binary64 scalars can be serialized.');
end
encoded = lower(num2hex(double(value)));
end


function digest = local_sha256_bytes(bytes)
try
    engine = javaMethod( ...
        'getInstance','java.security.MessageDigest','SHA-256');
catch ME
    error('run_muhat1_rayleigh_certificate:NoSHA256', ...
        'Cannot initialize SHA-256: %s',ME.message);
end
bytes = uint8(bytes(:));
if ~isempty(bytes)
    engine.update(typecast(bytes,'int8'));
end
raw = typecast(engine.digest(),'uint8');
digest = lower(reshape(dec2hex(raw,2).',1,[]));
end


function stamp = local_utc_timestamp()
if exist('OCTAVE_VERSION','builtin')
    stamp = strftime('%Y-%m-%dT%H:%M:%SZ',gmtime(time()));
else
    stamp = char(datetime('now','TimeZone','UTC', ...
        'Format','yyyy-MM-dd''T''HH:mm:ss''Z'''));
end
end


function value = local_if(condition,yes_value,no_value)
if condition
    value = yes_value;
else
    value = no_value;
end
end
