%RUN_ISOSCELES_HESSIAN_PRECISION_SCAN  Verified Hessian accuracy by height.
%
% For T_h=conv{(0,0),(1,0),(1/2,h)}, this script certifies the two
% coordinate-directional derivatives of lambda_2 and lambda_3 whenever
% the adjacent LG/Ritz/CR--Liu endpoints prove simplicity.
% Spectral endpoints are computed once per height by
% Lehmann--Goerisch + conforming Ritz + CR--Liu and are reused for both
% directions.  The Hessian enclosure uses degree-11 global Bernstein
% bubbles, exactly as in the Omega_up production computation.
%
% Required:
%   VER10_ISOSCELES_OUTPUT=/absolute/output/directory

project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root,'scripts_run'));
output_dir = getenv('VER10_ISOSCELES_OUTPUT');
if isempty(output_dir)
    error('run_isosceles_hessian_precision_scan:MissingOutput', ...
        'Set VER10_ISOSCELES_OUTPUT to an absolute output directory.');
end
if ~exist(output_dir,'dir')
    mkdir(output_dir);
end

omega_up_all_prepare_worker(project_root,'interval');
global INTERVAL_MODE
if ~logical(INTERVAL_MODE)
    error('run_isosceles_hessian_precision_scan:IntervalInitFailed', ...
        'INTLAB interval mode was not enabled.');
end

degree = 11;
spectral_indices = [2,3];
certificate_index = max(spectral_indices);
N_LG = 16;
N_rho = 64;
bound_order = 2;
height_labels = { ...
    '0.30','0.40','0.50','0.60','0.70', ...
    '0.75','0.80','0.85','sqrt(3)/2'};
heights = zeros(size(height_labels));
for k = 1:numel(height_labels)-1
    heights(k) = str2double(height_labels{k});
end
heights(end) = sqrt(3)/2;
direction_names = {'x','y'};
directions = {[1,0],[0,1]};

source = ver10_source_provenance(project_root);
started_at = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyy-MM-dd''T''HH:mm:ssXXX'));
scan_timer = tic;
rows = repmat(local_empty_row(),0,1);
certificates = cell(numel(heights),1);
diagnostics = cell( ...
    numel(heights),numel(spectral_indices),numel(directions));

for kh = 1:numel(heights)
    h = heights(kh);
    triangle = I_intval([0,0,1,0,0.5,h]);
    fprintf('height %s: spectral certificate ...\n',height_labels{kh});
    spectral_timer = tic;
    certificate = triangle_spectral_certificate_cr_lg( ...
        triangle,N_LG,N_rho,bound_order,certificate_index);
    spectral_seconds = toc(spectral_timer);
    certificates{kh} = certificate;
    spectral_options = struct('reference_certificate',certificate);

    for ki = 1:numel(spectral_indices)
        index = spectral_indices(ki);
        for kd = 1:numel(directions)
            row = local_empty_row();
            row.height_label = string(height_labels{kh});
            row.height_lower = h;
            row.height_upper = h;
            row.spectral_index = index;
            row.direction = string(direction_names{kd});
            row.degree = degree;
            row.trial_dimension = (degree-1)*(degree-2)/2;
            row.N_LG = N_LG;
            row.N_rho = N_rho;
            row.bound_order = bound_order;
            row.spectral_seconds = spectral_seconds;
            direction_timer = tic;
            try
                [lambda,dlambda,ddlo,ddhi,diag] = ...
                    calc_ddlambda_i_bernstein_strong_bounds( ...
                        index,triangle,directions{kd},degree, ...
                        spectral_options);
                diagnostics{kh,ki,kd} = diag;
                lower = I_inf(ddlo);
                upper = I_sup(ddhi);
                centre = (lower+upper)/2;
                half_width = (upper-lower)/2;
                relative_half_width = ...
                    half_width/max(abs(centre),realmin);

                row.status = "ok";
                row.lambda_lower = I_inf(lambda);
                row.lambda_upper = I_sup(lambda);
                row.dlambda_lower = I_inf(dlambda);
                row.dlambda_upper = I_sup(dlambda);
                row.ddlambda_lower = lower;
                row.ddlambda_upper = upper;
                row.ddlambda_midpoint = centre;
                row.ddlambda_width = upper-lower;
                row.ddlambda_half_width = half_width;
                row.relative_half_width = relative_half_width;
                row.certified_digits = ...
                    max(0,-log10(relative_half_width));
                row.contains_zero = lower <= 0 && upper >= 0;
                row.lambda_enclosure_width = ...
                    I_sup(lambda)-I_inf(lambda);
                row.lambda_i_LG_lower = ...
                    I_inf(diag.lambda_i_LG_lower);
                row.lambda_i_Ritz_upper = ...
                    I_sup(diag.lambda_i_Ritz_upper);
                row.lambda_ip1_lower = ...
                    I_inf(diag.lambda_ip1_lower);
                row.gap_minus = I_inf(diag.gap_minus);
                row.gap_plus = I_inf(diag.gap_plus);
                row.residual_gap = I_inf(diag.residual_gap);
                row.eigenfunction_residual = ...
                    I_sup(diag.eigenfunction_strong_residual);
                row.material_residual = ...
                    I_sup(diag.material_strong_residual);
                row.eps_0 = I_sup(diag.eps_0);
                row.eps_a = I_sup(diag.eps_a);
                row.center_interval_lower = ...
                    I_inf(diag.core.center_h);
                row.center_interval_upper = ...
                    I_sup(diag.core.center_h);
                row.algebraic_error = I_sup(diag.core.eps_D);
                row.lower_residual_correction = ...
                    I_sup(diag.core.lower_residual_correction);
                row.upper_residual_correction = ...
                    I_sup(diag.core.upper_residual_correction);
                row.error_message = "";
            catch ME
                row.status = "failed";
                row.error_message = string(getReport(ME,'extended', ...
                    'hyperlinks','off'));
            end
            row.hessian_seconds = toc(direction_timer);
            rows(end+1,1) = row; %#ok<SAGROW>
            fprintf(['height %s, lambda_%d, direction %s: %s, ', ...
                '[%.16e, %.16e], width %.3e\n'], ...
                height_labels{kh},index,direction_names{kd}, ...
                char(row.status),row.ddlambda_lower, ...
                row.ddlambda_upper,row.ddlambda_width);
        end
    end
end

wall_seconds = toc(scan_timer);
completed_at = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyy-MM-dd''T''HH:mm:ssXXX'));
result_table = struct2table(rows);
csv_path = fullfile(output_dir, ...
    'isosceles_hessian_precision_lambda2_lambda3.csv');
mat_path = fullfile(output_dir, ...
    'isosceles_hessian_precision_lambda2_lambda3.mat');
json_path = fullfile(output_dir, ...
    'isosceles_hessian_precision_lambda2_lambda3_manifest.json');
writetable(result_table,csv_path);
save(mat_path,'result_table','certificates','diagnostics','source', ...
    'degree','spectral_indices','certificate_index', ...
    'N_LG','N_rho','bound_order','height_labels', ...
    'started_at','completed_at','wall_seconds','-v7.3');

manifest = struct();
manifest.schema = ...
    'lowerboundsineq.isosceles-hessian-precision-scan.v2';
manifest.rigorous = true;
manifest.interval_library = 'INTLAB';
manifest.triangles = ...
    'conv{(0,0),(1,0),(1/2,h)}';
manifest.height_labels = height_labels;
manifest.directions = direction_names;
manifest.spectral_indices = spectral_indices;
manifest.certificate_index = certificate_index;
manifest.degree = degree;
manifest.trial_dimension = (degree-1)*(degree-2)/2;
manifest.N_LG = N_LG;
manifest.N_rho = N_rho;
manifest.bound_order = bound_order;
manifest.started_at_utc = started_at;
manifest.completed_at_utc = completed_at;
manifest.wall_seconds = wall_seconds;
manifest.num_rows = height(result_table);
manifest.num_success = sum(result_table.status == "ok");
manifest.num_failed = sum(result_table.status ~= "ok");
manifest.source = source;
manifest.csv_sha256 = ver10_file_sha256(csv_path);
manifest.mat_sha256 = ver10_file_sha256(mat_path);
fid = fopen(json_path,'w');
if fid < 0
    error('run_isosceles_hessian_precision_scan:JsonOpenFailed', ...
        'Could not open %s.',json_path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid,'%s\n',jsonencode(manifest,'PrettyPrint',true));
clear cleanup

fprintf('Isosceles Hessian precision scan complete in %.1f s.\n', ...
    wall_seconds);
fprintf('CSV: %s\n',csv_path);
fprintf('MAT: %s\n',mat_path);
fprintf('JSON: %s\n',json_path);


function row = local_empty_row()
nan_value = NaN;
row = struct( ...
    'height_label',"", ...
    'height_lower',nan_value, ...
    'height_upper',nan_value, ...
    'spectral_index',nan_value, ...
    'direction',"", ...
    'degree',nan_value, ...
    'trial_dimension',nan_value, ...
    'N_LG',nan_value, ...
    'N_rho',nan_value, ...
    'bound_order',nan_value, ...
    'status',"", ...
    'lambda_lower',nan_value, ...
    'lambda_upper',nan_value, ...
    'dlambda_lower',nan_value, ...
    'dlambda_upper',nan_value, ...
    'ddlambda_lower',nan_value, ...
    'ddlambda_upper',nan_value, ...
    'ddlambda_midpoint',nan_value, ...
    'ddlambda_width',nan_value, ...
    'ddlambda_half_width',nan_value, ...
    'relative_half_width',nan_value, ...
    'certified_digits',nan_value, ...
    'contains_zero',false, ...
    'lambda_enclosure_width',nan_value, ...
    'lambda_i_LG_lower',nan_value, ...
    'lambda_i_Ritz_upper',nan_value, ...
    'lambda_ip1_lower',nan_value, ...
    'gap_minus',nan_value, ...
    'gap_plus',nan_value, ...
    'residual_gap',nan_value, ...
    'eigenfunction_residual',nan_value, ...
    'material_residual',nan_value, ...
    'eps_0',nan_value, ...
    'eps_a',nan_value, ...
    'center_interval_lower',nan_value, ...
    'center_interval_upper',nan_value, ...
    'algebraic_error',nan_value, ...
    'lower_residual_correction',nan_value, ...
    'upper_residual_correction',nan_value, ...
    'spectral_seconds',nan_value, ...
    'hessian_seconds',nan_value, ...
    'error_message',"");
end
