%RUN_OMEGA_MID_UNIFIED_FULL  Production Omega_mid certificate for J1/J2.
%
% This is the ver10 liulabhpc wrapper.  It covers every row of
% inputs/cell_def.csv, uses one shared eigenvalue computation per cell for
% J1 and J2, and writes atomic resumable chunk checkpoints.  The driver
% refuses to start a complete interval run from a dirty Git checkout.

project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root,'scripts_run'));
results_root = fullfile(project_root,'results');
target_J1 = fullfile(results_root,'J1_OmegaMid.csv');
target_J2 = fullfile(results_root,'J2_OmegaMid.csv');
summary_json = fullfile(results_root,'verification_summary.json');
summary_markdown = fullfile(results_root,'verification_summary.md');
public_targets = { ...
    target_J1,target_J2,summary_json,summary_markdown};
publication_journal = fullfile( ...
    results_root,'.omega_mid_publication_journal.mat');
local_recover_publication(publication_journal,public_targets);

manifest = run_omega_mid_unified_parallel( ...
    'mode','interval', ...
    'workers',20, ...
    'input_file',fullfile(project_root,'inputs','cell_def.csv'), ...
    'chunk_size',256, ...
    'checkpoint_every',32, ...
    'max_subdivision_depth',8, ...
    'max_fem_refinement_level',2, ...
    'minimum_cr_mesh_size',0.005, ...
    'minimum_lg_mesh_size',0.025, ...
    'run_name','ver10_omega_mid_unified_prod', ...
    'resume',true, ...
    'retry_failed',true);

if ~manifest.complete_certificate
    error('run_omega_mid_unified_full:IncompleteCertificate', ...
        ['The unified production run did not produce a complete, clean, ', ...
         'strict interval certificate.  Public result files were not ', ...
         'modified.']);
end

% Publish only after the manifest has certified exact full input coverage.
% The legacy public validator consumes these canonical paths and requires
% status=ok, finite J_lower>0, and verified=1 on every input cell id.
run_dir = fullfile(project_root,'results','omega_mid_unified', ...
    'ver10_omega_mid_unified_prod');
source_J1 = fullfile(run_dir,'J1_OmegaMid.csv');
source_J2 = fullfile(run_dir,'J2_OmegaMid.csv');
local_validate_public_pair(source_J1,source_J2, ...
    fullfile(project_root,'inputs','cell_def.csv'));

publication = local_begin_publication( ...
    {source_J1,source_J2}, ...
    public_targets,publication_journal);
try
    validator = VerifyTriangleInequalities();
    validator.run();
    local_regenerate_summary(project_root,summary_json);
    local_validate_public_pair(target_J1,target_J2, ...
        fullfile(project_root,'inputs','cell_def.csv'));
    local_validate_public_summary(summary_json,summary_markdown);
    local_commit_publication(publication);
catch ME
    if strcmp(publication.state,'prepared')
        local_rollback_publication(publication);
    else
        local_cleanup_files(publication.staged);
        local_cleanup_files(publication.backups);
    end
    rethrow(ME);
end
local_publish_versioned_generation( ...
    project_root,manifest,public_targets);

fprintf('Omega_mid unified production run finished.\n');
fprintf('complete certificate: %d\n',manifest.complete_certificate);
fprintf('strict records: %d/%d\n', ...
    manifest.summary.num_strict_records, ...
    manifest.summary.num_selected_cells);
fprintf('minimum J1 lower: %.17g\n', ...
    manifest.summary.minimum_J1_lower);
fprintf('minimum J2 lower: %.17g\n', ...
    manifest.summary.minimum_J2_lower);


function local_validate_public_pair(source_J1,source_J2,input_file)
expected_table = readtable(input_file);
expected_ids = sort(double(expected_table.i(:)));
J1 = local_validate_public_csv(source_J1,'J1',expected_ids);
J2 = local_validate_public_csv(source_J2,'J2',expected_ids);
[~,order1] = sort(double(J1.cell_id));
[~,order2] = sort(double(J2.cell_id));
common_fields = {'method','LG_escalation_policy', ...
    'fem_refinement_scheme','fem_refinement_used', ...
    'max_fem_refinement_level_allowed', ...
    'minimum_cr_mesh_size_allowed','minimum_lg_mesh_size_allowed', ...
    'max_cr_refinement_level_used','max_lg_refinement_level_used', ...
    'minimum_cr_mesh_size_used','minimum_lg_mesh_size_used', ...
    'lambda1_lower','LG_rho_lower', ...
    'LG_ritz_upper','LG_separation_margin_lower','LG_mu_upper', ...
    'LG_B_verified_spd', ...
    'shared_eigenvalue_computation','strict_checks_passed', ...
    'subdivision_used','leaf_count','max_leaf_depth', ...
    'max_subdivision_depth_allowed','evaluated_node_count', ...
    'spectral_solve_count','LG_shift_method', ...
    'LG_fallback_used','LG_fallback_reason', ...
    'eigenvalue_total_seconds','LG_CR_shift_seconds', ...
    'LG_fallback_node_count','LG_analytic_shift_node_count', ...
    'LG_CR_Liu_shift_node_count','direct_CR_node_count'};
for k = 1:numel(common_fields)
    name = common_fields{k};
    left = J1.(name)(order1,:);
    right = J2.(name)(order2,:);
    if ~isequaln(left,right)
        error('run_omega_mid_unified_full:UnsharedSpectralRows', ...
            'J1/J2 differ in the shared spectral column %s.',name);
    end
end
end


function table_value = local_validate_public_csv( ...
    filename,conjecture,expected_ids)
if ~exist(filename,'file')
    error('run_omega_mid_unified_full:MissingArtifact', ...
        'Cannot publish missing artifact: %s',filename);
end
table_value = readtable(filename,'TextType','string');
required = {'conjecture','cell_id','verified','J_lower','status', ...
    'note','run_timestamp','certificate_status','rigorous', ...
    'method','LG_escalation_policy','fem_refinement_scheme', ...
    'fem_refinement_used','max_fem_refinement_level_allowed', ...
    'minimum_cr_mesh_size_allowed','minimum_lg_mesh_size_allowed', ...
    'max_cr_refinement_level_used','max_lg_refinement_level_used', ...
    'minimum_cr_mesh_size_used','minimum_lg_mesh_size_used', ...
    'lambda1_lower','LG_rho_lower', ...
    'LG_ritz_upper','LG_separation_margin_lower','LG_mu_upper', ...
    'LG_B_verified_spd', ...
    'subdivision_used','leaf_count','max_leaf_depth', ...
    'max_subdivision_depth_allowed','evaluated_node_count', ...
    'spectral_solve_count', ...
    'LG_shift_method','LG_fallback_used','LG_fallback_reason', ...
    'eigenvalue_total_seconds','LG_CR_shift_seconds', ...
    'LG_fallback_node_count','LG_analytic_shift_node_count', ...
    'LG_CR_Liu_shift_node_count','direct_CR_node_count', ...
    'shared_eigenvalue_computation','strict_checks_passed'};
if ~all(ismember(required,table_value.Properties.VariableNames))
    error('run_omega_mid_unified_full:BadPublicSchema', ...
        '%s lacks a required public or provenance column.',filename);
end
ids = double(table_value.cell_id(:));
if height(table_value) ~= numel(expected_ids) ...
        || numel(unique(ids)) ~= numel(ids) ...
        || ~isequal(sort(ids),expected_ids)
    error('run_omega_mid_unified_full:BadPublicCoverage', ...
        '%s does not cover the exact input cell-id set.',filename);
end
if ~all(strcmpi(strtrim(string(table_value.conjecture)),conjecture)) ...
        || ~all(double(table_value.verified) == 1) ...
        || ~all(isfinite(double(table_value.J_lower)) ...
            & double(table_value.J_lower) > 0) ...
        || ~all(strcmpi(strtrim(string(table_value.status)),'ok')) ...
        || ~all(strcmp( ...
            strtrim(string(table_value.certificate_status)), ...
            'certified_interval')) ...
        || ~all(double(table_value.rigorous) == 1) ...
        || ~all(isfinite(double(table_value.lambda1_lower)) ...
            & double(table_value.lambda1_lower) > 0) ...
        || ~all(double(table_value.shared_eigenvalue_computation) == 1) ...
        || ~all(double(table_value.strict_checks_passed) == 1)
    error('run_omega_mid_unified_full:BadPublicCertificate', ...
        '%s contains a non-strict or nonfinite certificate row.',filename);
end
methods = strtrim(string(table_value.method));
if ~all(ismember(methods,["CR","LG","SUBDIVISION"]))
    error('run_omega_mid_unified_full:BadPublicMethod', ...
        '%s contains an unknown eigenvalue method.',filename);
end
if ~all(strcmp(strtrim(string(table_value.LG_escalation_policy)), ...
        'LG-input-or-terminal-depth-after-CR-refinement-v1'))
    error('run_omega_mid_unified_full:BadLGEscalationPolicy', ...
        '%s does not use the production LG escalation policy.',filename);
end
if ~all(strcmp(strtrim(string(table_value.fem_refinement_scheme)), ...
        'dyadic-CR-then-terminal-LG-v1'))
    error('run_omega_mid_unified_full:BadFEMRefinementPolicy', ...
        '%s does not use the production FEM refinement scheme.', ...
        filename);
end
subdivision = methods == "SUBDIVISION";
leaf_count = double(table_value.leaf_count);
max_leaf_depth = double(table_value.max_leaf_depth);
evaluated_node_count = double(table_value.evaluated_node_count);
spectral_solve_count = double(table_value.spectral_solve_count);
max_fem_allowed = double( ...
    table_value.max_fem_refinement_level_allowed);
min_cr_allowed = double(table_value.minimum_cr_mesh_size_allowed);
min_lg_allowed = double(table_value.minimum_lg_mesh_size_allowed);
max_cr_used = double(table_value.max_cr_refinement_level_used);
max_lg_used = double(table_value.max_lg_refinement_level_used);
min_cr_used = double(table_value.minimum_cr_mesh_size_used);
min_lg_used = double(table_value.minimum_lg_mesh_size_used);
fem_refinement_used = double(table_value.fem_refinement_used);
subdivision_used = double(table_value.subdivision_used);
max_subdivision_allowed = double( ...
    table_value.max_subdivision_depth_allowed);
if any(~isfinite(evaluated_node_count) ...
        | evaluated_node_count < 1 ...
        | evaluated_node_count ~= floor(evaluated_node_count) ...
        | ~isfinite(spectral_solve_count) ...
        | spectral_solve_count < evaluated_node_count ...
        | spectral_solve_count ~= floor(spectral_solve_count) ...
        | ~isfinite(leaf_count) | leaf_count < 1 ...
        | leaf_count ~= floor(leaf_count) ...
        | ~isfinite(max_leaf_depth) | max_leaf_depth < 0 ...
        | max_leaf_depth ~= floor(max_leaf_depth) ...
        | ~isfinite(max_subdivision_allowed) ...
        | max_subdivision_allowed < 0 ...
        | max_subdivision_allowed ~= floor(max_subdivision_allowed) ...
        | max_leaf_depth > max_subdivision_allowed ...
        | ~ismember(subdivision_used,[0,1]) ...
        | ~isfinite(max_fem_allowed) ...
        | max_fem_allowed < 0 ...
        | max_fem_allowed ~= floor(max_fem_allowed) ...
        | ~isfinite(min_cr_allowed) | min_cr_allowed <= 0 ...
        | ~isfinite(min_lg_allowed) | min_lg_allowed <= 0 ...
        | ~isfinite(max_cr_used) | max_cr_used < 0 ...
        | max_cr_used > max_fem_allowed ...
        | max_cr_used ~= floor(max_cr_used) ...
        | ~isfinite(max_lg_used) | max_lg_used < -1 ...
        | max_lg_used > max_fem_allowed ...
        | max_lg_used ~= floor(max_lg_used) ...
        | ~isfinite(min_cr_used) | min_cr_used <= 0 ...
        | fem_refinement_used ...
            ~= (max_cr_used > 0 | max_lg_used > 0) ...
        | spectral_solve_count ...
            > 2*(max_fem_allowed+1).*evaluated_node_count) ...
        || any(methods == "LG" ...
            & (~isfinite(min_lg_used) | min_lg_used <= 0)) ...
        || any(double(table_value.LG_B_verified_spd) ~= 1)
    error('run_omega_mid_unified_full:BadFEMRefinementSummary', ...
        '%s contains inconsistent FEM refinement diagnostics.', ...
        filename);
end
if any(double(table_value.subdivision_used(subdivision)) ~= 1 ...
        | leaf_count(subdivision) <= 1 ...
        | max_leaf_depth(subdivision) < 1 ...
        | evaluated_node_count(subdivision) ...
            ~= (4*leaf_count(subdivision)-1)/3 ...
        | spectral_solve_count(subdivision) ...
            < evaluated_node_count(subdivision))
    error('run_omega_mid_unified_full:BadSubdivisionCertificate', ...
        '%s contains an inconsistent subdivision summary.',filename);
end
shift_method = strtrim(string(table_value.LG_shift_method));
valid_shift = ismember(shift_method, ...
    ["CR-Liu","not-applicable"]);
eigenvalue_seconds = double(table_value.eigenvalue_total_seconds);
cr_shift_seconds = double(table_value.LG_CR_shift_seconds);
fallback_used = double(table_value.LG_fallback_used);
fallback_reason = strtrim(string(table_value.LG_fallback_reason));
fallback_reason(ismissing(fallback_reason)) = "";
fallback_nodes = double(table_value.LG_fallback_node_count);
analytic_nodes = double(table_value.LG_analytic_shift_node_count);
cr_liu_nodes = double(table_value.LG_CR_Liu_shift_node_count);
direct_cr_nodes = double(table_value.direct_CR_node_count);
node_counts = [fallback_nodes,analytic_nodes, ...
    cr_liu_nodes,direct_cr_nodes];
if any(~valid_shift) ...
        || any(~isfinite(eigenvalue_seconds) ...
            | eigenvalue_seconds < 0) ...
        || any(~isfinite(cr_shift_seconds) | cr_shift_seconds < 0) ...
        || any(~isfinite(node_counts(:))) ...
        || any(node_counts(:) < 0) ...
        || any(node_counts(:) ~= floor(node_counts(:))) ...
        || any(fallback_nodes ~= 0) ...
        || any(analytic_nodes ~= 0) ...
        || any(cr_liu_nodes+direct_cr_nodes ...
            > evaluated_node_count) ...
        || any(fallback_used ~= 0) ...
        || any(strlength(fallback_reason) > 0) ...
        || any(methods == "CR" ...
            & shift_method ~= "not-applicable") ...
        || any(methods == "LG" ...
            & shift_method ~= "CR-Liu")
    error('run_omega_mid_unified_full:BadLGShiftDiagnostics', ...
        '%s contains inconsistent LG shift or timing diagnostics.', ...
        filename);
end
lg = methods == "LG";
rho = double(table_value.LG_rho_lower);
ritz = double(table_value.LG_ritz_upper);
separation = double(table_value.LG_separation_margin_lower);
mu_upper = double(table_value.LG_mu_upper);
if any(~isfinite(rho(lg)) | rho(lg) <= 0 ...
        | ~isfinite(ritz(lg)) | ritz(lg) <= 0 ...
        | rho(lg) <= ritz(lg) ...
        | ~isfinite(separation(lg)) | separation(lg) <= 0 ...
        | ~isfinite(mu_upper(lg)) | mu_upper(lg) >= 0)
    error('run_omega_mid_unified_full:BadPublicLGCertificate', ...
        '%s contains a row that fails strict LG conditions.',filename);
end
end


function publication = local_begin_publication( ...
    sources,targets,journal_path)
publication = struct();
publication.schema = ...
    'lowerboundsineq.omega_mid_publication_journal.v1';
publication.state = 'preparing';
publication.sources = sources;
publication.targets = targets;
publication.journal_path = journal_path;
publication.staged = cell(size(sources));
publication.backups = cell(size(targets));
publication.had_original = false(size(targets));

if exist(journal_path,'file')
    error('run_omega_mid_unified_full:UnrecoveredJournal', ...
        ['A prior publication journal still exists.  Recovery must ', ...
         'finish before another publication begins.']);
end
try
    for k = 1:numel(sources)
        directory = fileparts(targets{k});
        publication.staged{k} = [tempname(directory),'.csv'];
        [ok,message] = copyfile( ...
            sources{k},publication.staged{k},'f');
        if ~ok
            error('run_omega_mid_unified_full:StageFailed', ...
                'Could not stage %s: %s',targets{k},message);
        end
    end
    for k = 1:numel(targets)
        if exist(targets{k},'file')
            [~,~,extension] = fileparts(targets{k});
            publication.backups{k} = ...
                [tempname(fileparts(targets{k})),extension];
            [ok,message] = copyfile( ...
                targets{k},publication.backups{k},'f');
            if ~ok
                error('run_omega_mid_unified_full:BackupFailed', ...
                    'Could not back up %s: %s',targets{k},message);
            end
            publication.had_original(k) = true;
        end
    end
    publication.state = 'prepared';
    local_save_publication_journal(publication);
    for k = 1:numel(sources)
        [ok,message] = movefile( ...
            publication.staged{k},targets{k},'f');
        if ~ok
            error('run_omega_mid_unified_full:PublishFailed', ...
                'Could not publish %s: %s',targets{k},message);
        end
    end
catch ME
    local_rollback_publication(publication);
    rethrow(ME);
end
end


function local_recover_publication(journal_path,expected_targets)
if ~exist(journal_path,'file')
    return;
end
try
    payload = load(journal_path,'publication');
catch ME
    error('run_omega_mid_unified_full:UnreadableJournal', ...
        'Cannot read the interrupted publication journal: %s',ME.message);
end
if ~isfield(payload,'publication') ...
        || ~isstruct(payload.publication)
    error('run_omega_mid_unified_full:BadJournal', ...
        'The interrupted publication journal has no valid payload.');
end
publication = payload.publication;
if ~strcmp(local_publication_field( ...
            publication,'schema',''), ...
        'lowerboundsineq.omega_mid_publication_journal.v1') ...
        || ~strcmp(local_publication_field( ...
            publication,'journal_path',''),journal_path) ...
        || ~isequal(local_publication_field( ...
            publication,'targets',{}),expected_targets)
    error('run_omega_mid_unified_full:BadJournal', ...
        'The interrupted publication journal has unexpected targets.');
end
local_validate_journal_paths(publication,journal_path);
state = local_publication_field(publication,'state','');
if any(strcmp(state,{'committed','rolled_back'}))
    local_cleanup_files(local_publication_field( ...
        publication,'staged',{}));
    local_cleanup_files(local_publication_field( ...
        publication,'backups',{}));
    local_delete_if_present(journal_path);
    fprintf('Recovered cleanup from a committed Omega_mid publication.\n');
elseif strcmp(state,'prepared')
    local_rollback_publication(publication);
    fprintf('Rolled back an interrupted Omega_mid publication.\n');
else
    error('run_omega_mid_unified_full:BadJournalState', ...
        'The interrupted publication journal is not recoverable.');
end
end


function local_validate_journal_paths(publication,journal_path)
targets = local_publication_field(publication,'targets',{});
backups = local_publication_field(publication,'backups',{});
staged = local_publication_field(publication,'staged',{});
had_original = local_publication_field( ...
    publication,'had_original',[]);
if ~iscell(targets) || ~iscell(backups) || ~iscell(staged) ...
        || numel(backups) ~= numel(targets) ...
        || numel(had_original) ~= numel(targets) ...
        || ~all(ismember(double(had_original(:)),[0,1]))
    error('run_omega_mid_unified_full:BadJournal', ...
        'The interrupted publication journal has incoherent arrays.');
end
allowed_directory = fileparts(journal_path);
temporary_paths = [backups(:);staged(:)];
for k = 1:numel(temporary_paths)
    pathname = temporary_paths{k};
    if isempty(pathname)
        continue;
    end
    if ~ischar(pathname) ...
            || ~strcmp(fileparts(pathname),allowed_directory)
        error('run_omega_mid_unified_full:BadJournal', ...
            ['The interrupted publication journal references a ', ...
             'temporary path outside the public results directory.']);
    end
end
end


function local_save_publication_journal(publication)
journal_path = publication.journal_path;
directory = fileparts(journal_path);
temporary = [tempname(directory),'.mat'];
cleanup = onCleanup(@() local_delete_if_present(temporary));
save(temporary,'publication','-v7');
[ok,message] = movefile(temporary,journal_path,'f');
if ~ok
    error('run_omega_mid_unified_full:JournalWriteFailed', ...
        'Could not publish the rollback journal: %s',message);
end
clear cleanup
end


function local_regenerate_summary(project_root,summary_json)
python = getenv('PYTHON');
if isempty(python)
    python = 'python3';
end
script = fullfile(project_root,'scripts_run','compute_stats.py');
command = sprintf('"%s" "%s"',python,script);
[status,output] = system(command);
if ~isempty(output)
    fprintf('%s',output);
end
if status ~= 0
    error('run_omega_mid_unified_full:SummaryFailed', ...
        'compute_stats.py exited with status %d.',status);
end
summary = jsondecode(fileread(summary_json));
if ~isfield(summary,'overall') ...
        || ~logical(summary.overall.all_verified)
    error('run_omega_mid_unified_full:SummaryIncomplete', ...
        'The regenerated public summary is not fully verified.');
end
end


function local_validate_public_summary(summary_json,summary_markdown)
if ~exist(summary_json,'file') || ~exist(summary_markdown,'file')
    error('run_omega_mid_unified_full:MissingPublicSummary', ...
        'Both public summary artifacts must exist before publication.');
end
summary = jsondecode(fileread(summary_json));
if ~isfield(summary,'overall') ...
        || ~isfield(summary.overall,'all_verified') ...
        || ~logical(summary.overall.all_verified)
    error('run_omega_mid_unified_full:SummaryIncomplete', ...
        'The public JSON summary is not fully verified.');
end
info = dir(summary_markdown);
if isempty(info) || info.bytes < 1
    error('run_omega_mid_unified_full:SummaryIncomplete', ...
        'The public Markdown summary is empty.');
end
end


function local_commit_publication(publication)
publication.state = 'committed';
local_save_publication_journal(publication);
try
    local_cleanup_files(publication.staged);
    local_cleanup_files(publication.backups);
    local_delete_if_present(publication.journal_path);
catch ME
    % The committed journal deliberately remains recoverable on the next
    % invocation; publication itself has already passed every validator.
    warning('run_omega_mid_unified_full:CommitCleanupDeferred', ...
        'Committed publication cleanup was deferred: %s',ME.message);
end
end


function local_rollback_publication(publication)
failures = {};
for k = 1:numel(publication.targets)
    target = publication.targets{k};
    backup = publication.backups{k};
    if publication.had_original(k) && exist(backup,'file')
        % Copy rather than move so a crash during rollback remains
        % idempotently recoverable from the durable journal.
        [ok,message] = copyfile(backup,target,'f');
        if ~ok
            failures{end+1,1} = sprintf( ... %#ok<AGROW>
                'Could not restore %s: %s',target,message);
        end
    elseif ~publication.had_original(k)
        try
            local_delete_if_present(target);
        catch ME
            failures{end+1,1} = sprintf( ... %#ok<AGROW>
                'Could not remove %s: %s',target,ME.message);
        end
    else
        failures{end+1,1} = sprintf( ... %#ok<AGROW>
            'The backup needed to restore %s is missing.',target);
    end
end
if ~isempty(failures)
    error('run_omega_mid_unified_full:RollbackFailed', ...
        '%s',strjoin(failures,' '));
end
publication.state = 'rolled_back';
local_save_publication_journal(publication);
local_cleanup_files(publication.staged);
local_cleanup_files(publication.backups);
local_delete_if_present(publication.journal_path);
end


function local_publish_versioned_generation( ...
    project_root,certificate_manifest,targets)
publication_root = fullfile( ...
    project_root,'results','omega_mid_publications');
if ~exist(publication_root,'dir')
    mkdir(publication_root);
end
created = regexprep( ...
    certificate_manifest.created_utc,'[^0-9A-Za-z]+','');
generation_id = sprintf('%s_%s', ...
    created,certificate_manifest.fingerprint(1:16));
generation_dir = fullfile(publication_root,generation_id);
if exist(generation_dir,'dir')
    error('run_omega_mid_unified_full:GenerationExists', ...
        'The immutable publication generation already exists.');
end
temporary_dir = tempname(publication_root);
mkdir(temporary_dir);
cleanup = onCleanup(@() local_remove_dir_if_present(temporary_dir));

names = {'J1_OmegaMid.csv','J2_OmegaMid.csv', ...
    'verification_summary.json','verification_summary.md'};
copies = cell(size(names));
source_hashes = cell(size(names));
copy_hashes = cell(size(names));
for k = 1:numel(names)
    if ~exist(targets{k},'file')
        error('run_omega_mid_unified_full:MissingArtifact', ...
            'Cannot version missing public artifact %s.',targets{k});
    end
    copies{k} = fullfile(temporary_dir,names{k});
    [ok,message] = copyfile(targets{k},copies{k},'f');
    if ~ok
        error('run_omega_mid_unified_full:GenerationCopyFailed', ...
            'Could not stage immutable generation file: %s',message);
    end
    source_hashes{k} = ver10_file_sha256(targets{k});
    copy_hashes{k} = ver10_file_sha256(copies{k});
    if ~strcmp(source_hashes{k},copy_hashes{k})
        error('run_omega_mid_unified_full:GenerationHashMismatch', ...
            'A versioned publication copy has the wrong SHA-256 hash.');
    end
end
local_validate_public_pair(copies{1},copies{2}, ...
    fullfile(project_root,'inputs','cell_def.csv'));
local_validate_public_summary(copies{3},copies{4});

generation = struct();
generation.schema = ...
    'lowerboundsineq.omega_mid_publication_generation.v1';
generation.generation_id = generation_id;
generation.created_utc = certificate_manifest.created_utc;
generation.certificate_fingerprint = ...
    certificate_manifest.fingerprint;
generation.files = struct( ...
    'J1_OmegaMid_csv',names{1}, ...
    'J2_OmegaMid_csv',names{2}, ...
    'verification_summary_json',names{3}, ...
    'verification_summary_markdown',names{4});
generation.sha256 = struct( ...
    'J1_OmegaMid_csv',copy_hashes{1}, ...
    'J2_OmegaMid_csv',copy_hashes{2}, ...
    'verification_summary_json',copy_hashes{3}, ...
    'verification_summary_markdown',copy_hashes{4});
generation_manifest_name = 'publication_manifest.json';
generation_manifest_path = fullfile( ...
    temporary_dir,generation_manifest_name);
local_write_json_atomic(generation_manifest_path,generation);
generation_manifest_sha256 = ...
    ver10_file_sha256(generation_manifest_path);

[ok,message] = movefile(temporary_dir,generation_dir);
if ~ok
    error('run_omega_mid_unified_full:GenerationPublishFailed', ...
        'Could not publish the immutable generation: %s',message);
end
clear cleanup

pointer = struct();
pointer.schema = ...
    'lowerboundsineq.omega_mid_publication_pointer.v1';
pointer.generation_id = generation_id;
pointer.generation_directory = [ ...
    'omega_mid_publications/',generation_id];
pointer.publication_manifest = generation_manifest_name;
pointer.publication_manifest_sha256 = ...
    generation_manifest_sha256;
pointer.certificate_fingerprint = ...
    certificate_manifest.fingerprint;
local_write_json_atomic(fullfile( ...
    project_root,'results','omega_mid_current.json'),pointer);
fprintf('Published immutable Omega_mid generation %s.\n',generation_id);
end


function local_cleanup_files(filenames)
for k = 1:numel(filenames)
    if ~isempty(filenames{k})
        local_delete_if_present(filenames{k});
    end
end
end


function value = local_publication_field(record,name,default)
if isstruct(record) && isfield(record,name)
    value = record.(name);
else
    value = default;
end
end


function local_write_json_atomic(filename,value)
try
    encoded = jsonencode(value,'PrettyPrint',true);
catch
    encoded = jsonencode(value);
end
directory = fileparts(filename);
temporary = [tempname(directory),'.json'];
cleanup = onCleanup(@() local_delete_if_present(temporary));
fid = fopen(temporary,'w');
if fid < 0
    error('run_omega_mid_unified_full:JsonWriteFailed', ...
        'Could not open a temporary JSON publication file.');
end
file_cleanup = onCleanup(@() fclose(fid));
fprintf(fid,'%s\n',encoded);
clear file_cleanup
[ok,message] = movefile(temporary,filename,'f');
if ~ok
    error('run_omega_mid_unified_full:JsonPublishFailed', ...
        'Could not atomically publish %s: %s',filename,message);
end
clear cleanup
end


function local_delete_if_present(filename)
if exist(filename,'file')
    delete(filename);
end
end


function local_remove_dir_if_present(pathname)
if exist(pathname,'dir')
    rmdir(pathname,'s');
end
end
