%RUN_OMEGA_MID_UNIFIED_FULL  Production Omega_mid certificate for J1/J2.
%
% This is the ver10 liulabhpc wrapper.  It covers every row of
% inputs/cell_def.csv, uses one shared eigenvalue computation per cell for
% J1 and J2, and writes atomic resumable chunk checkpoints.  The driver
% refuses to start a complete interval run from a dirty Git checkout.

project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root,'scripts_run'));
results_root = fullfile(project_root,'results');
target_J1 = fullfile(results_root,'J1_OmegaMid.csv');
target_J2 = fullfile(results_root,'J2_OmegaMid.csv');
summary_json = fullfile(results_root,'verification_summary.json');
summary_markdown = fullfile(results_root,'verification_summary.md');
current_pointer = fullfile(results_root,'omega_mid_current.json');
public_targets = { ...
    target_J1,target_J2,summary_json,summary_markdown,current_pointer};
publication_journal = fullfile( ...
    results_root,'.omega_mid_publication_journal.mat');
local_recover_publication(publication_journal,public_targets);
local_release_destination();

manifest = run_omega_mid_unified_parallel( ...
    'mode','interval', ...
    'workers',20, ...
    'input_file',fullfile(project_root,'inputs','cell_def.csv'), ...
    'chunk_size',256, ...
    'checkpoint_every',32, ...
    'max_subdivision_depth',8, ...
    'max_fem_refinement_level',2, ...
    'minimum_cr_mesh_size',0.005, ...
    'minimum_lg_mesh_size',0.025, ...
    'run_name','ver10_omega_mid_unified_prod', ...
    'resume',true, ...
    'retry_failed',true);

local_validate_geometric_coverage( ...
    manifest,project_root,fullfile(project_root,'inputs','cell_def.csv'));
if ~manifest.complete_certificate
    error('run_omega_mid_unified_full:IncompleteCertificate', ...
        ['The unified production run did not produce a complete, clean, ', ...
         'strict interval certificate.  Public result files were not ', ...
         'modified.']);
end
source_artifacts = validate_omega_mid_unified_artifacts( ...
    manifest,project_root,'require_complete',true);

% Publish only after the manifest has certified both exact input IDs and
% rigorous geometric coverage of the actual Omega_mid region.
% The legacy public validator consumes these canonical paths and requires
% status=ok, finite J_lower>0, and verified=1 on every input cell id.
source_J1 = source_artifacts.paths.J1_csv;
source_J2 = source_artifacts.paths.J2_csv;
local_validate_public_pair(source_J1,source_J2, ...
    fullfile(project_root,'inputs','cell_def.csv'));

staged_generation = local_stage_versioned_generation( ...
    project_root,manifest,source_J1,source_J2);
try
    publication = local_begin_publication( ...
        {source_J1,source_J2, ...
         staged_generation.summary_json, ...
         staged_generation.summary_markdown, ...
         staged_generation.pointer_source}, ...
        public_targets,publication_journal,staged_generation);
catch ME
    local_abandon_staged_generation(staged_generation);
    rethrow(ME);
end
try
    validator = VerifyTriangleInequalities();
    validator.run();
    local_validate_public_pair(target_J1,target_J2, ...
        fullfile(project_root,'inputs','cell_def.csv'));
    local_validate_public_summary(summary_json,summary_markdown);
    if ~strcmp(ver10_file_sha256(current_pointer), ...
            staged_generation.pointer_sha256)
        error('run_omega_mid_unified_full:PointerCopyMismatch', ...
            'The staged current-generation pointer changed during copy.');
    end
    local_finalize_staged_generation(staged_generation);
    local_commit_publication(publication);
catch ME
    if strcmp(publication.state,'prepared')
        local_rollback_publication(publication);
    else
        local_cleanup_files(publication.staged);
        local_cleanup_files(publication.backups);
    end
    local_abandon_staged_generation(staged_generation);
    rethrow(ME);
end

fprintf('Omega_mid unified production run finished.\n');
fprintf('complete certificate: %d\n',manifest.complete_certificate);
fprintf('geometric coverage certificate: %d (%s)\n', ...
    manifest.summary.geometric_coverage_certified, ...
    manifest.geometric_coverage.hashes.proof_payload);
fprintf('strict records: %d/%d\n', ...
    manifest.summary.num_strict_records, ...
    manifest.summary.num_selected_cells);
fprintf('minimum J1 lower: %.17g\n', ...
    manifest.summary.minimum_J1_lower);
fprintf('minimum J2 lower: %.17g\n', ...
    manifest.summary.minimum_J2_lower);


function coverage_path = local_validate_geometric_coverage( ...
    manifest,project_root,input_file)
if ~isstruct(manifest) ...
        || ~isfield(manifest,'geometric_coverage') ...
        || ~isfield(manifest,'summary') ...
        || ~isfield(manifest.summary,'geometric_coverage_certified') ...
        || ~logical(manifest.summary.geometric_coverage_certified) ...
        || ~isfield(manifest,'files') ...
        || ~isfield(manifest.files,'geometric_coverage_json') ...
        || ~isfield(manifest,'hashes') ...
        || ~isfield(manifest.hashes,'geometric_coverage_json')
    error('run_omega_mid_unified_full:MissingGeometricCoverage', ...
        ['The unified manifest lacks a certified geometric Omega_mid ', ...
         'coverage artifact.  Exact cell IDs alone are insufficient.']);
end
coverage = manifest.geometric_coverage;
if ~isfield(coverage,'schema') ...
        || ~strcmp(coverage.schema, ...
            'lowerboundsineq.omega_mid_geometric_coverage.v1') ...
        || ~isfield(coverage,'complete') || ~logical(coverage.complete) ...
        || ~isfield(coverage,'rigorous') || ~logical(coverage.rigorous) ...
        || ~isfield(coverage,'status') ...
        || ~strcmp(coverage.status,'certified') ...
        || ~isfield(coverage,'input') ...
        || ~isfield(coverage.input,'sha256') ...
        || ~isfield(coverage,'proof') ...
        || ~isfield(coverage.proof,'decimal_topology_exact') ...
        || ~logical(coverage.proof.decimal_topology_exact) ...
        || ~isfield(coverage.proof,'binary_double_endpoint_roundtrip') ...
        || logical(coverage.proof.binary_double_endpoint_roundtrip) ...
        || ~isfield(coverage.proof,'arbitrary_tolerance_used') ...
        || logical(coverage.proof.arbitrary_tolerance_used) ...
        || ~isfield(coverage,'hashes') ...
        || ~isfield(coverage.hashes,'proof_payload') ...
        || numel(coverage.hashes.proof_payload) ~= 64
    error('run_omega_mid_unified_full:BadGeometricCoverage', ...
        'The geometric coverage payload is incomplete or non-rigorous.');
end
input_sha256 = ver10_file_sha256(input_file);
if ~strcmp(coverage.input.sha256,input_sha256) ...
        || ~isfield(manifest,'input') ...
        || ~isfield(manifest.input,'sha256') ...
        || ~strcmp(manifest.input.sha256,input_sha256)
    error('run_omega_mid_unified_full:CoverageInputMismatch', ...
        ['The geometric coverage certificate is not bound to the ', ...
         'published input CSV.']);
end
relative = char(manifest.files.geometric_coverage_json);
if isempty(relative) || local_is_absolute_path(relative) ...
        || ~isempty(regexp(strrep(relative,'\','/'), ...
            '(^|/)\.\.($|/)','once'))
    error('run_omega_mid_unified_full:BadCoveragePath', ...
        'The geometric coverage manifest path is not repository-relative.');
end
coverage_path = fullfile(project_root,relative);
if ~exist(coverage_path,'file') ...
        || ~strcmp(ver10_file_sha256(coverage_path), ...
            manifest.hashes.geometric_coverage_json)
    error('run_omega_mid_unified_full:CoverageHashMismatch', ...
        'The geometric coverage JSON is missing or has the wrong SHA-256.');
end
disk = jsondecode(fileread(coverage_path));
if ~isfield(disk,'schema') || ~strcmp(disk.schema,coverage.schema) ...
        || ~isfield(disk,'complete') || ~logical(disk.complete) ...
        || ~isfield(disk,'rigorous') || ~logical(disk.rigorous) ...
        || ~isfield(disk,'input') || ~isfield(disk.input,'sha256') ...
        || ~strcmp(disk.input.sha256,input_sha256) ...
        || ~isfield(disk,'hashes') ...
        || ~isfield(disk.hashes,'proof_payload') ...
        || ~strcmp(disk.hashes.proof_payload, ...
            coverage.hashes.proof_payload)
    error('run_omega_mid_unified_full:CoveragePayloadMismatch', ...
        ['The hashed geometric coverage JSON does not reproduce the ', ...
         'certificate embedded in the unified manifest.']);
end
end


function tf = local_is_absolute_path(pathname)
pathname = char(pathname);
tf = startsWith(pathname,filesep) ...
    || ~isempty(regexp(pathname,'^[A-Za-z]:[\\/]','once'));
end


function local_validate_public_pair(source_J1,source_J2,input_file)
expected_table = readtable(input_file);
expected_ids = sort(double(expected_table.i(:)));
J1 = local_validate_public_csv(source_J1,'J1',expected_ids);
J2 = local_validate_public_csv(source_J2,'J2',expected_ids);
[~,order1] = sort(double(J1.cell_id));
[~,order2] = sort(double(J2.cell_id));
common_fields = {'method','LG_escalation_policy', ...
    'fem_refinement_scheme','fem_refinement_used', ...
    'max_fem_refinement_level_allowed', ...
    'minimum_cr_mesh_size_allowed','minimum_lg_mesh_size_allowed', ...
    'max_cr_refinement_level_used','max_lg_refinement_level_used', ...
    'minimum_cr_mesh_size_used','minimum_lg_mesh_size_used', ...
    'lambda1_lower','LG_rho_lower', ...
    'LG_ritz_upper','LG_separation_margin_lower','LG_mu_upper', ...
    'LG_B_verified_spd', ...
    'shared_eigenvalue_computation','strict_checks_passed', ...
    'subdivision_used','leaf_count','max_leaf_depth', ...
    'max_subdivision_depth_allowed','evaluated_node_count', ...
    'spectral_solve_count','LG_shift_method', ...
    'LG_fallback_used','LG_fallback_reason', ...
    'eigenvalue_total_seconds','LG_CR_shift_seconds', ...
    'LG_fallback_node_count','LG_analytic_shift_node_count', ...
    'LG_CR_Liu_shift_node_count','direct_CR_node_count'};
for k = 1:numel(common_fields)
    name = common_fields{k};
    left = J1.(name)(order1,:);
    right = J2.(name)(order2,:);
    if ~isequaln(left,right)
        error('run_omega_mid_unified_full:UnsharedSpectralRows', ...
            'J1/J2 differ in the shared spectral column %s.',name);
    end
end
end


function table_value = local_validate_public_csv( ...
    filename,conjecture,expected_ids)
if ~exist(filename,'file')
    error('run_omega_mid_unified_full:MissingArtifact', ...
        'Cannot publish missing artifact: %s',filename);
end
table_value = readtable(filename,'TextType','string');
required = {'conjecture','cell_id','verified','J_lower','status', ...
    'note','run_timestamp','certificate_status','rigorous', ...
    'method','LG_escalation_policy','fem_refinement_scheme', ...
    'fem_refinement_used','max_fem_refinement_level_allowed', ...
    'minimum_cr_mesh_size_allowed','minimum_lg_mesh_size_allowed', ...
    'max_cr_refinement_level_used','max_lg_refinement_level_used', ...
    'minimum_cr_mesh_size_used','minimum_lg_mesh_size_used', ...
    'lambda1_lower','LG_rho_lower', ...
    'LG_ritz_upper','LG_separation_margin_lower','LG_mu_upper', ...
    'LG_B_verified_spd', ...
    'subdivision_used','leaf_count','max_leaf_depth', ...
    'max_subdivision_depth_allowed','evaluated_node_count', ...
    'spectral_solve_count', ...
    'LG_shift_method','LG_fallback_used','LG_fallback_reason', ...
    'eigenvalue_total_seconds','LG_CR_shift_seconds', ...
    'LG_fallback_node_count','LG_analytic_shift_node_count', ...
    'LG_CR_Liu_shift_node_count','direct_CR_node_count', ...
    'shared_eigenvalue_computation','strict_checks_passed'};
if ~all(ismember(required,table_value.Properties.VariableNames))
    error('run_omega_mid_unified_full:BadPublicSchema', ...
        '%s lacks a required public or provenance column.',filename);
end
ids = double(table_value.cell_id(:));
if height(table_value) ~= numel(expected_ids) ...
        || numel(unique(ids)) ~= numel(ids) ...
        || ~isequal(sort(ids),expected_ids)
    error('run_omega_mid_unified_full:BadPublicCoverage', ...
        '%s does not cover the exact input cell-id set.',filename);
end
if ~all(strcmpi(strtrim(string(table_value.conjecture)),conjecture)) ...
        || ~all(double(table_value.verified) == 1) ...
        || ~all(isfinite(double(table_value.J_lower)) ...
            & double(table_value.J_lower) > 0) ...
        || ~all(strcmpi(strtrim(string(table_value.status)),'ok')) ...
        || ~all(strcmp( ...
            strtrim(string(table_value.certificate_status)), ...
            'certified_interval')) ...
        || ~all(double(table_value.rigorous) == 1) ...
        || ~all(isfinite(double(table_value.lambda1_lower)) ...
            & double(table_value.lambda1_lower) > 0) ...
        || ~all(double(table_value.shared_eigenvalue_computation) == 1) ...
        || ~all(double(table_value.strict_checks_passed) == 1)
    error('run_omega_mid_unified_full:BadPublicCertificate', ...
        '%s contains a non-strict or nonfinite certificate row.',filename);
end
methods = strtrim(string(table_value.method));
if ~all(ismember(methods,["CR","LG","SUBDIVISION"]))
    error('run_omega_mid_unified_full:BadPublicMethod', ...
        '%s contains an unknown eigenvalue method.',filename);
end
if ~all(strcmp(strtrim(string(table_value.LG_escalation_policy)), ...
        'LG-input-or-terminal-depth-after-CR-refinement-v1'))
    error('run_omega_mid_unified_full:BadLGEscalationPolicy', ...
        '%s does not use the production LG escalation policy.',filename);
end
if ~all(strcmp(strtrim(string(table_value.fem_refinement_scheme)), ...
        'dyadic-CR-then-terminal-LG-v1'))
    error('run_omega_mid_unified_full:BadFEMRefinementPolicy', ...
        '%s does not use the production FEM refinement scheme.', ...
        filename);
end
subdivision = methods == "SUBDIVISION";
leaf_count = double(table_value.leaf_count);
max_leaf_depth = double(table_value.max_leaf_depth);
evaluated_node_count = double(table_value.evaluated_node_count);
spectral_solve_count = double(table_value.spectral_solve_count);
max_fem_allowed = double( ...
    table_value.max_fem_refinement_level_allowed);
min_cr_allowed = double(table_value.minimum_cr_mesh_size_allowed);
min_lg_allowed = double(table_value.minimum_lg_mesh_size_allowed);
max_cr_used = double(table_value.max_cr_refinement_level_used);
max_lg_used = double(table_value.max_lg_refinement_level_used);
min_cr_used = double(table_value.minimum_cr_mesh_size_used);
min_lg_used = double(table_value.minimum_lg_mesh_size_used);
fem_refinement_used = double(table_value.fem_refinement_used);
subdivision_used = double(table_value.subdivision_used);
max_subdivision_allowed = double( ...
    table_value.max_subdivision_depth_allowed);
if any(~isfinite(evaluated_node_count) ...
        | evaluated_node_count < 1 ...
        | evaluated_node_count ~= floor(evaluated_node_count) ...
        | ~isfinite(spectral_solve_count) ...
        | spectral_solve_count < evaluated_node_count ...
        | spectral_solve_count ~= floor(spectral_solve_count) ...
        | ~isfinite(leaf_count) | leaf_count < 1 ...
        | leaf_count ~= floor(leaf_count) ...
        | ~isfinite(max_leaf_depth) | max_leaf_depth < 0 ...
        | max_leaf_depth ~= floor(max_leaf_depth) ...
        | ~isfinite(max_subdivision_allowed) ...
        | max_subdivision_allowed < 0 ...
        | max_subdivision_allowed ~= floor(max_subdivision_allowed) ...
        | max_leaf_depth > max_subdivision_allowed ...
        | ~ismember(subdivision_used,[0,1]) ...
        | ~isfinite(max_fem_allowed) ...
        | max_fem_allowed < 0 ...
        | max_fem_allowed ~= floor(max_fem_allowed) ...
        | ~isfinite(min_cr_allowed) | min_cr_allowed <= 0 ...
        | ~isfinite(min_lg_allowed) | min_lg_allowed <= 0 ...
        | ~isfinite(max_cr_used) | max_cr_used < 0 ...
        | max_cr_used > max_fem_allowed ...
        | max_cr_used ~= floor(max_cr_used) ...
        | ~isfinite(max_lg_used) | max_lg_used < -1 ...
        | max_lg_used > max_fem_allowed ...
        | max_lg_used ~= floor(max_lg_used) ...
        | ~isfinite(min_cr_used) | min_cr_used <= 0 ...
        | fem_refinement_used ...
            ~= (max_cr_used > 0 | max_lg_used > 0) ...
        | spectral_solve_count ...
            > 2*(max_fem_allowed+1).*evaluated_node_count) ...
        || any(double(table_value.LG_CR_Liu_shift_node_count) > 0 ...
            & (~isfinite(min_lg_used) | min_lg_used <= 0)) ...
        || any(double(table_value.LG_B_verified_spd) ~= 1)
    error('run_omega_mid_unified_full:BadFEMRefinementSummary', ...
        '%s contains inconsistent FEM refinement diagnostics.', ...
        filename);
end
if any(double(table_value.subdivision_used(subdivision)) ~= 1 ...
        | leaf_count(subdivision) <= 1 ...
        | max_leaf_depth(subdivision) < 1 ...
        | evaluated_node_count(subdivision) ...
            ~= (4*leaf_count(subdivision)-1)/3 ...
        | spectral_solve_count(subdivision) ...
            < evaluated_node_count(subdivision))
    error('run_omega_mid_unified_full:BadSubdivisionCertificate', ...
        '%s contains an inconsistent subdivision summary.',filename);
end
shift_method = strtrim(string(table_value.LG_shift_method));
valid_shift = ismember(shift_method, ...
    ["CR-Liu","not-applicable"]);
eigenvalue_seconds = double(table_value.eigenvalue_total_seconds);
cr_shift_seconds = double(table_value.LG_CR_shift_seconds);
fallback_used = double(table_value.LG_fallback_used);
fallback_reason = strtrim(string(table_value.LG_fallback_reason));
fallback_reason(ismissing(fallback_reason)) = "";
fallback_nodes = double(table_value.LG_fallback_node_count);
analytic_nodes = double(table_value.LG_analytic_shift_node_count);
cr_liu_nodes = double(table_value.LG_CR_Liu_shift_node_count);
direct_cr_nodes = double(table_value.direct_CR_node_count);
uses_lg = cr_liu_nodes > 0;
node_counts = [fallback_nodes,analytic_nodes, ...
    cr_liu_nodes,direct_cr_nodes];
if any(~valid_shift) ...
        || any(~isfinite(eigenvalue_seconds) ...
            | eigenvalue_seconds < 0) ...
        || any(~isfinite(cr_shift_seconds) | cr_shift_seconds < 0) ...
        || any(~isfinite(node_counts(:))) ...
        || any(node_counts(:) < 0) ...
        || any(node_counts(:) ~= floor(node_counts(:))) ...
        || any(fallback_nodes ~= 0) ...
        || any(analytic_nodes ~= 0) ...
        || any(cr_liu_nodes+direct_cr_nodes ...
            ~= evaluated_node_count) ...
        || any(fallback_used ~= 0) ...
        || any(strlength(fallback_reason) > 0) ...
        || any(methods == "CR" ...
            & (shift_method ~= "not-applicable" | uses_lg)) ...
        || any(methods == "LG" ...
            & (shift_method ~= "CR-Liu" | ~uses_lg)) ...
        || any(uses_lg & shift_method ~= "CR-Liu") ...
        || any(~uses_lg & shift_method ~= "not-applicable") ...
        || any(uses_lg & (max_lg_used < 0 ...
            | ~isfinite(min_lg_used) | min_lg_used <= 0)) ...
        || any(~uses_lg & (max_lg_used ~= -1 ...
            | ~isnan(min_lg_used)))
    error('run_omega_mid_unified_full:BadLGShiftDiagnostics', ...
        '%s contains inconsistent LG shift or timing diagnostics.', ...
        filename);
end
lg = uses_lg;
direct_lg = methods == "LG";
rho = double(table_value.LG_rho_lower);
ritz = double(table_value.LG_ritz_upper);
separation = double(table_value.LG_separation_margin_lower);
mu_upper = double(table_value.LG_mu_upper);
% For SUBDIVISION rows these are extrema across distinct LG leaves.  The
% positive aggregate separation margin certifies every leaf; min(rho) need
% not exceed max(Ritz) when those extrema occur on different leaves.
if any(~isfinite(rho(lg)) | rho(lg) <= 0 ...
        | ~isfinite(ritz(lg)) | ritz(lg) <= 0 ...
        | ~isfinite(separation(lg)) | separation(lg) <= 0 ...
        | ~isfinite(mu_upper(lg)) | mu_upper(lg) >= 0) ...
        || any(rho(direct_lg) <= ritz(direct_lg))
    error('run_omega_mid_unified_full:BadPublicLGCertificate', ...
        '%s contains a row that fails strict LG conditions.',filename);
end
end


function publication = local_begin_publication( ...
    sources,targets,journal_path,staged_generation)
publication = struct();
publication.schema = ...
    'lowerboundsineq.omega_mid_publication_journal.v2';
publication.state = 'preparing';
publication.sources = sources;
publication.targets = targets;
publication.journal_path = journal_path;
publication.staged = cell(size(sources));
publication.backups = cell(size(targets));
publication.had_original = false(size(targets));
publication.generation = local_journal_generation(staged_generation);

if exist(journal_path,'file')
    error('run_omega_mid_unified_full:UnrecoveredJournal', ...
        ['A prior publication journal still exists.  Recovery must ', ...
         'finish before another publication begins.']);
end
try
    for k = 1:numel(sources)
        directory = fileparts(targets{k});
        publication.staged{k} = [tempname(directory),'.csv'];
        [ok,message] = copyfile( ...
            sources{k},publication.staged{k},'f');
        if ~ok
            error('run_omega_mid_unified_full:StageFailed', ...
                'Could not stage %s: %s',targets{k},message);
        end
    end
    for k = 1:numel(targets)
        if exist(targets{k},'file')
            [~,~,extension] = fileparts(targets{k});
            publication.backups{k} = ...
                [tempname(fileparts(targets{k})),extension];
            [ok,message] = copyfile( ...
                targets{k},publication.backups{k},'f');
            if ~ok
                error('run_omega_mid_unified_full:BackupFailed', ...
                    'Could not back up %s: %s',targets{k},message);
            end
            publication.had_original(k) = true;
        end
    end
    publication.state = 'prepared';
    local_save_publication_journal(publication);
    for k = 1:numel(sources)
        [ok,message] = movefile( ...
            publication.staged{k},targets{k},'f');
        if ~ok
            error('run_omega_mid_unified_full:PublishFailed', ...
                'Could not publish %s: %s',targets{k},message);
        end
    end
catch ME
    if strcmp(publication.state,'prepared')
        local_rollback_publication(publication);
    else
        % No canonical target is touched until the durable prepared journal
        % exists.  During preparation, clean only temporary copies.
        local_cleanup_publication_generation(publication);
        local_cleanup_files(publication.staged);
        local_cleanup_files(publication.backups);
    end
    rethrow(ME);
end
end


function local_recover_publication(journal_path,expected_targets)
if ~exist(journal_path,'file')
    return;
end
try
    payload = load(journal_path,'publication');
catch ME
    error('run_omega_mid_unified_full:UnreadableJournal', ...
        'Cannot read the interrupted publication journal: %s',ME.message);
end
if ~isfield(payload,'publication') ...
        || ~isstruct(payload.publication)
    error('run_omega_mid_unified_full:BadJournal', ...
        'The interrupted publication journal has no valid payload.');
end
publication = payload.publication;
if ~strcmp(local_publication_field( ...
            publication,'schema',''), ...
        'lowerboundsineq.omega_mid_publication_journal.v2') ...
        || ~strcmp(local_publication_field( ...
            publication,'journal_path',''),journal_path) ...
        || ~isequal(local_publication_field( ...
            publication,'targets',{}),expected_targets)
    error('run_omega_mid_unified_full:BadJournal', ...
        'The interrupted publication journal has unexpected targets.');
end
local_validate_journal_paths(publication,journal_path);
if ~isfield(publication,'generation') ...
        || ~isstruct(publication.generation)
    error('run_omega_mid_unified_full:BadJournal', ...
        'The interrupted journal lacks staged-generation recovery data.');
end
local_validate_journal_generation(publication.generation,journal_path);
state = local_publication_field(publication,'state','');
if strcmp(state,'committed')
    local_assert_committed_generation(publication);
    local_cleanup_files(local_publication_field( ...
        publication,'staged',{}));
    local_cleanup_files(local_publication_field( ...
        publication,'backups',{}));
    local_delete_if_present(journal_path);
    fprintf('Recovered cleanup from a committed Omega_mid publication.\n');
elseif strcmp(state,'rolled_back')
    local_cleanup_publication_generation(publication);
    local_cleanup_files(local_publication_field( ...
        publication,'staged',{}));
    local_cleanup_files(local_publication_field( ...
        publication,'backups',{}));
    local_delete_if_present(journal_path);
    fprintf('Recovered cleanup from a rolled-back Omega_mid publication.\n');
elseif strcmp(state,'prepared')
    local_rollback_publication(publication);
    fprintf('Rolled back an interrupted Omega_mid publication.\n');
else
    error('run_omega_mid_unified_full:BadJournalState', ...
        'The interrupted publication journal is not recoverable.');
end
end


function generation = local_journal_generation(staged)
local_validate_staged_paths(staged);
generation = struct( ...
    'schema','lowerboundsineq.omega_mid_journal_generation.v1', ...
    'publication_root',staged.publication_root, ...
    'temporary_dir',staged.temporary_dir, ...
    'generation_dir',staged.generation_dir, ...
    'manifest_name',staged.generation_manifest_name, ...
    'manifest_sha256',staged.generation_manifest_sha256, ...
    'staging_pointer_name','.omega_mid_current.json', ...
    'staging_pointer_sha256',staged.pointer_sha256);
end


function local_validate_journal_generation(generation,journal_path)
expected_root = fullfile( ...
    fileparts(journal_path),'omega_mid_publications');
if ~isstruct(generation) ...
        || ~isfield(generation,'schema') ...
        || ~strcmp(generation.schema, ...
            'lowerboundsineq.omega_mid_journal_generation.v1') ...
        || ~isfield(generation,'publication_root') ...
        || ~strcmp(generation.publication_root,expected_root) ...
        || ~isfield(generation,'temporary_dir') ...
        || ~strcmp(fileparts(generation.temporary_dir),expected_root) ...
        || ~isfield(generation,'generation_dir') ...
        || ~strcmp(fileparts(generation.generation_dir),expected_root) ...
        || strcmp(generation.temporary_dir,generation.generation_dir) ...
        || ~isfield(generation,'manifest_name') ...
        || ~strcmp(generation.manifest_name,'publication_manifest.json') ...
        || ~isfield(generation,'manifest_sha256') ...
        || isempty(regexp(generation.manifest_sha256, ...
            '^[0-9a-f]{64}$','once')) ...
        || ~isfield(generation,'staging_pointer_name') ...
        || ~strcmp(generation.staging_pointer_name, ...
            '.omega_mid_current.json') ...
        || ~isfield(generation,'staging_pointer_sha256') ...
        || isempty(regexp(generation.staging_pointer_sha256, ...
            '^[0-9a-f]{64}$','once'))
    error('run_omega_mid_unified_full:BadJournal', ...
        'The interrupted journal has unsafe generation recovery data.');
end
end


function local_validate_journal_paths(publication,journal_path)
targets = local_publication_field(publication,'targets',{});
backups = local_publication_field(publication,'backups',{});
staged = local_publication_field(publication,'staged',{});
had_original = local_publication_field( ...
    publication,'had_original',[]);
if ~iscell(targets) || ~iscell(backups) || ~iscell(staged) ...
        || numel(backups) ~= numel(targets) ...
        || numel(had_original) ~= numel(targets) ...
        || ~all(ismember(double(had_original(:)),[0,1]))
    error('run_omega_mid_unified_full:BadJournal', ...
        'The interrupted publication journal has incoherent arrays.');
end
allowed_directory = fileparts(journal_path);
temporary_paths = [backups(:);staged(:)];
for k = 1:numel(temporary_paths)
    pathname = temporary_paths{k};
    if isempty(pathname)
        continue;
    end
    if ~ischar(pathname) ...
            || ~strcmp(fileparts(pathname),allowed_directory)
        error('run_omega_mid_unified_full:BadJournal', ...
            ['The interrupted publication journal references a ', ...
             'temporary path outside the public results directory.']);
    end
end
end


function local_save_publication_journal(publication)
journal_path = publication.journal_path;
directory = fileparts(journal_path);
temporary = [tempname(directory),'.mat'];
cleanup = onCleanup(@() local_delete_if_present(temporary));
save(temporary,'publication','-v7');
[ok,message] = movefile(temporary,journal_path,'f');
if ~ok
    error('run_omega_mid_unified_full:JournalWriteFailed', ...
        'Could not publish the rollback journal: %s',message);
end
clear cleanup
end


function local_regenerate_summary( ...
    project_root,J1_file,J2_file,input_file, ...
    summary_json,summary_markdown)
python = getenv('PYTHON');
if isempty(python)
    python = 'python3';
end
script = fullfile(project_root,'scripts_run','compute_stats.py');
command = sprintf([ ...
    '%s %s --j1 %s --j2 %s --input %s ', ...
    '--summary-json %s --summary-markdown %s'], ...
    local_shell_quote(python),local_shell_quote(script), ...
    local_shell_quote(J1_file),local_shell_quote(J2_file), ...
    local_shell_quote(input_file),local_shell_quote(summary_json), ...
    local_shell_quote(summary_markdown));
[status,output] = system(command);
if ~isempty(output)
    fprintf('%s',output);
end
if status ~= 0
    error('run_omega_mid_unified_full:SummaryFailed', ...
        'compute_stats.py exited with status %d.',status);
end
summary = jsondecode(fileread(summary_json));
if ~isfield(summary,'overall') ...
        || ~logical(summary.overall.all_verified)
    error('run_omega_mid_unified_full:SummaryIncomplete', ...
        'The regenerated public summary is not fully verified.');
end
local_validate_public_summary(summary_json,summary_markdown);
end


function local_validate_public_summary(summary_json,summary_markdown)
if ~exist(summary_json,'file') || ~exist(summary_markdown,'file')
    error('run_omega_mid_unified_full:MissingPublicSummary', ...
        'Both public summary artifacts must exist before publication.');
end
summary = jsondecode(fileread(summary_json));
if ~isfield(summary,'overall') ...
        || ~isfield(summary.overall,'all_verified') ...
        || ~logical(summary.overall.all_verified)
    error('run_omega_mid_unified_full:SummaryIncomplete', ...
        'The public JSON summary is not fully verified.');
end
info = dir(summary_markdown);
if isempty(info) || info.bytes < 1
    error('run_omega_mid_unified_full:SummaryIncomplete', ...
        'The public Markdown summary is empty.');
end
end


function local_commit_publication(publication)
publication.state = 'committed';
local_save_publication_journal(publication);
try
    local_cleanup_files(publication.staged);
    local_cleanup_files(publication.backups);
    local_delete_if_present(publication.journal_path);
catch ME
    % The committed journal deliberately remains recoverable on the next
    % invocation; publication itself has already passed every validator.
    warning('run_omega_mid_unified_full:CommitCleanupDeferred', ...
        'Committed publication cleanup was deferred: %s',ME.message);
end
end


function local_rollback_publication(publication)
% Remove a staged or already-renamed generation before restoring canonical
% files.  The journal remains in state=prepared until both operations finish,
% so a hard kill at any point is idempotently recoverable on the next run.
local_cleanup_publication_generation(publication);
failures = {};
for k = 1:numel(publication.targets)
    target = publication.targets{k};
    backup = publication.backups{k};
    if publication.had_original(k) && exist(backup,'file')
        % Copy rather than move so a crash during rollback remains
        % idempotently recoverable from the durable journal.
        [ok,message] = copyfile(backup,target,'f');
        if ~ok
            failures{end+1,1} = sprintf( ... %#ok<AGROW>
                'Could not restore %s: %s',target,message);
        end
    elseif ~publication.had_original(k)
        try
            local_delete_if_present(target);
        catch ME
            failures{end+1,1} = sprintf( ... %#ok<AGROW>
                'Could not remove %s: %s',target,ME.message);
        end
    else
        failures{end+1,1} = sprintf( ... %#ok<AGROW>
            'The backup needed to restore %s is missing.',target);
    end
end
if ~isempty(failures)
    error('run_omega_mid_unified_full:RollbackFailed', ...
        '%s',strjoin(failures,' '));
end
publication.state = 'rolled_back';
local_save_publication_journal(publication);
local_cleanup_files(publication.staged);
local_cleanup_files(publication.backups);
local_delete_if_present(publication.journal_path);
end


function staged = local_stage_versioned_generation( ...
    project_root,certificate_manifest,source_J1,source_J2)
publication_root = fullfile( ...
    project_root,'results','omega_mid_publications');
if ~exist(publication_root,'dir')
    mkdir(publication_root);
end
created = regexprep( ...
    certificate_manifest.created_utc,'[^0-9A-Za-z]+','');
generation_id = sprintf('%s_%s', ...
    created,certificate_manifest.fingerprint(1:16));
generation_dir = fullfile(publication_root,generation_id);
if exist(generation_dir,'dir')
    error('run_omega_mid_unified_full:GenerationExists', ...
        'The immutable publication generation already exists.');
end
temporary_dir = tempname(publication_root);
mkdir(temporary_dir);
cleanup = onCleanup(@() local_remove_dir_if_present(temporary_dir));

input_file = fullfile(project_root,'inputs','cell_def.csv');
coverage_source = local_validate_geometric_coverage( ...
    certificate_manifest,project_root,input_file);
source_artifacts = validate_omega_mid_unified_artifacts( ...
    certificate_manifest,project_root,'require_complete',true, ...
    'validate_record_structure',false);
if ~strcmp(coverage_source, ...
        source_artifacts.paths.geometric_coverage_json)
    error('run_omega_mid_unified_full:CoveragePathMismatch', ...
        'Independent coverage validators resolved different artifacts.');
end
unified_source = source_artifacts.paths.json;
mat_source = source_artifacts.paths.mat;
config_source = source_artifacts.paths.config_mat;

release = local_release_destination();
mat_asset_name = sprintf( ...
    'omega_mid_unified_results_%s.mat',generation_id);
mat_asset_url = sprintf( ...
    'https://github.com/%s/releases/download/%s/%s', ...
    release.repository,release.tag,mat_asset_name);

names = struct( ...
    'J1_gzip','J1_OmegaMid.csv.gz', ...
    'J2_gzip','J2_OmegaMid.csv.gz', ...
    'summary_json','verification_summary.json', ...
    'summary_markdown','verification_summary.md', ...
    'coverage','omega_mid_geometric_coverage_manifest.json', ...
    'unified','omega_mid_unified_manifest.json', ...
    'results_mat',mat_asset_name, ...
    'config_mat','config.mat');
paths = struct();
name_fields = fieldnames(names);
for k = 1:numel(name_fields)
    name = name_fields{k};
    paths.(name) = fullfile(temporary_dir,names.(name));
end

local_regenerate_summary(project_root,source_J1,source_J2, ...
    input_file,paths.summary_json,paths.summary_markdown);
local_validate_public_pair(source_J1,source_J2,input_file);
J1_gzip = ver10_deterministic_gzip(source_J1,paths.J1_gzip);
J2_gzip = ver10_deterministic_gzip(source_J2,paths.J2_gzip);
if ~strcmp(J1_gzip.expanded_content_sha256, ...
        certificate_manifest.hashes.J1_csv) ...
        || ~strcmp(J2_gzip.expanded_content_sha256, ...
            certificate_manifest.hashes.J2_csv)
    error('run_omega_mid_unified_full:GzipContentMismatch', ...
        'A compressed public CSV does not expand to the manifest content.');
end

local_copy_bound(coverage_source,paths.coverage, ...
    certificate_manifest.hashes.geometric_coverage_json,'coverage');
local_copy_unified(unified_source,paths.unified);
local_copy_bound(mat_source,paths.results_mat, ...
    certificate_manifest.hashes.mat,'results MAT');
local_copy_bound(config_source,paths.config_mat, ...
    certificate_manifest.hashes.config_mat,'config MAT');
validate_omega_mid_unified_artifacts( ...
    certificate_manifest,project_root, ...
    'require_complete',true, ...
    'validate_record_structure',false, ...
    'J1_file',source_J1,'J2_file',source_J2, ...
    'coverage_file',paths.coverage, ...
    'unified_manifest_file',paths.unified, ...
    'mat_file',paths.results_mat,'config_file',paths.config_mat);

generation = struct();
generation.schema = ...
    'lowerboundsineq.omega_mid_publication_generation.v2';
generation.generation_id = generation_id;
generation.created_utc = certificate_manifest.created_utc;
generation.certificate_fingerprint = ...
    certificate_manifest.fingerprint;
generation.files = struct( ...
    'J1_OmegaMid_csv_gz',names.J1_gzip, ...
    'J2_OmegaMid_csv_gz',names.J2_gzip, ...
    'verification_summary_json',names.summary_json, ...
    'verification_summary_markdown',names.summary_markdown, ...
    'omega_mid_geometric_coverage_manifest',names.coverage, ...
    'omega_mid_unified_manifest',names.unified, ...
    'omega_mid_unified_results_mat',names.results_mat, ...
    'config_mat',names.config_mat);
generation.sha256 = struct( ...
    'J1_OmegaMid_csv_gz',J1_gzip.file_sha256, ...
    'J1_OmegaMid_csv_expanded_content', ...
        J1_gzip.expanded_content_sha256, ...
    'J2_OmegaMid_csv_gz',J2_gzip.file_sha256, ...
    'J2_OmegaMid_csv_expanded_content', ...
        J2_gzip.expanded_content_sha256, ...
    'verification_summary_json', ...
        ver10_file_sha256(paths.summary_json), ...
    'verification_summary_markdown', ...
        ver10_file_sha256(paths.summary_markdown), ...
    'omega_mid_geometric_coverage_manifest', ...
        ver10_file_sha256(paths.coverage), ...
    'omega_mid_unified_manifest', ...
        ver10_file_sha256(paths.unified), ...
    'omega_mid_unified_results_mat', ...
        ver10_file_sha256(paths.results_mat), ...
    'config_mat',ver10_file_sha256(paths.config_mat));
generation.compression = struct( ...
    'algorithm','gzip', ...
    'options','-n -9', ...
    'roundtrip_verified',true, ...
    'independent_encodings_identical',true);
generation.geometric_coverage_proof_payload_sha256 = ...
    certificate_manifest.geometric_coverage.hashes.proof_payload;
generation.artifact_resolution = struct( ...
    'rule','resolve files and SHA-256 through this publication manifest', ...
    'copied_unified_manifest_paths', ...
        ['source-run provenance only; immutable sibling files listed ', ...
         'here are authoritative'], ...
    'results_mat_release_asset',struct( ...
        'owner',release.owner, ...
        'repo',release.repo, ...
        'repository',release.repository, ...
        'tag',release.tag, ...
        'name',mat_asset_name, ...
        'url',mat_asset_url, ...
        'sha256',certificate_manifest.hashes.mat, ...
        'availability_at_generation_time','not-required', ...
        'post_upload_check','download asset and verify SHA-256'));
generation.leaf_attempt_evidence = struct( ...
    'file',names.results_mat, ...
    'sha256',certificate_manifest.hashes.mat, ...
    'matlab_variable','records(:).leaves(:).attempts', ...
    'config_file',names.config_mat, ...
    'config_sha256',certificate_manifest.hashes.config_mat);
generation_manifest_name = 'publication_manifest.json';
generation_manifest_path = fullfile( ...
    temporary_dir,generation_manifest_name);
local_write_json_atomic(generation_manifest_path,generation);
generation_manifest_sha256 = ...
    ver10_file_sha256(generation_manifest_path);
decoded_generation = validate_omega_mid_publication_generation( ...
    temporary_dir,generation_manifest_sha256);
if ~strcmp(jsonencode(decoded_generation),jsonencode(generation))
    error('run_omega_mid_unified_full:GenerationManifestMismatch', ...
        'The staged publication manifest did not round-trip exactly.');
end

pointer = struct();
pointer.schema = ...
    'lowerboundsineq.omega_mid_publication_pointer.v1';
pointer.generation_id = generation_id;
pointer.generation_directory = [ ...
    'omega_mid_publications/',generation_id];
pointer.publication_manifest = generation_manifest_name;
pointer.publication_manifest_sha256 = ...
    generation_manifest_sha256;
pointer.certificate_fingerprint = ...
    certificate_manifest.fingerprint;
pointer.results_mat_release_asset = ...
    generation.artifact_resolution.results_mat_release_asset;
pointer_source = fullfile(temporary_dir,'.omega_mid_current.json');
local_write_json_atomic(pointer_source,pointer);

staged = struct( ...
    'schema','lowerboundsineq.omega_mid_staged_generation.v1', ...
    'generation_id',generation_id, ...
    'temporary_dir',temporary_dir, ...
    'generation_dir',generation_dir, ...
    'publication_root',publication_root, ...
    'summary_json',paths.summary_json, ...
    'summary_markdown',paths.summary_markdown, ...
    'pointer_source',pointer_source, ...
    'pointer_sha256',ver10_file_sha256(pointer_source), ...
    'generation_manifest_name',generation_manifest_name, ...
    'generation_manifest_sha256',generation_manifest_sha256);
clear cleanup
end




function release = local_release_destination()
repository = strtrim(getenv('VER10_RELEASE_REPOSITORY'));
tag = strtrim(getenv('VER10_RELEASE_TAG'));
parts = regexp(repository, ...
    '^([A-Za-z0-9_.-]+)/([A-Za-z0-9_.-]+)$','tokens','once');
if isempty(parts) ...
        || isempty(regexp(tag,'^[A-Za-z0-9_.-]+$','once'))
    error('run_omega_mid_unified_full:MissingReleaseDestination', ...
        ['Set VER10_RELEASE_REPOSITORY=owner/repo and a safe ', ...
         'VER10_RELEASE_TAG before starting the production run.']);
end
release = struct( ...
    'owner',parts{1},'repo',parts{2}, ...
    'repository',repository,'tag',tag);
end


function local_copy_bound(source,destination,expected_hash,label)
if ~strcmp(ver10_file_sha256(source),expected_hash)
    error('run_omega_mid_unified_full:ManifestHashMismatch', ...
        'The source %s does not match its unified-manifest SHA-256.',label);
end
[ok,message] = copyfile(source,destination,'f');
if ~ok || ~strcmp(ver10_file_sha256(destination),expected_hash)
    error('run_omega_mid_unified_full:GenerationCopyFailed', ...
        'Could not make a hash-identical %s copy: %s',label,message);
end
end


function local_copy_unified(source,destination)
[ok,message] = copyfile(source,destination,'f');
if ~ok || ~strcmp(ver10_file_sha256(source), ...
        ver10_file_sha256(destination))
    error('run_omega_mid_unified_full:GenerationCopyFailed', ...
        'Could not copy the unified manifest exactly: %s',message);
end
end


function local_finalize_staged_generation(staged)
local_validate_staged_paths(staged);
validate_omega_mid_publication_generation( ...
    staged.temporary_dir,staged.generation_manifest_sha256, ...
    'staging_pointer_sha256',staged.pointer_sha256);
local_delete_if_present(staged.pointer_source);
[ok,message] = movefile( ...
    staged.temporary_dir,staged.generation_dir);
if ~ok
    error('run_omega_mid_unified_full:GenerationPublishFailed', ...
        'Could not publish the staged generation: %s',message);
end
validate_omega_mid_publication_generation( ...
    staged.generation_dir,staged.generation_manifest_sha256);
fprintf('Published immutable Omega_mid generation %s.\n', ...
    staged.generation_id);
end


function local_abandon_staged_generation(staged)
local_validate_staged_paths(staged);
local_remove_bound_generation_if_present(staged.temporary_dir, ...
    staged.generation_manifest_name,staged.generation_manifest_sha256, ...
    staged.pointer_sha256);
local_remove_bound_generation_if_present(staged.generation_dir, ...
    staged.generation_manifest_name,staged.generation_manifest_sha256,'');
end


function local_validate_staged_paths(staged)
if ~isstruct(staged) ...
        || ~isfield(staged,'schema') ...
        || ~strcmp(staged.schema, ...
            'lowerboundsineq.omega_mid_staged_generation.v1') ...
        || ~isfield(staged,'publication_root') ...
        || ~isfield(staged,'temporary_dir') ...
        || ~isfield(staged,'generation_dir') ...
        || ~isfield(staged,'generation_manifest_name') ...
        || ~strcmp(staged.generation_manifest_name, ...
            'publication_manifest.json') ...
        || ~isfield(staged,'generation_manifest_sha256') ...
        || isempty(regexp(staged.generation_manifest_sha256, ...
            '^[0-9a-f]{64}$','once')) ...
        || ~isfield(staged,'pointer_source') ...
        || ~strcmp(staged.pointer_source,fullfile( ...
            staged.temporary_dir,'.omega_mid_current.json')) ...
        || ~isfield(staged,'pointer_sha256') ...
        || isempty(regexp(staged.pointer_sha256, ...
            '^[0-9a-f]{64}$','once')) ...
        || ~startsWith(staged.temporary_dir, ...
            [staged.publication_root,filesep]) ...
        || ~startsWith(staged.generation_dir, ...
            [staged.publication_root,filesep]) ...
        || strcmp(staged.temporary_dir,staged.generation_dir)
    error('run_omega_mid_unified_full:UnsafeStagedGeneration', ...
        'Refusing to alter an unrecognized generation path.');
end
end


function local_cleanup_publication_generation(publication)
generation = publication.generation;
local_validate_journal_generation( ...
    generation,publication.journal_path);
local_remove_bound_generation_if_present( ...
    generation.temporary_dir,generation.manifest_name, ...
    generation.manifest_sha256,generation.staging_pointer_sha256);
local_remove_bound_generation_if_present( ...
    generation.generation_dir,generation.manifest_name, ...
    generation.manifest_sha256,'');
end


function local_assert_committed_generation(publication)
generation = publication.generation;
local_validate_journal_generation( ...
    generation,publication.journal_path);
if exist(generation.temporary_dir,'dir')
    error('run_omega_mid_unified_full:CommittedStageStillPresent', ...
        'A committed journal unexpectedly retains its staging directory.');
end
validate_omega_mid_publication_generation( ...
    generation.generation_dir,generation.manifest_sha256);
end


function local_remove_bound_generation_if_present( ...
    pathname,manifest_name,expected_sha256,staging_pointer_sha256)
if ~exist(pathname,'dir')
    return;
end
if ~strcmp(manifest_name,'publication_manifest.json')
    error('run_omega_mid_unified_full:UnsafeGenerationCleanup', ...
        'Refusing cleanup with an unexpected manifest name.');
end
validate_omega_mid_publication_generation( ...
    pathname,expected_sha256, ...
    'staging_pointer_sha256',staging_pointer_sha256);
rmdir(pathname,'s');
end


function local_cleanup_files(filenames)
for k = 1:numel(filenames)
    if ~isempty(filenames{k})
        local_delete_if_present(filenames{k});
    end
end
end


function value = local_publication_field(record,name,default)
if isstruct(record) && isfield(record,name)
    value = record.(name);
else
    value = default;
end
end


function quoted = local_shell_quote(value)
value = char(value);
quoted = ['''',strrep(value,'''','''"''"'''),''''];
end


function local_write_json_atomic(filename,value)
try
    encoded = jsonencode(value,'PrettyPrint',true);
catch
    encoded = jsonencode(value);
end
directory = fileparts(filename);
temporary = [tempname(directory),'.json'];
cleanup = onCleanup(@() local_delete_if_present(temporary));
fid = fopen(temporary,'w');
if fid < 0
    error('run_omega_mid_unified_full:JsonWriteFailed', ...
        'Could not open a temporary JSON publication file.');
end
file_cleanup = onCleanup(@() fclose(fid));
fprintf(fid,'%s\n',encoded);
clear file_cleanup
[ok,message] = movefile(temporary,filename,'f');
if ~ok
    error('run_omega_mid_unified_full:JsonPublishFailed', ...
        'Could not atomically publish %s: %s',filename,message);
end
clear cleanup
end


function local_delete_if_present(filename)
if exist(filename,'file')
    delete(filename);
end
end


function local_remove_dir_if_present(pathname)
if exist(pathname,'dir')
    rmdir(pathname,'s');
end
end
