function bundle = validate_omega_mid_unified_artifacts( ...
    manifest,project_root,varargin)
%VALIDATE_OMEGA_MID_UNIFIED_ARTIFACTS Bind replay artifacts to a manifest.
%
% The full records, leaves, and FEM-attempt histories live in the unified
% results MAT file rather than in the public summary CSVs.  This validator
% fails closed unless J1, J2, geometric coverage, results MAT, and config
% MAT have exactly the SHA-256 digests recorded by the in-memory unified
% manifest.  Optional file overrides allow the identical validation to be
% repeated after copying the files into an immutable publication bundle.

p = inputParser;
p.CaseSensitive = true;
if isprop(p,'PartialMatching')
    p.PartialMatching = false;
end
addRequired(p,'manifest',@isstruct);
addRequired(p,'project_root',@(x) ischar(x) || isstring(x));
addParameter(p,'require_complete',true, ...
    @(x) islogical(x) && isscalar(x));
addParameter(p,'validate_record_structure',true, ...
    @(x) islogical(x) && isscalar(x));
addParameter(p,'J1_file','',@local_path_value);
addParameter(p,'J2_file','',@local_path_value);
addParameter(p,'coverage_file','',@local_path_value);
addParameter(p,'mat_file','',@local_path_value);
addParameter(p,'config_file','',@local_path_value);
addParameter(p,'unified_manifest_file','',@local_path_value);
parse(p,manifest,project_root,varargin{:});
project_root = char(p.Results.project_root);
require_complete = logical(p.Results.require_complete);
validate_record_structure = logical( ...
    p.Results.validate_record_structure);

if ~isfield(manifest,'schema') ...
        || ~strcmp(manifest.schema, ...
            'lowerboundsineq.omega_mid_unified.manifest.v2') ...
        || ~isfield(manifest,'fingerprint') ...
        || isempty(regexp(manifest.fingerprint, ...
            '^[0-9a-f]{64}$','once')) ...
        || ~isfield(manifest,'files') ...
        || ~isfield(manifest,'hashes') ...
        || ~isfield(manifest,'input') ...
        || ~isfield(manifest.input,'sha256') ...
        || ~isfield(manifest.input,'cell_count') ...
        || ~isfield(manifest,'selection') ...
        || ~isfield(manifest.selection,'selected_cell_count') ...
        || ~isfield(manifest.selection,'full_input_coverage') ...
        || ~local_boolean( ...
            manifest.selection.full_input_coverage) ...
        || ~isfield(manifest,'config') ...
        || ~isfield(manifest,'summary') ...
        || ~isfield(manifest.summary,'complete_certificate') ...
        || ~local_boolean(manifest.summary.complete_certificate) ...
        || ~isfield(manifest.summary, ...
            'exact_full_input_id_coverage') ...
        || ~local_boolean( ...
            manifest.summary.exact_full_input_id_coverage) ...
        || ~isfield(manifest.summary, ...
            'geometric_coverage_certified') ...
        || ~local_boolean( ...
            manifest.summary.geometric_coverage_certified) ...
        || ~isfield(manifest,'geometric_coverage') ...
        || ~isfield(manifest.geometric_coverage,'complete') ...
        || ~local_boolean(manifest.geometric_coverage.complete) ...
        || ~isfield(manifest.geometric_coverage,'rigorous') ...
        || ~local_boolean(manifest.geometric_coverage.rigorous) ...
        || ~isfield(manifest,'complete_certificate') ...
        || ~local_boolean(manifest.complete_certificate) ...
        || ~isfield(manifest,'source') ...
        || ~isfield(manifest,'runtime') ...
        || ~isfield(manifest,'runtime_sha256') ...
        || isempty(regexp(char(manifest.runtime_sha256), ...
            '^[0-9a-f]{64}$','once')) ...
        || ~isfield(manifest,'runtime_rechecked_after_run') ...
        || ~local_true_boolean( ...
            manifest.runtime_rechecked_after_run) ...
        || ~isfield(manifest,'worker_runtime_validation') ...
        || ~isfield(manifest,'execution')
    error('validate_omega_mid_unified_artifacts:BadManifest', ...
        'The unified manifest lacks required certificate metadata.');
end
if require_complete && (~manifest.complete_certificate ...
        || ~manifest.summary.complete_certificate ...
        || ~manifest.summary.exact_full_input_id_coverage ...
        || ~manifest.summary.geometric_coverage_certified)
    error('validate_omega_mid_unified_artifacts:IncompleteManifest', ...
        'Only a complete unified certificate can be published.');
end

file_fields = {'J1_csv','J2_csv','geometric_coverage_json', ...
    'mat','config_mat','json'};
hash_fields = {'J1_csv','J2_csv','geometric_coverage_json', ...
    'mat','config_mat'};
for k = 1:numel(file_fields)
    if ~isfield(manifest.files,file_fields{k})
        error('validate_omega_mid_unified_artifacts:MissingFileField', ...
            'The unified manifest lacks files.%s.',file_fields{k});
    end
end
for k = 1:numel(hash_fields)
    name = hash_fields{k};
    if ~isfield(manifest.hashes,name) ...
            || isempty(regexp(char(manifest.hashes.(name)), ...
                '^[0-9a-f]{64}$','once'))
        error('validate_omega_mid_unified_artifacts:MissingHashField', ...
            'The unified manifest lacks a valid hashes.%s.',name);
    end
end
if ~isfield(manifest.hashes,'input') ...
        || ~strcmp(manifest.hashes.input,manifest.input.sha256)
    error('validate_omega_mid_unified_artifacts:InputHashMismatch', ...
        'The unified input hashes are inconsistent.');
end

paths = struct( ...
    'J1_csv',local_choose_path(p.Results.J1_file, ...
        project_root,manifest.files.J1_csv), ...
    'J2_csv',local_choose_path(p.Results.J2_file, ...
        project_root,manifest.files.J2_csv), ...
    'geometric_coverage_json',local_choose_path( ...
        p.Results.coverage_file,project_root, ...
        manifest.files.geometric_coverage_json), ...
    'mat',local_choose_path(p.Results.mat_file, ...
        project_root,manifest.files.mat), ...
    'config_mat',local_choose_path(p.Results.config_file, ...
        project_root,manifest.files.config_mat), ...
    'json',local_choose_path(p.Results.unified_manifest_file, ...
        project_root,manifest.files.json));

actual_hashes = struct();
for k = 1:numel(hash_fields)
    name = hash_fields{k};
    filename = paths.(name);
    if exist(filename,'file') ~= 2
        error('validate_omega_mid_unified_artifacts:MissingArtifact', ...
            'Required unified artifact is missing: %s',filename);
    end
    actual_hashes.(name) = ver10_file_sha256(filename);
    if ~strcmp(actual_hashes.(name),manifest.hashes.(name))
        error('validate_omega_mid_unified_artifacts:ArtifactHashMismatch', ...
            '%s does not match unified manifest hashes.%s.', ...
            filename,name);
    end
end
if exist(paths.json,'file') ~= 2
    error('validate_omega_mid_unified_artifacts:MissingArtifact', ...
        'The unified JSON manifest is missing: %s',paths.json);
end
unified_json_sha_before = ver10_file_sha256(paths.json);

coverage = local_read_json(paths.geometric_coverage_json, ...
    'geometric coverage');
if ~isfield(coverage,'input') ...
        || ~isfield(coverage.input,'sha256') ...
        || ~strcmp(coverage.input.sha256,manifest.input.sha256) ...
        || ~isfield(coverage,'hashes') ...
        || ~isfield(coverage.hashes,'proof_payload') ...
        || ~isfield(manifest.geometric_coverage,'hashes') ...
        || ~isfield( ...
            manifest.geometric_coverage.hashes,'proof_payload') ...
        || ~strcmp(coverage.hashes.proof_payload, ...
            manifest.geometric_coverage.hashes.proof_payload) ...
        || ~isfield(coverage,'complete') ...
        || ~local_boolean(coverage.complete) ...
        || ~isfield(coverage,'rigorous') ...
        || ~local_boolean(coverage.rigorous) ...
        || (require_complete ...
            && (~coverage.complete || ~coverage.rigorous))
    error('validate_omega_mid_unified_artifacts:CoverageMismatch', ...
        'The hash-bound coverage JSON disagrees with the unified manifest.');
end

disk_manifest = local_read_json(paths.json,'unified manifest');
if ~local_same_manifest_identity(disk_manifest,manifest)
    error('validate_omega_mid_unified_artifacts:UnifiedManifestMismatch', ...
        ['The copied unified JSON does not reproduce the in-memory ', ...
         'certificate identity and artifact hashes.']);
end

variables = whos('-file',paths.mat);
variable_names = {variables.name};
required_variables = {'records','config','selection','summary', ...
    'geometric_coverage','fingerprint'};
if ~all(ismember(required_variables,variable_names))
    error('validate_omega_mid_unified_artifacts:IncompleteResultsMat', ...
        ['The results MAT omits records or metadata needed to replay ', ...
         'leaf and attempt certificates.']);
end
record_info = variables(strcmp(variable_names,'records'));
selected_count = double(manifest.selection.selected_cell_count);
if numel(record_info) ~= 1 ...
        || ~strcmp(record_info.class,'cell') ...
        || prod(double(record_info.size)) ~= selected_count ...
        || record_info.bytes <= 0
    error('validate_omega_mid_unified_artifacts:BadRecordsVariable', ...
        'The results MAT does not contain one record per selected cell.');
end
metadata = load(paths.mat,'config','selection','summary', ...
    'geometric_coverage','fingerprint');
if ~strcmp(metadata.fingerprint,manifest.fingerprint) ...
        || ~isequaln(metadata.config,manifest.config) ...
        || ~isequaln(metadata.summary,manifest.summary) ...
        || ~isequaln(metadata.geometric_coverage, ...
            manifest.geometric_coverage) ...
        || ~local_selection_matches( ...
            metadata.selection,manifest.selection)
    error('validate_omega_mid_unified_artifacts:ResultsMetadataMismatch', ...
        'The results MAT metadata disagrees with the unified manifest.');
end
if validate_record_structure
    record_statistics = local_validate_record_evidence( ...
        paths.mat,record_info,manifest,require_complete);
else
    record_statistics = struct( ...
        'leaf_count',NaN,'attempt_count',NaN);
end

config_variables = whos('-file',paths.config_mat);
config_names = {config_variables.name};
if ~all(ismember({'config','fingerprint','fingerprint_payload'}, ...
        config_names))
    error('validate_omega_mid_unified_artifacts:IncompleteConfigMat', ...
        'The config MAT omits its config, fingerprint, or payload.');
end
config_payload = load(paths.config_mat, ...
    'config','fingerprint','fingerprint_payload');
runtime_sha256 = local_sha256_bytes(uint8(jsonencode(manifest.runtime)));
runtime_token = sprintf('runtime=%s|',runtime_sha256);
if ~isfield(manifest.config,'schema') ...
        || ~strcmp(manifest.config.schema, ...
            'lowerboundsineq.omega_mid_unified.config.v3') ...
        || ~isfield(manifest.config,'runtime') ...
        || ~local_json_equivalent( ...
            manifest.config.runtime,manifest.runtime) ...
        || ~isfield(manifest.config,'runtime_sha256') ...
        || ~strcmp(manifest.config.runtime_sha256,runtime_sha256) ...
        || ~strcmp(manifest.runtime_sha256,runtime_sha256) ...
        || ~isfield(manifest.config, ...
            'worker_runtime_validation_policy') ...
        || ~strcmp(manifest.config.worker_runtime_validation_policy, ...
            'full-runtime-json-all-workers-before-and-after-dispatch-v1') ...
        || ~strcmp(config_payload.fingerprint,manifest.fingerprint) ...
        || ~isequaln(config_payload.config,manifest.config) ...
        || ~(ischar(config_payload.fingerprint_payload) ...
            || isstring(config_payload.fingerprint_payload)) ...
        || isempty(config_payload.fingerprint_payload) ...
        || ~strcmp(local_sha256_bytes(uint8(char( ...
            config_payload.fingerprint_payload))), ...
            manifest.fingerprint) ...
        || isempty(strfind(char(config_payload.fingerprint_payload), ...
            runtime_token)) %#ok<STREMP>
    error('validate_omega_mid_unified_artifacts:ConfigMetadataMismatch', ...
        'The config MAT does not reproduce the manifest fingerprint.');
end
ver10_validate_worker_runtime_record( ...
    manifest.worker_runtime_validation,runtime_sha256,[], ...
    'Omega_mid worker runtime validation');

% Close the validation window after the potentially long record scan.
% Manifest-bound payloads must still have both their expected and initial
% hashes.  The unified JSON cannot hash itself, so bind its initial bytes,
% reread its identity, and hash it once more after that reread.
for k = 1:numel(hash_fields)
    name = hash_fields{k};
    final_hash = ver10_file_sha256(paths.(name));
    if ~strcmp(final_hash,manifest.hashes.(name)) ...
            || ~strcmp(final_hash,actual_hashes.(name))
        error([ ...
            'validate_omega_mid_unified_artifacts:', ...
            'ArtifactChangedDuringValidation'], ...
            '%s changed during artifact validation.',paths.(name));
    end
end
unified_json_sha_after = ver10_file_sha256(paths.json);
disk_manifest_after = local_read_json(paths.json,'unified manifest');
if ~strcmp(unified_json_sha_before,unified_json_sha_after) ...
        || ~local_same_manifest_identity(disk_manifest_after,manifest) ...
        || ~strcmp(ver10_file_sha256(paths.json), ...
            unified_json_sha_before)
    error([ ...
        'validate_omega_mid_unified_artifacts:', ...
        'UnifiedManifestChangedDuringValidation'], ...
        'The unified JSON changed during artifact validation.');
end

bundle = struct();
bundle.schema = ...
    'lowerboundsineq.omega_mid_artifact_binding.v1';
bundle.paths = paths;
bundle.sha256 = actual_hashes;
bundle.unified_manifest_sha256 = unified_json_sha_after;
bundle.records_variable_class = record_info.class;
bundle.records_variable_count = prod(double(record_info.size));
bundle.leaf_count = record_statistics.leaf_count;
bundle.attempt_count = record_statistics.attempt_count;
bundle.leaf_attempt_evidence = ...
    'mat:records(:).leaves(:).attempts';
bundle.complete_certificate_required = require_complete;
end


function statistics = local_validate_record_evidence( ...
    filename,record_info,manifest,require_complete)
n = double(manifest.selection.selected_cell_count);
if numel(record_info.size) ~= 2 ...
        || record_info.size(1) ~= n || record_info.size(2) ~= 1
    error('validate_omega_mid_unified_artifacts:BadRecordsShape', ...
        'The records variable must be a selected-cell-count-by-one cell.');
end

block_size = 512;
use_partial_reader = true;
storage = [];
all_records = {};
try
    storage = matfile(filename);
    first_block = storage.records(1:min(n,block_size),1);
catch
    use_partial_reader = false;
    payload = load(filename,'records');
    all_records = payload.records(:);
    first_block = all_records(1:min(n,block_size));
end

cell_ids = zeros(n,1);
input_rows = zeros(n,1);
total_leaves = 0;
total_attempts = 0;
for first = 1:block_size:n
    last = min(first+block_size-1,n);
    if first == 1
        block = first_block;
    elseif use_partial_reader
        block = storage.records(first:last,1);
    else
        block = all_records(first:last);
    end
    if ~iscell(block) || numel(block) ~= last-first+1
        error('validate_omega_mid_unified_artifacts:BadRecordsBlock', ...
            'The records MAT returned an incomplete record block.');
    end
    for offset = 1:numel(block)
        index = first+offset-1;
        record = block{offset};
        [cell_ids(index),input_rows(index),leaf_count,attempt_count] = ...
            local_validate_one_record(record,require_complete);
        total_leaves = total_leaves+leaf_count;
        total_attempts = total_attempts+attempt_count;
    end
end
if numel(unique(cell_ids)) ~= n || numel(unique(input_rows)) ~= n
    error('validate_omega_mid_unified_artifacts:DuplicateRecordIdentity', ...
        'The records MAT repeats a cell ID or input row.');
end
if manifest.selection.full_input_coverage
    if n ~= double(manifest.input.cell_count) ...
            || ~isfield(manifest.input,'validation') ...
            || ~isfield( ...
                manifest.input.validation,'ids_equal_row_numbers') ...
            || ~local_true_boolean( ...
                manifest.input.validation.ids_equal_row_numbers) ...
            || ~isequal(sort(cell_ids),(1:n).') ...
            || ~isequal(sort(input_rows),(1:n).')
        error('validate_omega_mid_unified_artifacts:BadFullRecordSet', ...
            'The results MAT does not contain the exact full input set.');
    end
else
    expected_ids = double(manifest.selection.target_cell_ids(:));
    if numel(expected_ids) ~= n ...
            || ~isequal(sort(cell_ids),sort(expected_ids))
        error('validate_omega_mid_unified_artifacts:BadSelectedRecordSet', ...
            'The results MAT does not contain the selected cell-ID set.');
    end
end
statistics = struct( ...
    'leaf_count',total_leaves,'attempt_count',total_attempts);
end


function [cell_id,input_row,leaf_count,attempt_count] = ...
    local_validate_one_record(record,require_complete)
if ~isstruct(record) || ~isscalar(record) ...
        || ~isfield(record,'cell_id') ...
        || ~isfield(record,'input_row') ...
        || ~isfield(record,'leaf_count') ...
        || ~isfield(record,'leaves')
    error('validate_omega_mid_unified_artifacts:IncompleteRecord', ...
        'A results MAT record omits identity or leaf evidence.');
end
cell_id = double(record.cell_id);
input_row = double(record.input_row);
leaves = record.leaves(:);
leaf_count = numel(leaves);
if ~isscalar(cell_id) || ~isfinite(cell_id) ...
        || cell_id < 1 || cell_id ~= floor(cell_id) ...
        || ~isscalar(input_row) || ~isfinite(input_row) ...
        || input_row < 1 || input_row ~= floor(input_row) ...
        || ~isstruct(leaves) || isempty(leaves) ...
        || double(record.leaf_count) ~= leaf_count ...
        || (require_complete ...
            && (~isfield(record,'completed') ...
                || ~local_true_boolean(record.completed) ...
                || ~isfield(record,'strict_checks_passed') ...
                || ~local_true_boolean(record.strict_checks_passed)))
    error('validate_omega_mid_unified_artifacts:BadRecordEvidence', ...
        'A results MAT record has invalid identity or leaf counts.');
end

attempt_count = 0;
for k = 1:leaf_count
    leaf = leaves(k);
    if ~isfield(leaf,'attempts') ...
            || ~isstruct(leaf.attempts) || isempty(leaf.attempts) ...
            || ~isfield(leaf,'eigenvalue_attempts') ...
            || ~isfield(leaf,'selected_attempt_ordinal')
        error('validate_omega_mid_unified_artifacts:MissingAttempts', ...
            'A stored leaf omits its complete FEM-attempt history.');
    end
    attempts = leaf.attempts(:);
    count = numel(attempts);
    selected = double(leaf.selected_attempt_ordinal);
    if double(leaf.eigenvalue_attempts) ~= count ...
            || ~isscalar(selected) || selected < 1 ...
            || selected > count || selected ~= floor(selected) ...
            || ~all(arrayfun(@(attempt) ...
                isfield(attempt,'ordinal'),attempts)) ...
            || ~isequal(double([attempts.ordinal]).',(1:count).') ...
            || (require_complete ...
                && (~isfield(leaf,'strict_checks_passed') ...
                    || ~local_true_boolean(leaf.strict_checks_passed) ...
                    || ~isfield(attempts(selected), ...
                        'strict_checks_passed') ...
                    || ~local_true_boolean( ...
                        attempts(selected).strict_checks_passed)))
        error('validate_omega_mid_unified_artifacts:BadAttemptHistory', ...
            'A stored leaf has a truncated or inconsistent attempt history.');
    end
    attempt_count = attempt_count+count;
end
end


function tf = local_path_value(value)
tf = ischar(value) || isstring(value);
end


function filename = local_choose_path(override,project_root,relative)
override = char(override);
if ~isempty(override)
    filename = override;
    return;
end
relative = char(relative);
normalized = strrep(relative,'\','/');
if isempty(relative) || local_is_absolute_path(relative) ...
        || ~isempty(regexp(normalized,'(^|/)\.\.($|/)','once'))
    error('validate_omega_mid_unified_artifacts:UnsafeManifestPath', ...
        'A unified artifact path is not repository-relative.');
end
filename = fullfile(project_root,relative);
end


function tf = local_is_absolute_path(pathname)
tf = startsWith(pathname,filesep) ...
    || ~isempty(regexp(pathname,'^[A-Za-z]:[\\/]','once'));
end


function value = local_read_json(filename,label)
try
    value = jsondecode(fileread(filename));
catch ME
    error('validate_omega_mid_unified_artifacts:BadJson', ...
        'Cannot decode %s JSON %s: %s',label,filename,ME.message);
end
end


function tf = local_same_manifest_identity(disk,memory)
tf = isfield(disk,'schema') && strcmp(disk.schema,memory.schema) ...
    && isfield(disk,'fingerprint') ...
    && strcmp(disk.fingerprint,memory.fingerprint) ...
    && isfield(disk,'complete_certificate') ...
    && local_boolean(disk.complete_certificate) ...
    && isfield(memory,'complete_certificate') ...
    && local_boolean(memory.complete_certificate) ...
    && isequal(disk.complete_certificate,memory.complete_certificate) ...
    && isfield(disk,'input') && isfield(disk.input,'sha256') ...
    && strcmp(disk.input.sha256,memory.input.sha256) ...
    && isfield(disk.input,'cell_count') ...
    && double(disk.input.cell_count) == double(memory.input.cell_count) ...
    && isfield(disk,'files') && isfield(disk,'hashes');
if ~tf
    return;
end
critical_fields = {'input','config','selection','summary', ...
    'geometric_coverage','source','runtime','runtime_sha256', ...
    'runtime_rechecked_after_run','worker_runtime_validation', ...
    'execution','files','hashes'};
for k = 1:numel(critical_fields)
    name = critical_fields{k};
    if ~isfield(disk,name) ...
            || ~local_json_equivalent(disk.(name),memory.(name))
        tf = false;
        return;
    end
end
file_fields = {'J1_csv','J2_csv','geometric_coverage_json', ...
    'mat','config_mat'};
for k = 1:numel(file_fields)
    name = file_fields{k};
    if ~isfield(disk.files,name) ...
            || ~strcmp(char(disk.files.(name)), ...
                char(memory.files.(name))) ...
            || ~isfield(disk.hashes,name) ...
            || ~strcmp(disk.hashes.(name),memory.hashes.(name))
        tf = false;
        return;
    end
end
tf = isfield(disk.files,'json') ...
    && strcmp(char(disk.files.json),char(memory.files.json)) ...
    && isfield(disk,'geometric_coverage') ...
    && isfield(disk.geometric_coverage,'hashes') ...
    && isfield(disk.geometric_coverage.hashes,'proof_payload') ...
    && strcmp(disk.geometric_coverage.hashes.proof_payload, ...
        memory.geometric_coverage.hashes.proof_payload);
end


function tf = local_json_equivalent(left,right)
try
    tf = strcmp(jsonencode(left),jsonencode(right));
catch
    tf = isequaln(left,right);
end
end


function tf = local_selection_matches(saved,manifest_selection)
tf = isstruct(saved) ...
    && isfield(saved,'mode') ...
    && strcmp(saved.mode,manifest_selection.mode) ...
    && isfield(saved,'selected_ids_sha256') ...
    && strcmp(saved.selected_ids_sha256, ...
        manifest_selection.selected_ids_sha256) ...
    && isfield(saved,'manifest_cell_ids') ...
    && isequaln(saved.manifest_cell_ids, ...
        manifest_selection.target_cell_ids);
end


function digest = local_sha256_bytes(bytes)
engine = javaMethod( ...
    'getInstance','java.security.MessageDigest','SHA-256');
bytes = uint8(bytes(:));
if ~isempty(bytes)
    engine.update(typecast(bytes,'int8'));
end
raw = typecast(engine.digest(),'uint8');
digest = lower(reshape(dec2hex(raw,2).',1,[]));
end


function tf = local_boolean(value)
tf = islogical(value) && isscalar(value);
end


function tf = local_true_boolean(value)
tf = local_boolean(value) && value;
end
