function generation = validate_omega_mid_publication_generation( ...
    directory,expected_manifest_sha256,varargin)
%VALIDATE_OMEGA_MID_PUBLICATION_GENERATION Verify every immutable payload.
%
% The publication-manifest bytes, all eight sibling artifacts, and both
% expanded CSV contents are checked.  Every byte-level hash is repeated at
% the end so a persistent replacement during validation fails closed.

directory = char(directory);
expected_manifest_sha256 = char(expected_manifest_sha256);
p = inputParser;
p.CaseSensitive = true;
if isprop(p,'PartialMatching')
    p.PartialMatching = false;
end
addParameter(p,'staging_pointer_sha256','', ...
    @(x) ischar(x) || isstring(x));
parse(p,varargin{:});
staging_pointer_sha256 = char(p.Results.staging_pointer_sha256);
if ~isempty(staging_pointer_sha256) ...
        && isempty(regexp(staging_pointer_sha256, ...
            '^[0-9a-f]{64}$','once'))
    error([ ...
        'validate_omega_mid_publication_generation:', ...
        'BadStagingPointerHash'], ...
        'The optional staging-pointer SHA-256 is invalid.');
end
manifest_name = 'publication_manifest.json';
manifest_path = fullfile(directory,manifest_name);
if isempty(regexp(expected_manifest_sha256,'^[0-9a-f]{64}$','once')) ...
        || exist(manifest_path,'file') ~= 2 ...
        || ~strcmp(ver10_file_sha256(manifest_path), ...
            expected_manifest_sha256)
    error([ ...
        'validate_omega_mid_publication_generation:', ...
        'ManifestHashMismatch'], ...
        'The publication manifest is missing or has the wrong SHA-256.');
end
try
    generation = jsondecode(fileread(manifest_path));
catch ME
    error([ ...
        'validate_omega_mid_publication_generation:', ...
        'BadManifest'], ...
        'Cannot decode the publication manifest: %s',ME.message);
end

file_fields = {'J1_OmegaMid_csv_gz','J2_OmegaMid_csv_gz', ...
    'verification_summary_json','verification_summary_markdown', ...
    'omega_mid_geometric_coverage_manifest', ...
    'omega_mid_unified_manifest','omega_mid_unified_results_mat', ...
    'config_mat'};
fixed_names = {'J1_OmegaMid.csv.gz','J2_OmegaMid.csv.gz', ...
    'verification_summary.json','verification_summary.md', ...
    'omega_mid_geometric_coverage_manifest.json', ...
    'omega_mid_unified_manifest.json','','config.mat'};
if ~isstruct(generation) ...
        || ~isfield(generation,'schema') ...
        || ~strcmp(generation.schema, ...
            'lowerboundsineq.omega_mid_publication_generation.v2') ...
        || ~isfield(generation,'files') ...
        || ~isfield(generation,'sha256') ...
        || ~isfield(generation,'compression') ...
        || ~isfield(generation.compression,'algorithm') ...
        || ~strcmp(generation.compression.algorithm,'gzip') ...
        || ~isfield(generation.compression,'options') ...
        || ~strcmp(generation.compression.options,'-n -9') ...
        || ~isfield(generation.compression,'roundtrip_verified') ...
        || ~local_true_boolean( ...
            generation.compression.roundtrip_verified) ...
        || ~isfield(generation.compression, ...
            'independent_encodings_identical') ...
        || ~local_true_boolean( ...
            generation.compression.independent_encodings_identical) ...
        || ~isfield(generation.sha256, ...
            'J1_OmegaMid_csv_expanded_content') ...
        || ~isfield(generation.sha256, ...
            'J2_OmegaMid_csv_expanded_content')
    error([ ...
        'validate_omega_mid_publication_generation:', ...
        'BadManifest'], ...
        'The publication manifest lacks required artifact metadata.');
end
if ~isequal(sort(fieldnames(generation.files)),sort(file_fields(:)))
    error([ ...
        'validate_omega_mid_publication_generation:', ...
        'BadManifest'], ...
        'The publication manifest files set is not exactly eight payloads.');
end

artifact_paths = cell(size(file_fields));
artifact_hashes_before = cell(size(file_fields));
artifact_names = cell(size(file_fields));
for k = 1:numel(file_fields)
    field = file_fields{k};
    if ~isfield(generation.files,field) ...
            || ~isfield(generation.sha256,field)
        error([ ...
            'validate_omega_mid_publication_generation:', ...
            'BadManifest'], ...
            'The publication manifest omits %s.',field);
    end
    artifact_names{k} = char(generation.files.(field));
    expected_hash = char(generation.sha256.(field));
    if isempty(artifact_names{k}) ...
            || ~strcmp(fileparts(artifact_names{k}),'') ...
            || isempty(regexp(expected_hash,'^[0-9a-f]{64}$','once')) ...
            || (~isempty(fixed_names{k}) ...
                && ~strcmp(artifact_names{k},fixed_names{k})) ...
            || (strcmp(field,'omega_mid_unified_results_mat') ...
                && isempty(regexp(artifact_names{k}, ...
                    ['^omega_mid_unified_results_', ...
                     '[A-Za-z0-9_]+\.mat$'],'once')))
        error([ ...
            'validate_omega_mid_publication_generation:', ...
            'BadArtifactPath'], ...
            'The publication manifest has an unsafe artifact entry.');
    end
    artifact_paths{k} = fullfile(directory,artifact_names{k});
    if exist(artifact_paths{k},'file') ~= 2
        error([ ...
            'validate_omega_mid_publication_generation:', ...
            'MissingArtifact'], ...
            'A publication payload is missing: %s',artifact_names{k});
    end
    artifact_hashes_before{k} = ver10_file_sha256(artifact_paths{k});
    if ~strcmp(artifact_hashes_before{k},expected_hash)
        error([ ...
            'validate_omega_mid_publication_generation:', ...
            'ArtifactHashMismatch'], ...
            'Publication payload %s has the wrong SHA-256.', ...
            artifact_names{k});
    end
end
if numel(unique(artifact_names)) ~= numel(artifact_names)
    error([ ...
        'validate_omega_mid_publication_generation:', ...
        'BadArtifactPath'], ...
        'Publication payload names must be distinct.');
end

expanded_fields = {'J1_OmegaMid_csv_expanded_content', ...
    'J2_OmegaMid_csv_expanded_content'};
for k = 1:2
    expanded_hash = char(generation.sha256.(expanded_fields{k}));
    if isempty(regexp(expanded_hash,'^[0-9a-f]{64}$','once'))
        error([ ...
            'validate_omega_mid_publication_generation:', ...
            'BadManifest'], ...
            'A gzip expanded-content SHA-256 is invalid.');
    end
    ver10_verify_gzip_artifact(artifact_paths{k}, ...
        artifact_hashes_before{k},expanded_hash);
end

if ~isfield(generation,'artifact_resolution') ...
        || ~isfield(generation.artifact_resolution, ...
            'results_mat_release_asset') ...
        || ~isfield(generation,'leaf_attempt_evidence')
    error([ ...
        'validate_omega_mid_publication_generation:', ...
        'ResolutionMismatch'], ...
        'Publication replay-resolution metadata is missing.');
end
release_asset = ...
    generation.artifact_resolution.results_mat_release_asset;
evidence = generation.leaf_attempt_evidence;
if ~isfield(release_asset,'owner') ...
        || isempty(regexp(char(release_asset.owner), ...
            '^[A-Za-z0-9_.-]+$','once')) ...
        || ~isfield(release_asset,'repo') ...
        || isempty(regexp(char(release_asset.repo), ...
            '^[A-Za-z0-9_.-]+$','once')) ...
        || ~isfield(release_asset,'repository') ...
        || ~strcmp(release_asset.repository, ...
            [release_asset.owner,'/',release_asset.repo]) ...
        || ~isfield(release_asset,'tag') ...
        || isempty(regexp(char(release_asset.tag), ...
            '^[A-Za-z0-9_.-]+$','once')) ...
        || ~isfield(release_asset,'name') ...
        || ~strcmp(release_asset.name,artifact_names{7}) ...
        || ~isfield(release_asset,'url') ...
        || ~strcmp(release_asset.url,sprintf( ...
            'https://github.com/%s/releases/download/%s/%s', ...
            release_asset.repository,release_asset.tag, ...
            release_asset.name)) ...
        || ~isfield(release_asset,'sha256') ...
        || ~strcmp(release_asset.sha256,artifact_hashes_before{7}) ...
        || ~isfield(evidence,'file') ...
        || ~strcmp(evidence.file,artifact_names{7}) ...
        || ~isfield(evidence,'sha256') ...
        || ~strcmp(evidence.sha256,artifact_hashes_before{7}) ...
        || ~isfield(evidence,'config_file') ...
        || ~strcmp(evidence.config_file,artifact_names{8}) ...
        || ~isfield(evidence,'config_sha256') ...
        || ~strcmp(evidence.config_sha256,artifact_hashes_before{8})
    error([ ...
        'validate_omega_mid_publication_generation:', ...
        'ResolutionMismatch'], ...
        'Publication replay-resolution metadata is inconsistent.');
end

for k = 1:numel(file_fields)
    expected_hash = char(generation.sha256.(file_fields{k}));
    if ~strcmp(ver10_file_sha256(artifact_paths{k}),expected_hash) ...
            || ~strcmp(artifact_hashes_before{k},expected_hash)
        error([ ...
            'validate_omega_mid_publication_generation:', ...
            'ArtifactChangedDuringValidation'], ...
            'A publication payload changed during validation.');
    end
end
if ~strcmp(ver10_file_sha256(manifest_path), ...
        expected_manifest_sha256)
    error([ ...
        'validate_omega_mid_publication_generation:', ...
        'ManifestChangedDuringValidation'], ...
        'The publication manifest changed during validation.');
end
decoded_after = jsondecode(fileread(manifest_path));
if ~strcmp(jsonencode(decoded_after),jsonencode(generation)) ...
        || ~strcmp(ver10_file_sha256(manifest_path), ...
            expected_manifest_sha256)
    error([ ...
        'validate_omega_mid_publication_generation:', ...
        'ManifestChangedDuringValidation'], ...
        'The publication manifest changed while it was being read.');
end
local_validate_directory_entries( ...
    directory,generation,manifest_name,staging_pointer_sha256);
end


function local_validate_directory_entries( ...
    directory,generation,manifest_name,staging_pointer_sha256)
payload_names = struct2cell(generation.files);
payload_names = cellfun(@char,payload_names,'UniformOutput',false);
allowed = [{manifest_name};payload_names(:)];
pointer_name = '.omega_mid_current.json';
pointer_path = fullfile(directory,pointer_name);
if ~isempty(staging_pointer_sha256)
    allowed{end+1,1} = pointer_name;
    if exist(pointer_path,'file') == 2
        pointer_sha_before = ver10_file_sha256(pointer_path);
        if ~strcmp(pointer_sha_before,staging_pointer_sha256) ...
                || ~strcmp(ver10_file_sha256(pointer_path), ...
                    pointer_sha_before)
            error([ ...
                'validate_omega_mid_publication_generation:', ...
                'StagingPointerHashMismatch'], ...
                'The optional staging pointer has the wrong SHA-256.');
        end
    end
end
% Query both ordinary and dot-prefixed entries: platform wildcard behavior
% must not let an unlisted hidden file escape the destructive cleanup gate.
entries = [dir(fullfile(directory,'*')); ...
    dir(fullfile(directory,'.*'))];
for k = 1:numel(entries)
    name = entries(k).name;
    if any(strcmp(name,{'.','..'}))
        continue;
    end
    if entries(k).isdir || ~any(strcmp(name,allowed))
        error([ ...
            'validate_omega_mid_publication_generation:', ...
            'UnexpectedDirectoryEntry'], ...
            ['The generation contains an unlisted file or directory; ', ...
             'automatic publication or deletion is refused.']);
    end
end
if exist(pointer_path,'file') == 2 ...
        && isempty(staging_pointer_sha256)
    error([ ...
        'validate_omega_mid_publication_generation:', ...
        'UnexpectedDirectoryEntry'], ...
        'A staging pointer is not permitted in a finalized generation.');
end
end


function tf = local_true_boolean(value)
tf = islogical(value) && isscalar(value) && value;
end
