function record = ver10_validate_worker_runtime_record( ...
    record,expected_runtime_sha256,expected_workers,context)
%VER10_VALIDATE_WORKER_RUNTIME_RECORD Validate persisted all-worker gates.

if nargin < 4
    context = 'worker runtime validation';
end
context = char(context);
expected_runtime_sha256 = char(expected_runtime_sha256);
if isempty(regexp(expected_runtime_sha256,'^[0-9a-f]{64}$','once'))
    error('ver10_validate_worker_runtime_record:BadExpectedHash', ...
        'The expected runtime SHA-256 is malformed.');
end
if nargin < 3 || isempty(expected_workers)
    expected_workers = [];
elseif ~(isnumeric(expected_workers) && isreal(expected_workers) ...
        && isscalar(expected_workers) && isfinite(expected_workers) ...
        && expected_workers >= 0 ...
        && expected_workers == floor(expected_workers))
    error('ver10_validate_worker_runtime_record:BadExpectedCount', ...
        'The expected worker count must be a nonnegative integer.');
else
    expected_workers = double(expected_workers);
end

local_require(isstruct(record) && isscalar(record),context, ...
    'is not a scalar structure');
local_require(isfield(record,'policy') && ischar(record.policy) ...
        && strcmp(record.policy, ...
            'full-runtime-json-all-workers-before-and-after-dispatch-v1'), ...
    context,'has an unsupported validation policy');
local_require(isfield(record,'runtime_sha256') ...
        && ischar(record.runtime_sha256) ...
        && strcmp(record.runtime_sha256,expected_runtime_sha256), ...
    context,'does not bind the expected runtime SHA-256');
local_require(isfield(record,'all_computation_workers_checked') ...
        && local_true_boolean(record.all_computation_workers_checked), ...
    context,'does not assert that every computation worker was checked');
local_require(isfield(record,'before_dispatch') ...
        && isfield(record,'after_dispatch'),context, ...
    'omits a before- or after-dispatch report');
before = local_validate_phase( ...
    record.before_dispatch,expected_runtime_sha256,context);
after = local_validate_phase( ...
    record.after_dispatch,expected_runtime_sha256,context);
local_require(before.worker_count == after.worker_count,context, ...
    'has different before/after worker populations');
if ~isempty(expected_workers)
    local_require(before.worker_count == expected_workers,context, ...
        'does not cover the expected worker population');
end
end


function report = local_validate_phase(report,expected_sha256,context)
local_require(isstruct(report) && isscalar(report),context, ...
    'contains a nonscalar phase report');
local_require(isfield(report,'schema') && ischar(report.schema) ...
        && strcmp(report.schema, ...
            'lowerboundsineq.worker-runtime-validation.v1'), ...
    context,'contains an unsupported phase-report schema');
local_require(isfield(report,'phase') && ischar(report.phase) ...
        && ~isempty(report.phase),context, ...
    'contains an empty phase label');
local_require(isfield(report,'runtime_sha256') ...
        && ischar(report.runtime_sha256) ...
        && strcmp(report.runtime_sha256,expected_sha256), ...
    context,'contains a phase report for a different runtime');
local_require(isfield(report,'worker_count') ...
        && isnumeric(report.worker_count) && isreal(report.worker_count) ...
        && isscalar(report.worker_count) && isfinite(report.worker_count) ...
        && report.worker_count >= 0 ...
        && report.worker_count == floor(report.worker_count), ...
    context,'contains an invalid worker count');
local_require(isfield(report,'all_workers_returned') ...
        && local_true_boolean(report.all_workers_returned), ...
    context,'did not receive one report from every worker');
local_require(isfield(report,'all_workers_full_runtime_json_match') ...
        && local_true_boolean( ...
            report.all_workers_full_runtime_json_match), ...
    context,'contains a worker whose full runtime JSON did not match');
report.worker_count = double(report.worker_count);
end


function tf = local_true_boolean(value)
tf = islogical(value) && isscalar(value) && value;
end


function local_require(condition,context,message)
if ~(islogical(condition) && isscalar(condition) && condition)
    error('ver10_validate_worker_runtime_record:InvalidRecord', ...
        '%s %s.',context,message);
end
end
