function report = ver10_assert_worker_runtime( ...
    pool,trusted_runtime,expected_sha256,phase)
%VER10_ASSERT_WORKER_RUNTIME Verify the full runtime on every local worker.
%
% Call this only after OMEGA_UP_ALL_PREPARE_WORKER has completed on all
% workers.  PARFEVALONALL returns one validation report per worker; this
% function checks both the returned population and every report rather
% than treating completion of the broadcast as sufficient evidence.

if nargin < 4
    phase = 'unspecified-worker-phase';
end
phase = char(phase);
if isempty(pool) || ~isobject(pool) || ~isprop(pool,'NumWorkers') ...
        || ~isscalar(pool.NumWorkers) || pool.NumWorkers < 1 ...
        || pool.NumWorkers ~= floor(pool.NumWorkers)
    error('ver10_assert_worker_runtime:BadPool', ...
        'A nonempty parallel pool is required.');
end
if ~isstruct(trusted_runtime) || ~isscalar(trusted_runtime)
    error('ver10_assert_worker_runtime:BadTrustedRuntime', ...
        'The trusted runtime must be a scalar structure.');
end
expected_sha256 = char(expected_sha256);
if isempty(regexp(expected_sha256,'^[0-9a-f]{64}$','once'))
    error('ver10_assert_worker_runtime:BadExpectedHash', ...
        'The expected runtime SHA-256 is malformed.');
end

future = parfevalOnAll(pool,@ver10_assert_runtime_snapshot,1, ...
    trusted_runtime,expected_sha256,phase);
wait(future);
% FEVALONALLFUTURE is a scalar broadcast future.  FETCHOUTPUTS both
% rethrows a worker failure and returns its per-worker output cell; do not
% treat Future.Error as an MException array (it is release-dependent and
% is a cell-valued property in the supported R2023b runtime).
raw_worker_reports = fetchOutputs(future);
raw_output_class = class(raw_worker_reports);
raw_output_count = numel(raw_worker_reports);
if isstruct(raw_worker_reports)
    worker_reports = num2cell(raw_worker_reports);
elseif iscell(raw_worker_reports)
    worker_reports = raw_worker_reports;
else
    worker_reports = {};
end
if numel(worker_reports) ~= double(pool.NumWorkers)
    error('ver10_assert_worker_runtime:IncompleteWorkerPopulation', ...
        'The runtime broadcast did not return one report per worker.');
end
for k = 1:numel(worker_reports)
    current = worker_reports{k};
    if ~isstruct(current) || ~isscalar(current) ...
            || ~isfield(current,'schema') ...
            || ~strcmp(current.schema, ...
                'lowerboundsineq.runtime-snapshot-validation.v1') ...
            || ~isfield(current,'runtime_sha256') ...
            || ~strcmp(current.runtime_sha256,expected_sha256) ...
            || ~isfield(current,'full_runtime_json_match') ...
            || ~islogical(current.full_runtime_json_match) ...
            || ~isscalar(current.full_runtime_json_match) ...
            || ~current.full_runtime_json_match
        error('ver10_assert_worker_runtime:BadWorkerReport', ...
            'Worker %d returned an invalid runtime report.',k);
    end
end

report = struct( ...
    'schema','lowerboundsineq.worker-runtime-validation.v1', ...
    'phase',phase, ...
    'runtime_sha256',expected_sha256, ...
    'worker_count',double(pool.NumWorkers), ...
    'broadcast_output_class',raw_output_class, ...
    'broadcast_output_count',raw_output_count, ...
    'all_workers_returned',true, ...
    'all_workers_full_runtime_json_match',true);
end
