function global_manifest = verify_upper_rayleigh_global_manifests( ...
    thin_manifest_path,compact_manifest_path,residual_manifest_path, ...
    spectral_atlas_path,output_path)
%VERIFY_UPPER_RAYLEIGH_GLOBAL_MANIFESTS Join all three upper-bound covers.
%
% This verifier replays the thin Rayleigh and CR--LG spectral artifacts,
% validates the hashes, scopes, signs, and covers of the affine-atlas and
% residual CSVs through the v1 global verifier, and binds every component.

if nargin < 5
    output_path = '';
end
project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root,'src','degenerate'));
addpath(fullfile(project_root,'scripts_run'));
snapshot = struct( ...
    'thin_manifest',ver10_file_sha256(thin_manifest_path), ...
    'compact_manifest',ver10_file_sha256(compact_manifest_path), ...
    'residual_manifest',ver10_file_sha256(residual_manifest_path), ...
    'spectral_atlas',ver10_file_sha256(spectral_atlas_path));
verification_source_before = ver10_source_provenance(project_root);
verification_hashes_before = local_verifier_hashes(project_root);
local_require(verification_source_before.git_status_available ...
    && ~verification_source_before.git_dirty ...
    && ~isempty(verification_source_before.git_commit), ...
    'The global verifier must run from a clean committed source tree.');

thin_validation = validate_muhat1_rayleigh_certificate( ...
    thin_manifest_path,'require_complete_certificate',true);
local_require(thin_validation.complete ...
    && thin_validation.manifest_complete_certificate, ...
    'The thin Rayleigh artifact is not a complete replayed certificate.');
base = verify_upper_conjecture_global_manifests( ...
    compact_manifest_path,residual_manifest_path,'', ...
    'allow_independent_commits',true);
local_require(base.complete_certificate, ...
    'The affine-atlas/residual certificate is incomplete.');

thin = local_read_json(thin_manifest_path,'thin');
compact = local_read_json(compact_manifest_path,'compact');
residual = local_read_json(residual_manifest_path,'residual');
thin_source = local_struct(thin,'source','thin');
compact_source = local_struct(compact,'source','compact');
residual_source = local_struct(residual,'source','residual');
thin_commit = local_text(thin_source,'git_commit','thin.source');
compact_commit = local_text(compact_source,'git_commit','compact.source');
residual_commit = local_text(residual_source,'git_commit','residual.source');
local_require(strcmp(thin_commit,residual_commit), ...
    ['The newly generated thin and residual components do not use one ', ...
     'source commit.']);
local_require(strcmp(verification_source_before.git_commit,thin_commit), ...
    'The global verifier is not running from the new components'' commit.');

thin_config = local_struct(thin,'config','thin');
thin_y_start = 0;
thin_y_end = local_decimal_text_number( ...
    thin_config,'down_y_max_text','thin.config');
atlas = local_struct(compact,'atlas','compact');
atlas_y_start = local_number(atlas,'y_min','compact.atlas');
atlas_y_end = local_number(atlas,'y_up','compact.atlas');
residual_y_start = local_number( ...
    local_struct(residual,'domain_coverage','residual'), ...
    'JUP_certified_y_start_upper','residual.domain_coverage');
local_require(thin_y_end == 0.19, ...
    'The thin Rayleigh component does not reach the canonical y=0.19.');
local_require(atlas_y_start <= thin_y_end, ...
    'The thin Rayleigh and affine-atlas covers have a gap.');
local_require(residual_y_start < atlas_y_end, ...
    'The affine-atlas and residual covers do not overlap.');

thin_runtime = local_struct(thin,'runtime','thin');
compact_runtime = local_struct(compact,'runtime','compact');
residual_runtime = local_struct(residual,'runtime','residual');
trusted_runtime = local_validate_matching_runtime( ...
    {thin_runtime,residual_runtime});
compact_runtime_record = local_validate_legacy_runtime(compact_runtime);
residual_config = local_struct(residual,'config','residual');
residual_runtime_sha256 = local_sha256_bytes( ...
    uint8(jsonencode(residual_runtime)));
local_require(local_flag(residual, ...
        'runtime_rechecked_after_run','residual') ...
    && strcmp(local_sha256(residual,'runtime_sha256','residual'), ...
        residual_runtime_sha256), ...
    ['The residual artifact does not bind a runtime snapshot that was ', ...
     'rechecked after generation.']);
residual_config_runtime = local_struct( ...
    residual_config,'runtime','residual.config');
local_require(strcmp(jsonencode(residual_config_runtime), ...
        jsonencode(residual_runtime)) ...
    && strcmp(local_sha256(residual_config, ...
        'runtime_sha256','residual.config'),residual_runtime_sha256), ...
    'The residual config and manifest runtime bindings disagree.');
local_require(strcmp(local_text(residual_config, ...
        'worker_runtime_validation_policy','residual.config'), ...
        'full-runtime-json-all-workers-before-and-after-dispatch-v1'), ...
    'The residual config has an unsupported worker-runtime policy.');
residual_worker_runtime = local_struct( ...
    residual,'worker_runtime_validation','residual');
ver10_validate_worker_runtime_record( ...
    residual_worker_runtime,residual_runtime_sha256,[], ...
    'residual worker runtime validation');
expected_atlas_sha256 = local_sha256( ...
    residual_config,'spectral_atlas_sha256','residual.config');
global_replay_runtime_before = ver10_runtime_metadata();
global_replay_runtime_before_payload = jsonencode( ...
    global_replay_runtime_before);
global_replay_runtime_sha256 = local_sha256_bytes( ...
    uint8(global_replay_runtime_before_payload));
local_require(strcmp(global_replay_runtime_before_payload, ...
        jsonencode(thin_runtime)) ...
    && strcmp(global_replay_runtime_sha256, ...
        trusted_runtime.record_sha256), ...
    'The current replay runtime does not match the component runtime.');
spectral = local_validate_spectral_atlas( ...
    spectral_atlas_path,expected_atlas_sha256,thin_commit, ...
    thin_runtime,trusted_runtime.record_sha256);
global_replay_runtime_after = ver10_runtime_metadata();
global_replay_runtime_after_payload = jsonencode( ...
    global_replay_runtime_after);
global_replay_runtime_after_sha256 = local_sha256_bytes( ...
    uint8(global_replay_runtime_after_payload));
local_require(strcmp(global_replay_runtime_before_payload, ...
        global_replay_runtime_after_payload) ...
    && strcmp(global_replay_runtime_sha256, ...
        global_replay_runtime_after_sha256), ...
    'The numerical runtime changed during the spectral replay.');
verification_source_after = ver10_assert_source_unchanged( ...
    project_root,verification_source_before);

thin_summary = local_struct(thin,'summary','thin');
thin_hashes = local_struct(thin,'hashes','thin');
global_manifest = struct();
global_manifest.schema = ...
    'lowerboundsineq.siudeja-upper-global-rayleigh.manifest.v2';
global_manifest.theorem = ...
    ['lambda1(T) <= pi^2*P(T)^2/(12*A(T)^2) ', ...
     '+sqrt(3)*pi^2/(3*A(T)) for every triangle T'];
global_manifest.rigor = ...
    'certified_interval_execution_with_thin_and_spectral_replay';
global_manifest.complete_certificate = true;
global_manifest.source = struct( ...
    'thin_git_commit',thin_commit, ...
    'affine_git_commit',compact_commit, ...
    'residual_git_commit',residual_commit, ...
    'spectral_atlas_git_commit',thin_commit, ...
    'component_commits_are_independent',~strcmp(thin_commit,compact_commit), ...
    'all_components_clean',true, ...
    'all_components_unchanged_after_run',true);
global_manifest.cover = struct( ...
    'thin_y_closed_hull',[thin_y_start,thin_y_end], ...
    'affine_y_closed_hull',[atlas_y_start,atlas_y_end], ...
    'residual_y_start',residual_y_start, ...
    'thin_affine_overlap',[atlas_y_start,thin_y_end], ...
    'affine_residual_overlap',[residual_y_start,atlas_y_end], ...
    'normalized_domain_complete',true);
global_manifest.margins = struct( ...
    'thin_functional_upper_display',local_number( ...
        thin_summary,'max_down_scaled_upper_display','thin.summary'), ...
    'thin_functional_upper_hex',local_text( ...
        thin_summary,'max_down_scaled_upper_hex','thin.summary'), ...
    'affine_margin_lower',local_number( ...
        local_struct(base,'margins','base'), ...
        'compact_lower','base.margins'), ...
    'residual_JUP_upper',local_number( ...
        local_struct(base,'margins','base'), ...
        'residual_JUP_upper','base.margins'));
local_require(global_manifest.margins.thin_functional_upper_display < 0 ...
    && global_manifest.margins.affine_margin_lower > 0 ...
    && global_manifest.margins.residual_JUP_upper < 0, ...
    'A global upper-bound margin has the wrong strict sign.');
global_manifest.counts = struct( ...
    'thin_s_cells',thin_validation.number_of_s_cells, ...
    'thin_down_cells',thin_validation.number_of_down_cells, ...
    'affine_cells',local_number(atlas,'number_of_cells','compact.atlas'), ...
    'spectral_anchor_certificates',spectral.num_certificates, ...
    'spectral_anchor_certificates_replayed',spectral.num_replayed);
global_manifest.inputs = struct( ...
    'thin_manifest_sha256',snapshot.thin_manifest, ...
    'thin_coefficients_csv_sha256',local_sha256( ...
        thin_hashes,'coefficients_csv','thin.hashes'), ...
    'thin_cells_csv_sha256',local_sha256( ...
        thin_hashes,'cells_csv','thin.hashes'), ...
    'thin_down_cells_csv_sha256',local_sha256( ...
        thin_hashes,'down_cells_csv','thin.hashes'), ...
    'compact_manifest_sha256',snapshot.compact_manifest, ...
    'compact_csv_sha256',local_text( ...
        local_struct(base,'inputs','base'), ...
        'compact_csv_sha256','base.inputs'), ...
    'residual_manifest_sha256',snapshot.residual_manifest, ...
    'residual_csv_sha256',local_text( ...
        local_struct(base,'inputs','base'), ...
        'residual_csv_sha256','base.inputs'), ...
    'spectral_atlas_sha256',expected_atlas_sha256);
global_manifest.trusted_runtime = trusted_runtime;
global_manifest.global_replay_runtime_sha256 = ...
    global_replay_runtime_sha256;
global_manifest.global_replay_runtime_rechecked_after_run = true;
global_manifest.global_replay_worker_runtime_validation = ...
    spectral.worker_runtime_validation;
global_manifest.affine_component_runtime = compact_runtime_record;
global_manifest.verification_source = struct( ...
    'git_commit',verification_source_after.git_commit, ...
    'git_status_available',verification_source_after.git_status_available, ...
    'git_dirty',verification_source_after.git_dirty, ...
    'source_unchanged_after_run', ...
        verification_source_after.source_unchanged_after_run, ...
    'rayleigh_global_verifier_sha256', ...
        verification_hashes_before.rayleigh_global, ...
    'affine_residual_verifier_sha256', ...
        verification_hashes_before.affine_residual, ...
    'thin_verifier_sha256',verification_hashes_before.thin);
global_manifest.verification_source.runtime_snapshot_validator_sha256 = ...
    verification_hashes_before.runtime_snapshot;
global_manifest.verification_source.worker_runtime_validator_sha256 = ...
    verification_hashes_before.worker_runtime;
global_manifest.verification_source.persisted_worker_runtime_validator_sha256 = ...
    verification_hashes_before.persisted_worker_runtime;
global_manifest.distribution = local_distribution_record( ...
    expected_atlas_sha256);
global_manifest.validation = struct( ...
    'thin_lossless_interval_replay',true, ...
    'affine_csv_hash_scope_sign_and_cover_rechecked',true, ...
    'affine_interval_execution_is_trusted_evidence',true, ...
    'residual_csv_hash_scope_sign_and_cover_rechecked',true, ...
    'residual_interval_execution_is_trusted_evidence',true, ...
    'spectral_atlas_structure_rechecked',true, ...
    'spectral_atlas_independently_recomputed',true, ...
    'global_replay_runtime_rechecked',true, ...
    'global_replay_all_workers_runtime_rechecked', ...
        spectral.worker_runtime_validation.all_computation_workers_checked, ...
    'component_hashes_rechecked',true);

% Bind the provenance fields to the same verifier bytes that were present
% before any replay began.  This closes the final assembly window as well
% as checking the component artifacts themselves below.
verification_source_final = ver10_assert_source_unchanged( ...
    project_root,verification_source_before);
verification_hashes_after = local_verifier_hashes(project_root);
local_require(isequal(verification_hashes_before, ...
        verification_hashes_after), ...
    'A global-verification program changed during validation.');
global_manifest.verification_source.git_commit = ...
    verification_source_final.git_commit;
global_manifest.verification_source.git_status_available = ...
    verification_source_final.git_status_available;
global_manifest.verification_source.git_dirty = ...
    verification_source_final.git_dirty;
global_manifest.verification_source.source_unchanged_after_run = ...
    verification_source_final.source_unchanged_after_run;

local_require(strcmp(ver10_file_sha256(thin_manifest_path), ...
        snapshot.thin_manifest) ...
    && strcmp(ver10_file_sha256(compact_manifest_path), ...
        snapshot.compact_manifest) ...
    && strcmp(ver10_file_sha256(residual_manifest_path), ...
        snapshot.residual_manifest) ...
    && strcmp(ver10_file_sha256(spectral_atlas_path), ...
        snapshot.spectral_atlas), ...
    'A component manifest or spectral atlas changed during validation.');

if ~isempty(output_path)
    local_write_json(output_path,global_manifest);
end
end


function hashes = local_verifier_hashes(project_root)
hashes = struct( ...
    'rayleigh_global',ver10_file_sha256(fullfile( ...
        project_root,'scripts_run', ...
        'verify_upper_rayleigh_global_manifests.m')), ...
    'affine_residual',ver10_file_sha256(fullfile( ...
        project_root,'scripts_run', ...
        'verify_upper_conjecture_global_manifests.m')), ...
    'thin',ver10_file_sha256(fullfile( ...
        project_root,'src','degenerate', ...
        'validate_muhat1_rayleigh_certificate.m')), ...
    'runtime_snapshot',ver10_file_sha256(fullfile( ...
        project_root,'scripts_run','ver10_assert_runtime_snapshot.m')), ...
    'worker_runtime',ver10_file_sha256(fullfile( ...
        project_root,'scripts_run','ver10_assert_worker_runtime.m')), ...
    'persisted_worker_runtime',ver10_file_sha256(fullfile( ...
        project_root,'scripts_run', ...
        'ver10_validate_worker_runtime_record.m')));
end


function distribution = local_distribution_record(spectral_sha256)
repository = getenv('VER10_RELEASE_REPOSITORY');
release_tag = getenv('VER10_RELEASE_TAG');
local_require(~isempty(regexp(repository, ...
        '^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$','once')) ...
    && ~isempty(regexp(release_tag,'^[A-Za-z0-9_.-]+$','once')), ...
    ['VER10_RELEASE_REPOSITORY and VER10_RELEASE_TAG must identify the ', ...
     'immutable public distribution.']);
spectral_asset = 'omega_up_spectral_atlas_9x5.mat';
distribution = struct( ...
    'repository',repository, ...
    'release_tag',release_tag, ...
    'thin_manifest_repo_path', ...
        'results/paper_certificates/muhat1_rayleigh_t038_v2/manifest.json', ...
    'affine_manifest_repo_path',[ ...
        'results/paper_certificates/upper_affine_atlas/', ...
        'upper_manifest_interval_20260728_162102.json'], ...
    'residual_manifest_repo_path',[ ...
        'results/paper_certificates/omega_up_residual_v2/', ...
        'omega_up_all_manifest.json'], ...
    'global_manifest_repo_path',[ ...
        'results/paper_certificates/', ...
        'siudeja_upper_global_rayleigh_manifest.json'], ...
    'spectral_atlas_release_asset',struct( ...
        'name',spectral_asset, ...
        'sha256',spectral_sha256, ...
        'download_url',sprintf( ...
            'https://github.com/%s/releases/download/%s/%s', ...
            repository,release_tag,spectral_asset)));
end


function runtime = local_validate_legacy_runtime(record)
runtime = struct( ...
    'engine',local_text(record,'engine','affine runtime'), ...
    'engine_version',local_text( ...
        record,'engine_version','affine runtime'), ...
    'startintlab_sha256',local_sha256( ...
        record,'startintlab_sha256','affine runtime'), ...
    'intval_constructor_sha256',local_sha256( ...
        record,'intval_constructor_sha256','affine runtime'));
if isfield(record,'intlab_tree_sha256')
    runtime.intlab_tree_sha256 = local_sha256( ...
        record,'intlab_tree_sha256','affine runtime');
else
    runtime.intlab_tree_sha256 = '';
end
runtime.trust_boundary = [ ...
    'The affine v1 artifact predates whole-tree hashing; its clean source ', ...
    'commit, startintlab.m, intval.m, CSV hash, serialized margins, ', ...
    'strict signs, and geometric cover are checked.  The archived INTLAB ', ...
    'execution that produced those serialized margins remains trusted.'];
end


function spectral = local_validate_spectral_atlas( ...
        filename,expected_sha256,expected_commit, ...
        trusted_runtime,trusted_runtime_sha256)
local_require(isfile(filename),'The spectral-atlas MAT file is missing.');
before = ver10_file_sha256(filename);
local_require(strcmp(before,expected_sha256), ...
    'The spectral-atlas MAT hash disagrees with the residual manifest.');
payload = load(filename,'atlas');
after = ver10_file_sha256(filename);
local_require(strcmp(after,expected_sha256), ...
    'The spectral-atlas MAT file changed while it was loaded.');
local_require(isfield(payload,'atlas') ...
    && isstruct(payload.atlas) && isscalar(payload.atlas), ...
    'The spectral-atlas MAT file has no scalar atlas structure.');
value = payload.atlas;
local_require(strcmp(local_text(value,'schema','spectral atlas'), ...
    'lowerboundsineq.omega-up-spectral-cr-lg-atlas.v1'), ...
    'The spectral-atlas schema is unsupported.');
local_require(strcmp(local_text(value,'method','spectral atlas'), ...
    'nearest-anchor-affine-transport-of-LG-Ritz-CR-endpoints'), ...
    'The spectral-atlas method is unsupported.');
local_require(local_flag(value,'rigorous','spectral atlas'), ...
    'The spectral atlas is not rigorous.');
Nx = local_positive_integer(value,'Nx_anchor','spectral atlas');
Ny = local_positive_integer(value,'Ny_anchor','spectral atlas');
num_certificates = local_positive_integer( ...
    value,'num_certificates','spectral atlas');
local_require(Nx == 9 && Ny == 5 && num_certificates == Nx*Ny, ...
    'The spectral atlas is not the canonical 9-by-5 anchor grid.');
local_require(local_positive_integer(value,'N_LG','spectral atlas') == 16 ...
    && local_positive_integer(value,'N_rho','spectral atlas') == 64 ...
    && local_positive_integer(value,'bound_order','spectral atlas') == 2, ...
    'The spectral-atlas discretization is noncanonical.');
local_require(isfield(value,'certificates') ...
    && iscell(value.certificates) ...
    && isequal(size(value.certificates),[Ny,Nx]), ...
    'The spectral-atlas certificate array has the wrong shape.');
local_require(isfield(value,'x_anchors') && isnumeric(value.x_anchors) ...
    && isreal(value.x_anchors) && numel(value.x_anchors) == Nx ...
    && all(isfinite(value.x_anchors(:))) ...
    && all(diff(value.x_anchors(:)) > 0) ...
    && isfield(value,'y_anchors') && isnumeric(value.y_anchors) ...
    && isreal(value.y_anchors) && numel(value.y_anchors) == Ny ...
    && all(isfinite(value.y_anchors(:))) ...
    && all(diff(value.y_anchors(:)) > 0), ...
    'The spectral-atlas anchor vectors are invalid.');
for ix = 1:Nx
    for iy = 1:Ny
        certificate = value.certificates{iy,ix};
        local_validate_anchor_certificate( ...
            certificate,value.x_anchors(ix),value.y_anchors(iy), ...
            value.N_LG,value.N_rho,value.bound_order);
    end
end
[num_replayed,worker_runtime_validation] = local_replay_spectral_atlas( ...
    value,Nx,Ny,trusted_runtime,trusted_runtime_sha256);
source = local_struct(value,'source','spectral atlas');
local_require(strcmp(local_text(source,'git_commit','spectral source'), ...
        expected_commit) ...
    && local_flag(source,'git_status_available','spectral source') ...
    && ~local_flag(source,'git_dirty','spectral source') ...
    && local_flag(source,'source_unchanged_after_run','spectral source'), ...
    'The spectral atlas was not generated from the common clean source.');
spectral_runtime = local_struct(value,'runtime','spectral atlas');
spectral_runtime_sha256 = local_sha256_bytes( ...
    uint8(jsonencode(spectral_runtime)));
local_require(strcmp(local_sha256(value, ...
        'runtime_sha256','spectral atlas'),spectral_runtime_sha256) ...
    && local_flag(value,'runtime_rechecked_after_run','spectral atlas'), ...
    ['The spectral atlas does not bind a full runtime snapshot that was ', ...
     'rechecked after generation.']);
spectral_workers = local_number( ...
    value,'parallel_workers','spectral atlas');
local_require(spectral_workers >= 0 ...
    && spectral_workers == floor(spectral_workers) ...
    && spectral_workers <= 64, ...
    'The spectral-atlas worker count is invalid.');
ver10_validate_worker_runtime_record( ...
    local_struct(value,'worker_runtime_validation','spectral atlas'), ...
    spectral_runtime_sha256,spectral_workers, ...
    'spectral atlas worker runtime validation');

eps_up = I_intval('0.122');
x_left = I_intval('0.5');
x_right = x_left+2*eps_up;
y_top = sqrt(I_intval('3'))/2;
y_bottom = y_top-eps_up;
local_require(local_number(value,'x_domain_lower','spectral atlas') ...
        <= I_inf(x_left) ...
    && I_sup(x_right) <= local_number( ...
        value,'x_domain_upper','spectral atlas') ...
    && local_number(value,'y_domain_lower','spectral atlas') ...
        <= I_inf(y_bottom) ...
    && I_sup(y_top) <= local_number( ...
        value,'y_domain_upper','spectral atlas'), ...
    'The spectral atlas does not cover the canonical residual rectangle.');
spectral = struct( ...
    'num_certificates',num_certificates, ...
    'num_replayed',num_replayed, ...
    'worker_runtime_validation',worker_runtime_validation);
end


function [num_replayed,worker_runtime_validation] = ...
        local_replay_spectral_atlas( ...
            atlas,Nx,Ny,trusted_runtime,trusted_runtime_sha256)
project_root = fileparts(fileparts(mfilename('fullpath')));
workers = local_environment_nonnegative_integer( ...
    'VER10_SPECTRAL_REPLAY_WORKERS',0);
num_replayed = Nx*Ny;
replayed = cell(Ny,Nx);
before_workers = local_serial_worker_report( ...
    trusted_runtime_sha256,'global-spectral-replay-before-dispatch');
after_workers = local_serial_worker_report( ...
    trusted_runtime_sha256,'global-spectral-replay-after-dispatch');
if workers > 0
    pool = ver10_ensure_local_pool(workers);
    initialization = parfevalOnAll( ...
        pool,@omega_up_all_prepare_worker,0,project_root,'interval');
    wait(initialization);
    fetchOutputs(initialization);
    before_workers = ver10_assert_worker_runtime( ...
        pool,trusted_runtime,trusted_runtime_sha256, ...
        'global-spectral-replay-before-dispatch');
    parfor linear_index = 1:num_replayed
        [iy,ix] = ind2sub([Ny,Nx],linear_index);
        triangle = I_intval([ ...
            0,0,1,0,atlas.x_anchors(ix),atlas.y_anchors(iy)]);
        replayed{linear_index} = triangle_spectral_certificate_cr_lg( ...
            triangle,atlas.N_LG,atlas.N_rho,atlas.bound_order,1);
    end
    after_workers = ver10_assert_worker_runtime( ...
        pool,trusted_runtime,trusted_runtime_sha256, ...
        'global-spectral-replay-after-dispatch');
else
    for linear_index = 1:num_replayed
        [iy,ix] = ind2sub([Ny,Nx],linear_index);
        triangle = I_intval([ ...
            0,0,1,0,atlas.x_anchors(ix),atlas.y_anchors(iy)]);
        replayed{linear_index} = triangle_spectral_certificate_cr_lg( ...
            triangle,atlas.N_LG,atlas.N_rho,atlas.bound_order,1);
    end
end
for linear_index = 1:num_replayed
    stored = atlas.certificates{linear_index};
    current = replayed{linear_index};
    local_require(I_inf(stored.lambda_LG_lower) ...
            <= I_inf(current.lambda_LG_lower) ...
        && I_sup(current.lambda_Ritz_upper) ...
            <= I_sup(stored.lambda_Ritz_upper) ...
        && I_inf(stored.lambda_next_CR_lower) ...
            <= I_inf(current.lambda_next_CR_lower), ...
        ['A stored spectral endpoint is not conservative relative to ', ...
         'the independent interval replay.']);
end
worker_runtime_validation = struct( ...
    'policy','full-runtime-json-all-workers-before-and-after-dispatch-v1', ...
    'before_dispatch',before_workers, ...
    'after_dispatch',after_workers, ...
    'all_computation_workers_checked',true, ...
    'runtime_sha256',trusted_runtime_sha256);
end


function value = local_environment_nonnegative_integer(name,default_value)
text_value = getenv(name);
if isempty(text_value)
    value = default_value;
else
    value = str2double(text_value);
end
local_require(isfinite(value) && isscalar(value) ...
    && value >= 0 && value == floor(value) && value <= 64, ...
    [name,' must be an integer between 0 and 64.']);
end


function local_validate_anchor_certificate( ...
        certificate,x_anchor,y_anchor,N_LG,N_rho,bound_order)
context = 'spectral certificate';
local_require(isstruct(certificate) && isscalar(certificate), ...
    'A spectral anchor certificate is not a scalar structure.');
local_require(strcmp(local_text(certificate,'schema',context), ...
        'lowerboundsineq.triangle-spectral-cr-lg-certificate.v1') ...
    && strcmp(local_text(certificate,'method',context), ...
        'Lehmann-Goerisch+conforming-Ritz+CR-Liu') ...
    && local_positive_integer(certificate,'index',context) == 1 ...
    && local_positive_integer(certificate,'N_LG',context) == N_LG ...
    && local_positive_integer(certificate,'N_rho',context) == N_rho ...
    && local_positive_integer(certificate,'bound_order',context) ...
        == bound_order ...
    && local_flag(certificate,'rigorous',context) ...
    && local_flag(certificate,'mesh_used',context), ...
    'A spectral anchor certificate has noncanonical metadata.');
local_require(isfield(certificate,'reference_triangle') ...
    && numel(certificate.reference_triangle) == 6, ...
    'A spectral anchor certificate has no reference triangle.');
triangle = certificate.reference_triangle(:).';
expected = [0,0,1,0,x_anchor,y_anchor];
for k = 1:6
    local_require(I_inf(triangle(k)) == expected(k) ...
        && I_sup(triangle(k)) == expected(k), ...
        'A spectral certificate is attached to the wrong anchor.');
end
required = {'lambda_LG_lower','lambda_Ritz_upper', ...
    'lambda_next_CR_lower','lambda1_LG_lower', ...
    'lambda1_Ritz_upper','lambda2_CR_lower'};
for k = 1:numel(required)
    local_require(isfield(certificate,required{k}) ...
        && isscalar(certificate.(required{k})), ...
        ['A spectral certificate is missing ',required{k},'.']);
end
lower = certificate.lambda_LG_lower;
upper = certificate.lambda_Ritz_upper;
next = certificate.lambda_next_CR_lower;
local_require(isfinite(I_inf(lower)) && I_inf(lower) > 0 ...
    && isfinite(I_sup(upper)) && I_inf(lower) <= I_sup(upper) ...
    && isfinite(I_inf(next)) && I_sup(upper) < I_inf(next), ...
    'A spectral certificate has invalid or unseparated endpoints.');
local_require(I_inf(certificate.lambda1_LG_lower) == I_inf(lower) ...
    && I_sup(certificate.lambda1_Ritz_upper) == I_sup(upper) ...
    && I_inf(certificate.lambda2_CR_lower) == I_inf(next), ...
    'A spectral certificate alias endpoint is inconsistent.');
end


function runtime = local_validate_matching_runtime(records)
first = records{1};
local_require(isstruct(first) && isscalar(first), ...
    'A component runtime record is not a scalar object.');
first_payload = jsonencode(first);
record_sha256 = local_sha256_bytes(uint8(first_payload));
tree_hash = local_sha256(first,'intlab_tree_sha256','runtime');
gmsh_hash = local_sha256(first,'gmsh_binary_sha256','runtime');
file_count = local_positive_integer( ...
    first,'intlab_tree_file_count','runtime');
total_bytes = local_positive_integer( ...
    first,'intlab_tree_total_bytes','runtime');
local_require(local_number(first,'gmsh_version_status','runtime') == 0, ...
    'A component runtime did not resolve a working Gmsh executable.');
for k = 2:numel(records)
    current = records{k};
    local_require(isstruct(current) && isscalar(current) ...
        && strcmp(jsonencode(current),first_payload) ...
        && strcmp(local_sha256(current, ...
            'intlab_tree_sha256','runtime'),tree_hash) ...
        && strcmp(local_sha256(current, ...
            'gmsh_binary_sha256','runtime'),gmsh_hash) ...
        && local_positive_integer(current, ...
            'intlab_tree_file_count','runtime') == file_count ...
        && local_positive_integer(current, ...
            'intlab_tree_total_bytes','runtime') == total_bytes, ...
        ['The new upper-bound components used different complete ', ...
         'runtime records.']);
end
runtime = first;
runtime.record_sha256 = record_sha256;
runtime.trust_boundary = [ ...
    'MATLAB, the byte-identical INTLAB tree, Gmsh, the operating ', ...
    'system, hardware, and SHA-256 are trusted dependencies'];
end


function value = local_read_json(filename,label)
local_require(isfile(filename),['Missing ',label,' manifest.']);
try
    value = jsondecode(fileread(filename));
catch ME
    error('verify_upper_rayleigh_global_manifests:InvalidCertificate', ...
        'Cannot parse the %s manifest: %s',label,ME.message);
end
local_require(isstruct(value) && isscalar(value), ...
    ['The ',label,' manifest root is not an object.']);
end


function local_write_json(filename,value)
directory = fileparts(filename);
if ~isempty(directory) && ~isfolder(directory)
    mkdir(directory);
end
fid = fopen(filename,'w');
if fid < 0
    error('verify_upper_rayleigh_global_manifests:CannotWrite', ...
        'Cannot open %s.',filename);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid,'%s\n',jsonencode(value,'PrettyPrint',true));
clear cleanup
end


function value = local_struct(parent,name,context)
local_require(isstruct(parent) && isscalar(parent) ...
    && isfield(parent,name) && isstruct(parent.(name)) ...
    && isscalar(parent.(name)),['Missing or invalid ',context,'.',name,'.']);
value = parent.(name);
end


function value = local_text(parent,name,context)
local_require(isstruct(parent) && isscalar(parent) ...
    && isfield(parent,name) ...
    && (ischar(parent.(name)) ...
        || (isstring(parent.(name)) && isscalar(parent.(name)))), ...
    ['Missing or invalid ',context,'.',name,'.']);
value = char(parent.(name));
end


function value = local_sha256(parent,name,context)
value = local_text(parent,name,context);
local_require(~isempty(regexp(value,'^[0-9a-f]{64}$','once')), ...
    ['Invalid SHA-256 field ',context,'.',name,'.']);
end


function value = local_number(parent,name,context)
local_require(isstruct(parent) && isscalar(parent) ...
    && isfield(parent,name) && isnumeric(parent.(name)) ...
    && isreal(parent.(name)) && isscalar(parent.(name)) ...
    && isfinite(double(parent.(name))), ...
    ['Missing or invalid ',context,'.',name,'.']);
value = double(parent.(name));
end


function value = local_positive_integer(parent,name,context)
value = local_number(parent,name,context);
local_require(value >= 1 && value == floor(value) && value <= flintmax, ...
    ['Invalid positive integer ',context,'.',name,'.']);
end


function value = local_flag(parent,name,context)
local_require(isstruct(parent) && isscalar(parent) ...
    && isfield(parent,name) && islogical(parent.(name)) ...
    && isscalar(parent.(name)), ...
    ['Missing or invalid ',context,'.',name,'.']);
value = logical(parent.(name));
end


function report = local_serial_worker_report(runtime_sha256,phase)
report = struct( ...
    'schema','lowerboundsineq.worker-runtime-validation.v1', ...
    'phase',phase, ...
    'runtime_sha256',runtime_sha256, ...
    'worker_count',0, ...
    'all_workers_returned',true, ...
    'all_workers_full_runtime_json_match',true);
end


function value = local_decimal_text_number(parent,name,context)
text_value = local_text(parent,name,context);
local_require(~isempty(regexp(text_value, ...
    '^[+-]?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[eE][+-]?[0-9]+)?$', ...
    'once')),'A decimal configuration field is malformed.');
value = str2double(text_value);
local_require(isfinite(value),'A decimal configuration field is nonfinite.');
end


function digest = local_sha256_bytes(bytes)
try
    engine = javaMethod( ...
        'getInstance','java.security.MessageDigest','SHA-256');
catch ME
    error('verify_upper_rayleigh_global_manifests:NoSHA256', ...
        'Cannot initialize SHA-256: %s',ME.message);
end
bytes = uint8(bytes(:));
if ~isempty(bytes)
    engine.update(typecast(bytes,'int8'));
end
raw = typecast(engine.digest(),'uint8');
digest = lower(reshape(dec2hex(raw,2).',1,[]));
end


function local_require(condition,message)
if ~(islogical(condition) || isnumeric(condition)) ...
        || ~isscalar(condition) || ~isfinite(double(condition)) ...
        || ~logical(condition)
    error('verify_upper_rayleigh_global_manifests:InvalidCertificate', ...
        '%s',message);
end
end
