function global_manifest = verify_upper_conjecture_global_manifests( ...
    compact_manifest_path,residual_manifest_path,output_path)
%VERIFY_UPPER_CONJECTURE_GLOBAL_MANIFESTS Join the two overlapping proofs.
%
% A JSON summary is not accepted on trust.  The compact and residual CSV
% files are hashed, parsed, and checked against their manifests before the
% global certificate is emitted.

rounding_cleanup = []; %#ok<NASGU>
if exist('getround','file') == 2 || exist('getround','file') == 3
    old_round = getround;
    setround(0);
    rounding_cleanup = onCleanup(@() setround(old_round)); %#ok<NASGU>
end
compact = jsondecode(fileread(compact_manifest_path));
residual = jsondecode(fileread(residual_manifest_path));

local_require(local_text_field(compact,'schema', ...
    'compact.schema'), ...
    'The compact manifest has no valid schema.');
local_require(strcmp(char(compact.schema), ...
    'lowerboundsineq.upper_conjecture.v1'), ...
    'Unsupported compact-atlas manifest schema.');
local_require(local_text_field(residual,'schema', ...
    'residual.schema'), ...
    'The residual manifest has no valid schema.');
local_require(strcmp(char(residual.schema), ...
    'lowerboundsineq.omega_up_all_residual.manifest.v2'), ...
    'Unsupported residual manifest schema.');

compact_stats = local_validate_compact_manifest( ...
    compact,compact_manifest_path);
residual_stats = local_validate_residual_manifest( ...
    residual,residual_manifest_path);

compact_source = local_struct_field(compact,'source','compact.source');
residual_source = local_struct_field(residual,'source','residual.source');
local_require(local_flag(compact_source, ...
    'source_unchanged_after_run','compact source unchanged') ...
    && local_flag(residual_source, ...
        'source_unchanged_after_run','residual source unchanged'), ...
    'A source tree changed during one of the computations.');
local_require(local_flag(compact_source, ...
    'git_status_available','compact Git status available') ...
    && local_flag(residual_source, ...
        'git_status_available','residual Git status available') ...
    && ~local_flag(compact_source,'git_dirty','compact Git dirty') ...
    && ~local_flag(residual_source,'git_dirty','residual Git dirty'), ...
    'A component was not computed from a clean Git checkout.');
compact_commit = local_text(compact_source,'git_commit', ...
    'compact source commit');
residual_commit = local_text(residual_source,'git_commit', ...
    'residual source commit');
local_require(~isempty(compact_commit) ...
    && strcmp(compact_commit,residual_commit), ...
    'The two components were not computed from the same Git commit.');

y_residual = residual_stats.y_start;
y_atlas = compact_stats.y_end;
local_require(y_residual < y_atlas, ...
    'The compact and residual certificates do not overlap.');
local_require(y_residual <= compact_stats.recorded_residual_start ...
    && compact_stats.recorded_residual_start < y_atlas, ...
    'The actual residual cover does not reach the recorded interface.');

global_manifest = struct();
global_manifest.schema = ...
    'lowerboundsineq.siudeja-upper-global.manifest.v1';
global_manifest.theorem = ...
    ['lambda1(T) <= pi^2*P(T)^2/(12*A(T)^2) ', ...
     '+sqrt(3)*pi^2/(3*A(T)) for every triangle T'];
global_manifest.rigor = 'certified_interval';
global_manifest.complete_certificate = true;
global_manifest.git_commit = compact_commit;
global_manifest.cover = struct( ...
    'thin_and_compact_y_end',y_atlas, ...
    'residual_y_start',y_residual, ...
    'overlap',[y_residual,y_atlas]);
global_manifest.margins = struct( ...
    'thin_scaled_lower',compact_stats.thin_margin, ...
    'compact_lower',compact_stats.compact_margin, ...
    'residual_JUP_upper',residual_stats.maximum_JUP_upper);
global_manifest.inputs = struct( ...
    'compact_manifest_sha256', ...
        ver10_file_sha256(compact_manifest_path), ...
    'residual_manifest_sha256', ...
        ver10_file_sha256(residual_manifest_path), ...
    'compact_csv_sha256',compact_stats.csv_sha256, ...
    'residual_csv_sha256',residual_stats.csv_sha256);
global_manifest.runtime = ver10_runtime_metadata();

if nargin >= 3 && ~isempty(output_path)
    fid = fopen(output_path,'w');
    if fid < 0
        error('verify_upper_conjecture_global_manifests:CannotWrite', ...
            'Cannot open %s.',output_path);
    end
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid,'%s\n',jsonencode(global_manifest,'PrettyPrint',true));
    clear cleanup
end
end


function stats = local_validate_compact_manifest(compact,manifest_path)
local_require(strcmp(local_text(compact,'rigor','compact rigor'), ...
    'certified_interval'), ...
    'The compact component is not an interval certificate.');
if isfield(compact,'mode')
    local_require(strcmp(local_text(compact,'mode','compact mode'), ...
        'interval'), ...
        'The compact component was not run in interval mode.');
end
local_require(local_flag(compact,'component_complete_certificate', ...
    'compact complete flag'), ...
    'The compact upper component is incomplete.');

thin = local_struct_field(compact,'thin','compact.thin');
atlas = local_struct_field(compact,'atlas','compact.atlas');
connection = local_struct_field( ...
    compact,'connection','compact.connection');
files = local_struct_field(compact,'files','compact.files');
hashes = local_struct_field(compact,'hashes','compact.hashes');

thin_y_min = local_number(thin,'y_min','thin.y_min');
thin_y_max = local_number(thin,'y_max','thin.y_max');
atlas_y_min = local_number(atlas,'y_min','atlas.y_min');
atlas_y_end = local_number(atlas,'y_up','atlas.y_up');
local_require(thin_y_min == 0 && thin_y_max == atlas_y_min, ...
    'The thin and compact components do not meet at the same endpoint.');
local_require(0 < atlas_y_min && atlas_y_min < atlas_y_end ...
    && atlas_y_end < 1, ...
    'The compact y-range is invalid.');
local_require(local_flag(thin,'verified','thin verified flag'), ...
    'The thin-sector certificate is incomplete.');
thin_margin = local_number( ...
    thin,'scaled_margin_lower','thin scaled margin');
local_require(thin_margin > 0, ...
    'The thin-sector margin is not strictly positive.');

local_require(local_flag(atlas,'cover_generation_complete', ...
    'compact cover complete flag') ...
    && local_flag(atlas,'all_verified', ...
        'compact all-verified flag'), ...
    'The compact atlas is not a complete verified cover.');
number_of_cells = local_positive_integer( ...
    atlas,'number_of_cells','compact number of cells');
number_verified = local_nonnegative_integer( ...
    atlas,'number_verified','compact verified count');
local_require(number_verified == number_of_cells, ...
    'The compact verified-cell count is incomplete.');
compact_margin = local_number( ...
    atlas,'minimum_margin_lower','compact minimum margin');
local_require(compact_margin > 0, ...
    'The compact-atlas margin is not strictly positive.');
atlas_x_min = local_number(atlas,'x_min','compact x minimum');
local_require(atlas_x_min == 0.5, ...
    'The compact atlas does not start on the symmetry axis.');

recorded_y_end = local_number( ...
    connection,'atlas_y_end','recorded compact endpoint');
recorded_residual_start = local_number( ...
    connection,'residual_y_start','recorded residual interface');
local_require(recorded_y_end == atlas_y_end ...
    && recorded_residual_start < atlas_y_end, ...
    'The compact connection metadata is inconsistent.');

csv_path = local_resolve_sibling( ...
    manifest_path,local_text(files,'cells_csv','compact CSV path'));
recorded_hash = local_text(hashes,'cells_csv','compact CSV hash');
actual_hash = ver10_file_sha256(csv_path);
local_require(strcmp(actual_hash,recorded_hash), ...
    'The compact-atlas CSV hash does not match its manifest.');
table_value = local_read_csv(csv_path,'compact');
required = {'cell_id','rigor','verified','x_lo','x_hi', ...
    'y_lo','y_hi','margin_lower'};
local_require_table_columns(table_value,required,'compact');

cell_id = local_numeric_column(table_value,'cell_id','compact');
rigor = local_text_column(table_value,'rigor','compact');
verified = local_binary_column(table_value,'verified','compact');
x_lo = local_finite_column(table_value,'x_lo','compact');
x_hi = local_finite_column(table_value,'x_hi','compact');
y_lo = local_finite_column(table_value,'y_lo','compact');
y_hi = local_finite_column(table_value,'y_hi','compact');
margin = local_finite_column(table_value,'margin_lower','compact');
n = height(table_value);
local_require(n == number_of_cells ...
    && isequal(cell_id(:),(1:n).'), ...
    'The compact CSV does not contain exactly the recorded cell IDs.');
local_require(all(rigor == "certified_interval") ...
    && all(verified == 1) && all(margin > 0), ...
    'A compact CSV row is not rigorously verified with positive margin.');
local_require(min(margin) == compact_margin, ...
    'The compact CSV minimum margin disagrees with its manifest.');
local_require(all(0 < y_lo & y_lo < y_hi & y_hi < 1) ...
    && all(atlas_x_min <= x_lo & x_lo < x_hi & x_hi <= 1), ...
    'A compact CSV rectangle has invalid geometry.');

strip_start = [1;find(y_lo(2:end) ~= y_lo(1:end-1))+1];
strip_end = [strip_start(2:end)-1;n];
local_require(~isempty(strip_start), ...
    'The compact CSV has no y-strips.');
previous_y_hi = NaN;
for s = 1:numel(strip_start)
    indices = strip_start(s):strip_end(s);
    strip_y_lo = y_lo(indices(1));
    strip_y_hi = y_hi(indices(1));
    local_require(all(y_lo(indices) == strip_y_lo) ...
        && all(y_hi(indices) == strip_y_hi), ...
        'A compact y-strip has inconsistent y endpoints.');
    if s == 1
        local_require(strip_y_lo <= atlas_y_min ...
            && atlas_y_min <= strip_y_hi, ...
            'The compact CSV does not start at atlas.y_min.');
    else
        local_require(strip_y_lo <= previous_y_hi ...
            && strip_y_hi > previous_y_hi, ...
            'The compact y-strips are not contiguous and increasing.');
    end
    local_require(x_lo(indices(1)) == atlas_x_min, ...
        'A compact y-strip does not start at x=1/2.');
    for j = 1:(numel(indices)-1)
        local_require(x_lo(indices(j+1)) <= x_hi(indices(j)), ...
            'A compact y-strip has a gap between rectangles.');
    end
    required_x_end = sqrt(max(0,1-strip_y_lo^2));
    local_require(x_hi(indices(end)) >= required_x_end, ...
        'A compact y-strip does not reach the circular boundary.');
    previous_y_hi = strip_y_hi;
end
local_require(y_lo(strip_start(end)) <= atlas_y_end ...
    && atlas_y_end <= y_hi(strip_end(end)), ...
    'The compact CSV does not reach atlas.y_up.');

stats = struct( ...
    'y_end',atlas_y_end, ...
    'recorded_residual_start',recorded_residual_start, ...
    'thin_margin',thin_margin, ...
    'compact_margin',compact_margin, ...
    'csv_sha256',actual_hash);
end


function stats = local_validate_residual_manifest(residual,manifest_path)
local_require(strcmp(local_text(residual,'rigor','residual rigor'), ...
    'certified_interval'), ...
    'The residual component is not an interval certificate.');
if isfield(residual,'mode')
    local_require(strcmp(local_text(residual,'mode','residual mode'), ...
        'interval'), ...
        'The residual component was not run in interval mode.');
end

scope = local_struct_field( ...
    residual,'functional_scope','residual functional scope');
local_validate_split_scope(scope,'residual functional scope');
coverage = local_struct_field( ...
    residual,'domain_coverage','residual domain coverage');
config = local_struct_field(residual,'config','residual config');
summary = local_struct_field(residual,'summary','residual summary');
files = local_struct_field(residual,'files','residual.files');
hashes = local_struct_field(residual,'hashes','residual.hashes');

local_require(strcmp(local_text(config,'schema','residual config schema'), ...
    'lowerboundsineq.omega_up_all_residual.config.v3'), ...
    'Unsupported residual config schema.');
config_scope = local_struct_field( ...
    config,'functional_scope','residual config functional scope');
local_validate_split_scope(config_scope,'residual config functional scope');
local_require(local_number(config_scope,'JUP_y_min_lower', ...
    'config JUP lower threshold') ...
    == local_number(scope,'JUP_y_min_lower', ...
        'manifest JUP lower threshold') ...
    && local_number(config_scope,'JUP_y_min_upper', ...
        'config JUP upper threshold') ...
    == local_number(scope,'JUP_y_min_upper', ...
        'manifest JUP upper threshold'), ...
    'The residual scope metadata is duplicated inconsistently.');

Nx = local_positive_integer(config,'Nx','residual Nx');
Ny = local_positive_integer(config,'Ny','residual Ny');
Ny_axis = local_positive_integer(config,'Ny_axis','residual Ny_axis');
number_rectangles = Nx*Ny;
number_tasks = number_rectangles+Ny_axis;
local_require(isfinite(number_tasks) && number_tasks <= flintmax, ...
    'The residual grid task count is not representable exactly.');
local_require(local_positive_integer(config,'full_task_count', ...
    'residual full task count') == number_tasks ...
    && local_positive_integer(config,'selected_task_count', ...
        'residual selected task count') == number_tasks ...
    && local_flag(config,'coverage_complete', ...
        'residual config coverage complete'), ...
    'The residual config does not select the full grid.');
local_require(strcmp(local_text(config,'selection_mode', ...
    'residual selection mode'),'all'), ...
    'The residual run used a restricted task selection.');
if isfield(config,'selected_task_ids')
    local_require(isempty(config.selected_task_ids), ...
        'A full residual run must not record a task-ID subset.');
end

local_require(local_positive_integer(summary,'num_tasks', ...
    'residual summary task count') == number_tasks ...
    && local_nonnegative_integer(summary,'num_rectangles', ...
        'residual rectangle count') == number_rectangles ...
    && local_nonnegative_integer(summary,'num_axis_intervals', ...
        'residual axis count') == Ny_axis, ...
    'The residual rectangle/axis counts disagree with the grid.');
local_require(local_nonnegative_integer(summary,'num_unique_task_ids', ...
    'residual unique-ID count') == number_tasks ...
    && local_nonnegative_integer(summary,'num_missing_task_ids', ...
        'residual missing-ID count') == 0 ...
    && local_nonnegative_integer(summary,'num_unexpected_task_ids', ...
        'residual unexpected-ID count') == 0 ...
    && local_nonnegative_integer(summary,'num_duplicate_task_ids', ...
        'residual duplicate-ID count') == 0 ...
    && local_flag(summary,'exact_full_task_id_coverage', ...
        'residual exact full-ID flag') ...
    && local_flag(summary,'coverage_complete', ...
        'residual summary coverage complete'), ...
    'The residual manifest does not certify exact task IDs.');
local_require(local_nonnegative_integer(summary,'num_errors', ...
    'residual error count') == 0 ...
    && local_flag(summary,'JUP_complete_certificate', ...
        'residual JUP complete flag'), ...
    'The residual JUP component is not a complete interval certificate.');

y_start = local_validate_residual_coverage(coverage);
local_require(local_flag(summary,'canonical_ver10_omega_up_covered', ...
    'residual summary canonical coverage') ...
    && local_flag(summary,'JUP_requested_band_covered', ...
        'residual summary JUP coverage') ...
    && local_number(summary,'JUP_certified_y_start_upper', ...
        'residual summary JUP start') == y_start, ...
    'The residual coverage summary disagrees with domain_coverage.');
config_coverage = local_struct_field( ...
    config,'domain_coverage','residual config domain coverage');
local_compare_coverage(coverage,config_coverage);

csv_path = local_resolve_sibling( ...
    manifest_path,local_text(files,'csv','residual CSV path'));
recorded_hash = local_text(hashes,'csv','residual CSV hash');
actual_hash = ver10_file_sha256(csv_path);
local_require(strcmp(actual_hash,recorded_hash), ...
    'The residual CSV hash does not match its manifest.');
table_value = local_read_csv(csv_path,'residual');
required = {'task_id','kind','ix','iy','x_lo','x_hi','y_lo','y_hi', ...
    'domain_applicable','computed','rigorous', ...
    'J1_in_scope','J2_in_scope','JUP_in_scope', ...
    'num_scoped_functionals','JUP_upper','JUP_certified', ...
    'residual_gap_lower','eigenfunction_strong_residual_upper', ...
    'material_strong_residual_upper','status'};
local_require_table_columns(table_value,required,'residual');
local_require(height(table_value) == number_tasks, ...
    'The residual CSV row count disagrees with the full grid.');

task_id = local_numeric_column(table_value,'task_id','residual');
kind = local_text_column(table_value,'kind','residual');
ix = local_numeric_column(table_value,'ix','residual');
iy = local_numeric_column(table_value,'iy','residual');
x_lo = local_finite_column(table_value,'x_lo','residual');
x_hi = local_finite_column(table_value,'x_hi','residual');
y_lo = local_finite_column(table_value,'y_lo','residual');
y_hi = local_finite_column(table_value,'y_hi','residual');
domain_applicable = local_binary_column( ...
    table_value,'domain_applicable','residual');
computed = local_binary_column(table_value,'computed','residual');
rigorous = local_binary_column(table_value,'rigorous','residual');
J1_scope = local_binary_column(table_value,'J1_in_scope','residual');
J2_scope = local_binary_column(table_value,'J2_in_scope','residual');
JUP_scope = local_binary_column(table_value,'JUP_in_scope','residual');
num_scoped = local_numeric_column( ...
    table_value,'num_scoped_functionals','residual');
JUP_upper = local_numeric_column(table_value,'JUP_upper','residual');
JUP_certified = local_binary_column( ...
    table_value,'JUP_certified','residual');
residual_gap = local_numeric_column( ...
    table_value,'residual_gap_lower','residual');
eigenfunction_residual = local_numeric_column( ...
    table_value,'eigenfunction_strong_residual_upper','residual');
material_residual = local_numeric_column( ...
    table_value,'material_strong_residual_upper','residual');

local_require(isequal(task_id(:),(1:number_tasks).'), ...
    'The residual CSV does not contain exact task IDs 1:N.');
local_require(all(rigorous == 1), ...
    'A residual CSV row is not rigorous.');
expected_rect_ix = repelem((1:Nx).',Ny);
expected_rect_iy = repmat((1:Ny).',Nx,1);
rect = (1:number_rectangles).';
axis = (number_rectangles+1:number_tasks).';
local_require(all(kind(rect) == "rectangle") ...
    && isequal(ix(rect),expected_rect_ix) ...
    && isequal(iy(rect),expected_rect_iy), ...
    'The residual rectangle IDs or grid indices are inconsistent.');
local_require(all(kind(axis) == "axis") ...
    && all(ix(axis) == 0) ...
    && isequal(iy(axis),(1:Ny_axis).'), ...
    'The residual axis IDs or grid indices are inconsistent.');
local_require(all(x_lo(rect) < x_hi(rect)) ...
    && all(y_lo(rect) < y_hi(rect)) ...
    && all(x_lo(axis) <= 0.5 & 0.5 <= x_hi(axis)) ...
    && all(y_lo(axis) < y_hi(axis)), ...
    'A residual CSV cell has invalid geometry.');

rect_x_lo = reshape(x_lo(rect),Ny,Nx);
rect_x_hi = reshape(x_hi(rect),Ny,Nx);
rect_y_lo = reshape(y_lo(rect),Ny,Nx);
rect_y_hi = reshape(y_hi(rect),Ny,Nx);
local_require(all(all(rect_x_lo == rect_x_lo(1,:))) ...
    && all(all(rect_x_hi == rect_x_hi(1,:))) ...
    && all(all(rect_y_lo == rect_y_lo(:,1))) ...
    && all(all(rect_y_hi == rect_y_hi(:,1))), ...
    'Residual rectangles do not form a tensor grid.');
for k = 1:(Nx-1)
    local_require(rect_x_lo(1,k+1) <= rect_x_hi(1,k), ...
        'The residual rectangle grid has an x-gap.');
end
for k = 1:(Ny-1)
    local_require(rect_y_hi(k+1,1) >= rect_y_lo(k,1), ...
        'The residual rectangle grid has a y-gap.');
end
for k = 1:(Ny_axis-1)
    local_require(y_hi(axis(k+1)) >= y_lo(axis(k)), ...
        'The residual axis grid has a y-gap.');
end

canonical_x_left = 0.5;
canonical_x_right = 0.5+2*0.122;
canonical_y_top = sqrt(3)/2;
canonical_y_bottom = canonical_y_top-0.122;
local_require(rect_x_lo(1,1) <= canonical_x_left ...
    && rect_x_hi(1,end) >= canonical_x_right ...
    && rect_y_hi(1,1) >= canonical_y_top ...
    && rect_y_lo(end,1) <= canonical_y_bottom ...
    && y_hi(axis(1)) >= canonical_y_top ...
    && y_lo(axis(end)) <= canonical_y_bottom, ...
    'The residual CSV does not cover the canonical Omega_up bounds.');
local_require(min(x_lo(rect)) == local_number(coverage, ...
    'grid_x_left_lower','coverage grid x-left lower') ...
    && max(x_hi(rect)) == local_number(coverage, ...
        'grid_x_right_upper','coverage grid x-right upper') ...
    && min(y_lo(rect)) == local_number(coverage, ...
        'grid_y_bottom_lower','coverage grid y-bottom lower') ...
    && max(y_hi(rect)) == local_number(coverage, ...
        'grid_y_top_upper','coverage grid y-top upper') ...
    && min(y_lo(axis)) == local_number(coverage, ...
        'axis_y_bottom_lower','coverage axis y-bottom lower') ...
    && max(y_hi(axis)) == local_number(coverage, ...
        'axis_y_top_upper','coverage axis y-top upper'), ...
    'The residual CSV endpoints disagree with domain_coverage.');

jup_threshold = local_number( ...
    scope,'JUP_y_min_lower','residual JUP threshold');
expected_JUP_scope = y_hi >= jup_threshold;
local_require(all(J1_scope == 1) && all(J2_scope == 1) ...
    && isequal(logical(JUP_scope),expected_JUP_scope) ...
    && isequal(num_scoped,2+double(expected_JUP_scope)), ...
    'The residual CSV scope does not implement functional_scope=split.');
rect_JUP_start = min(y_lo(rect(expected_JUP_scope(rect))));
axis_JUP_start = min(y_lo(axis(expected_JUP_scope(axis))));
local_require(rect_JUP_start == local_number(coverage, ...
    'JUP_rectangle_y_start','coverage rectangle JUP start') ...
    && axis_JUP_start == local_number(coverage, ...
        'JUP_axis_y_start','coverage axis JUP start') ...
    && max(rect_JUP_start,axis_JUP_start) == y_start, ...
    'The residual CSV JUP band disagrees with domain_coverage.');
required_JUP = logical(domain_applicable) & expected_JUP_scope;
local_require(any(required_JUP) ...
    && all(computed(required_JUP) == 1) ...
    && all(JUP_certified(required_JUP) == 1) ...
    && all(isfinite(JUP_upper(required_JUP))) ...
    && all(isfinite(residual_gap(required_JUP))) ...
    && all(residual_gap(required_JUP) > 0) ...
    && all(isfinite(eigenfunction_residual(required_JUP))) ...
    && all(eigenfunction_residual(required_JUP) >= 0) ...
    && all(isfinite(material_residual(required_JUP))) ...
    && all(material_residual(required_JUP) >= 0) ...
    && all(JUP_upper(required_JUP) < 0), ...
    'A required residual JUP row is not rigorously certified.');
maximum_JUP_upper = max(JUP_upper(required_JUP));
local_require(local_nonnegative_integer(summary,'num_JUP_required', ...
    'residual required JUP count') == sum(required_JUP) ...
    && local_nonnegative_integer(summary,'num_JUP_certified', ...
        'residual certified JUP count') == sum(required_JUP) ...
    && local_number(summary,'maximum_JUP_upper', ...
        'residual maximum JUP') == maximum_JUP_upper, ...
    'The residual CSV JUP summary disagrees with its manifest.');

stats = struct( ...
    'y_start',y_start, ...
    'maximum_JUP_upper',maximum_JUP_upper, ...
    'csv_sha256',actual_hash);
end


function y_start = local_validate_residual_coverage(coverage)
local_require(strcmp(local_text(coverage,'schema', ...
    'residual coverage schema'), ...
    'lowerboundsineq.omega-up-residual-domain-coverage.v1'), ...
    'Unsupported residual domain-coverage schema.');
local_require(local_flag(coverage,'canonical_ver10_omega_up_covered', ...
    'canonical Omega_up coverage') ...
    && local_flag(coverage,'JUP_requested_band_covered', ...
        'requested JUP-band coverage'), ...
    'The residual manifest does not certify the actual ver10 domain.');

canonical_eps = 0.122;
canonical_x_left = 0.5;
canonical_x_right = canonical_x_left+2*canonical_eps;
canonical_y_top = sqrt(3)/2;
canonical_y_bottom = canonical_y_top-canonical_eps;
local_require(local_number(coverage,'canonical_eps_up', ...
    'canonical eps_up') == canonical_eps, ...
    'The residual coverage uses a noncanonical eps_up.');
local_require(local_pair_contains(coverage, ...
        'canonical_x_right_lower','canonical_x_right_upper', ...
        canonical_x_right,'canonical x-right') ...
    && local_pair_contains(coverage, ...
        'canonical_y_bottom_lower','canonical_y_bottom_upper', ...
        canonical_y_bottom,'canonical y-bottom') ...
    && local_pair_contains(coverage, ...
        'grid_x_left_lower','grid_x_left_upper', ...
        canonical_x_left,'grid x-left') ...
    && local_pair_contains(coverage, ...
        'grid_x_right_lower','grid_x_right_upper', ...
        canonical_x_right,'grid x-right') ...
    && local_pair_contains(coverage, ...
        'grid_y_bottom_lower','grid_y_bottom_upper', ...
        canonical_y_bottom,'grid y-bottom') ...
    && local_pair_contains(coverage, ...
        'grid_y_top_lower','grid_y_top_upper', ...
        canonical_y_top,'grid y-top') ...
    && local_pair_contains(coverage, ...
        'axis_y_bottom_lower','axis_y_bottom_upper', ...
        canonical_y_bottom,'axis y-bottom') ...
    && local_pair_contains(coverage, ...
        'axis_y_top_lower','axis_y_top_upper', ...
        canonical_y_top,'axis y-top'), ...
    'The residual endpoint fields do not contain the canonical domain.');

rect_start = local_number(coverage,'JUP_rectangle_y_start', ...
    'JUP rectangle start');
axis_start = local_number(coverage,'JUP_axis_y_start', ...
    'JUP axis start');
y_start = local_number(coverage,'JUP_certified_y_start_upper', ...
    'JUP certified start');
local_require(y_start == max(rect_start,axis_start) ...
    && y_start <= 0.85, ...
    'The residual JUP band does not reach y=0.85.');
end


function local_compare_coverage(first,second)
numeric_fields = { ...
    'grid_x_left_lower','grid_x_left_upper', ...
    'grid_x_right_lower','grid_x_right_upper', ...
    'grid_y_bottom_lower','grid_y_bottom_upper', ...
    'grid_y_top_lower','grid_y_top_upper', ...
    'axis_y_bottom_lower','axis_y_bottom_upper', ...
    'axis_y_top_lower','axis_y_top_upper', ...
    'canonical_eps_up','canonical_x_right_lower', ...
    'canonical_x_right_upper','canonical_y_bottom_lower', ...
    'canonical_y_bottom_upper','JUP_rectangle_y_start', ...
    'JUP_axis_y_start','JUP_certified_y_start_upper'};
for k = 1:numel(numeric_fields)
    name = numeric_fields{k};
    local_require(local_number(first,name,['coverage.',name]) ...
        == local_number(second,name,['config coverage.',name]), ...
        'The duplicated residual domain_coverage fields disagree.');
end
flag_fields = {'canonical_ver10_omega_up_covered', ...
    'JUP_requested_band_covered'};
for k = 1:numel(flag_fields)
    name = flag_fields{k};
    local_require(local_flag(first,name,['coverage.',name]) ...
        == local_flag(second,name,['config coverage.',name]), ...
        'The duplicated residual domain_coverage flags disagree.');
end
end


function local_validate_split_scope(scope,label)
local_require(strcmp(local_text(scope,'name',[label,' name']),'split'), ...
    'The residual functional scope must be ''split''.');
local_require(local_flag(scope,'J1_requested',[label,' J1 requested']) ...
    && local_flag(scope,'J2_requested',[label,' J2 requested']) ...
    && local_flag(scope,'JUP_requested',[label,' JUP requested']), ...
    'The split residual scope must request J1, J2, and JUP.');
lower = local_number(scope,'JUP_y_min_lower',[label,' JUP lower']);
upper = local_number(scope,'JUP_y_min_upper',[label,' JUP upper']);
local_require(lower <= 0.85 && 0.85 <= upper, ...
    'The split residual JUP threshold does not enclose y=0.85.');
end


function tf = local_pair_contains(s,lower_name,upper_name,value,label)
lower = local_number(s,lower_name,[label,' lower']);
upper = local_number(s,upper_name,[label,' upper']);
local_require(lower <= upper, ...
    [label,' endpoint pair is reversed.']);
tf = lower <= value && value <= upper;
end


function table_value = local_read_csv(filename,label)
try
    table_value = readtable(filename,'TextType','string');
catch ME
    error('verify_upper_conjecture_global_manifests:InvalidCertificate', ...
        'Cannot parse the %s CSV: %s',label,ME.message);
end
local_require(istable(table_value), ...
    ['The ',label,' CSV did not parse as a table.']);
end


function local_require_table_columns(table_value,names,label)
available = table_value.Properties.VariableNames;
for k = 1:numel(names)
    local_require(any(strcmp(available,names{k})), ...
        sprintf('The %s CSV is missing column %s.',label,names{k}));
end
end


function values = local_numeric_column(table_value,name,label)
values = table_value.(name);
local_require((isnumeric(values) || islogical(values)) ...
    && isvector(values) && numel(values) == height(table_value), ...
    sprintf('The %s CSV column %s is not numeric.',label,name));
values = double(values(:));
end


function values = local_finite_column(table_value,name,label)
values = local_numeric_column(table_value,name,label);
local_require(all(isfinite(values)), ...
    sprintf('The %s CSV column %s is nonfinite.',label,name));
end


function values = local_binary_column(table_value,name,label)
values = local_finite_column(table_value,name,label);
local_require(all(values == 0 | values == 1), ...
    sprintf('The %s CSV column %s is not binary.',label,name));
end


function values = local_text_column(table_value,name,label)
values = table_value.(name);
try
    values = string(values(:));
catch
    local_require(false, ...
        sprintf('The %s CSV column %s is not textual.',label,name));
end
local_require(numel(values) == height(table_value) ...
    && ~any(ismissing(values)), ...
    sprintf('The %s CSV column %s is not complete.',label,name));
end


function value = local_struct_field(s,name,label)
local_require(isstruct(s) && isscalar(s) && isfield(s,name) ...
    && isstruct(s.(name)) && isscalar(s.(name)), ...
    ['Missing or invalid ',label,'.']);
value = s.(name);
end


function value = local_number(s,name,label)
local_require(isstruct(s) && isscalar(s) && isfield(s,name) ...
    && isnumeric(s.(name)) && isscalar(s.(name)) ...
    && isfinite(double(s.(name))), ...
    ['Missing or invalid ',label,'.']);
value = double(s.(name));
end


function value = local_positive_integer(s,name,label)
value = local_number(s,name,label);
local_require(value >= 1 && value == floor(value), ...
    [label,' is not a positive integer.']);
end


function value = local_nonnegative_integer(s,name,label)
value = local_number(s,name,label);
local_require(value >= 0 && value == floor(value), ...
    [label,' is not a nonnegative integer.']);
end


function value = local_flag(s,name,label)
local_require(isstruct(s) && isscalar(s) && isfield(s,name) ...
    && (islogical(s.(name)) || isnumeric(s.(name))) ...
    && isscalar(s.(name)) && isfinite(double(s.(name))) ...
    && any(double(s.(name)) == [0,1]), ...
    ['Missing or invalid ',label,'.']);
value = logical(s.(name));
end


function value = local_text(s,name,label)
local_require(local_text_field(s,name,label), ...
    ['Missing or invalid ',label,'.']);
value = char(s.(name));
end


function tf = local_text_field(s,name,~)
tf = isstruct(s) && isscalar(s) && isfield(s,name) ...
    && (ischar(s.(name)) ...
        || (isstring(s.(name)) && isscalar(s.(name))));
end


function filename = local_resolve_sibling(manifest_path,recorded_path)
recorded_path = char(recorded_path);
if isfile(recorded_path)
    filename = recorded_path;
    return;
end
[manifest_directory,~,~] = fileparts(manifest_path);
[~,name,extension] = fileparts(recorded_path);
filename = fullfile(manifest_directory,[name,extension]);
if ~isfile(filename)
    error('verify_upper_conjecture_global_manifests:MissingInput', ...
        'Cannot resolve manifest input %s.',recorded_path);
end
end


function local_require(condition,message)
if ~(islogical(condition) || isnumeric(condition)) ...
        || ~isscalar(condition) || ~isfinite(double(condition)) ...
        || ~logical(condition)
    error('verify_upper_conjecture_global_manifests:InvalidCertificate', ...
        '%s',message);
end
end
