function report = validate_muhat1_rayleigh_certificate(manifest_path,varargin)
%VALIDATE_MUHAT1_RAYLEIGH_CERTIFICATE Fail-closed thin-proof replay.
%
% The validator does not trust booleans or extrema in the manifest.  It
% verifies all SHA-256 bindings, decodes the frozen trials losslessly,
% recomputes every interval Rayleigh quotient and every (s,r)-cell bound,
% and compares directed endpoints bit for bit with the serialized proof.

project_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(project_root,'src','degenerate'));
addpath(fullfile(project_root,'scripts_run'));
global INTERVAL_MODE
if isempty(INTERVAL_MODE) || ~logical(INTERVAL_MODE) ...
        || exist('intval','file') ~= 2
    omega_up_all_prepare_worker(project_root,'interval');
end

p = inputParser;
addParameter(p,'require_complete_certificate',true, ...
    @(x) islogical(x) && isscalar(x));
addParameter(p,'allow_pending_self_validation',false, ...
    @(x) islogical(x) && isscalar(x));
parse(p,varargin{:});
opt = p.Results;

manifest_path = char(manifest_path);
local_require(isfile(manifest_path),'The manifest file does not exist.');
manifest = jsondecode(fileread(manifest_path));
local_require(isstruct(manifest),'The manifest root must be an object.');
local_require(strcmp(local_text(manifest,'schema','manifest'), ...
    'lowerboundsineq.muhat1-rayleigh.manifest.v2'), ...
    'Unsupported thin-certificate schema.');
local_require(strcmp(local_text(manifest,'rigor','manifest'), ...
    'certified_interval_replay'), ...
    'Only an interval-replay artifact can be validated as a proof.');

config = local_struct(manifest,'config','manifest');
mode = local_text(config,'mode','config');
t_text = local_decimal(config,'t_text','config');
degree = local_integer(config,'degree','config');
n_s = local_integer(config,'s_cells','config');
s_lo_text = local_decimal(config,'s_lo_text','config');
s_hi_text = local_decimal(config,'s_hi_text','config');
y_max_text = local_decimal(config,'down_y_max_text','config');
n_r = local_integer(config,'down_y_cells','config');
local_require(strcmp(mode,'interval'),'The replay mode must be interval.');
local_require(str2double(t_text) > 0,'t must be positive.');
local_require(degree >= 2,'The polynomial degree is too small.');
local_require(n_s >= 1 && n_r >= 1,'Cell counts must be positive.');
local_require(str2double(s_lo_text) >= 0 ...
    && str2double(s_hi_text) <= 1 ...
    && str2double(s_lo_text) < str2double(s_hi_text), ...
    'The s-domain is invalid.');
local_require(str2double(y_max_text) > 0, ...
    'The thin-sector y endpoint must be positive.');
local_require(strcmp(local_text(config,'s_partition','config'), ...
    'uniform exact-rational index partition'), ...
    'The s-partition construction is not the certified construction.');
local_require(strcmp(local_text(config,'r_partition','config'), [ ...
    'uniform binary64 partition through an outward upper endpoint ', ...
    'of the exact interval power down_y_max^(1/3)']), ...
    'The r-partition construction is not the certified construction.');

files = local_struct(manifest,'files','manifest');
expected_files = struct( ...
    'manifest_json','manifest.json', ...
    'coefficients_csv','frozen_coefficients.csv', ...
    'cells_csv','cells.csv', ...
    'down_cells_csv','down_cells.csv', ...
    'checksums_sha256','checksums.sha256');
file_fields = fieldnames(expected_files);
artifact_dir = fileparts(local_canonical_path(manifest_path));
paths = struct();
for k = 1:numel(file_fields)
    key = file_fields{k};
    recorded = local_text(files,key,'files');
    local_require(strcmp(recorded,expected_files.(key)), ...
        ['Unexpected artifact filename for ',key,'.']);
    paths.(key) = local_resolve_sibling(artifact_dir,recorded);
end
local_require(strcmp(local_canonical_path(paths.manifest_json), ...
    local_canonical_path(manifest_path)), ...
    'The supplied manifest is not the artifact manifest.json.');

hashes = local_struct(manifest,'hashes','manifest');
local_require(strcmp(local_text(hashes,'algorithm','hashes'),'SHA-256'), ...
    'The artifact hash algorithm must be SHA-256.');
recorded_hashes = struct( ...
    'coefficients_csv',local_sha256(hashes,'coefficients_csv','hashes'), ...
    'cells_csv',local_sha256(hashes,'cells_csv','hashes'), ...
    'down_cells_csv',local_sha256(hashes,'down_cells_csv','hashes'));
local_verify_artifact_hashes(paths,recorded_hashes);
local_verify_checksums(paths,recorded_hashes);

source_files = local_struct(manifest,'source_files','manifest');
current_source_hashes = local_verify_source_files( ...
    project_root,source_files);
source = local_struct(manifest,'source','manifest');
local_validate_source_record(source,opt.require_complete_certificate);

recorded_runtime = local_struct(manifest,'runtime','manifest');
recorded_runtime_payload = jsonencode(recorded_runtime);
recorded_runtime_sha256 = local_sha256_bytes( ...
    uint8(recorded_runtime_payload));
local_require(local_flag(manifest, ...
        'runtime_rechecked_after_run','manifest') ...
    && strcmp(local_sha256(manifest,'runtime_sha256','manifest'), ...
        recorded_runtime_sha256), ...
    ['The thin artifact does not bind a runtime snapshot that was ', ...
     'rechecked after generation.']);
validation_runtime_before = ver10_runtime_metadata();
validation_runtime_before_payload = jsonencode(validation_runtime_before);
validation_runtime_before_sha256 = local_sha256_bytes( ...
    uint8(validation_runtime_before_payload));
local_compare_runtime(recorded_runtime,validation_runtime_before);
local_require(strcmp(recorded_runtime_payload, ...
        validation_runtime_before_payload) ...
    && strcmp(recorded_runtime_sha256, ...
        validation_runtime_before_sha256), ...
    'The replay runtime does not exactly match the recorded runtime.');

profile = local_struct(manifest,'profile','manifest');
production_requested = local_flag( ...
    profile,'production_requested','profile');
if production_requested
    local_validate_source_record(source,true);
end
recorded_profile_match = local_flag( ...
    profile,'production_parameters_match','profile');
production_parameters_match = strcmp(mode,'interval') ...
    && strcmp(t_text,'0.38') ...
    && degree == 10 ...
    && n_s == 200 ...
    && strcmp(s_lo_text,'0') ...
    && strcmp(s_hi_text,'1') ...
    && strcmp(y_max_text,'0.19') ...
    && n_r == 40;
local_require(recorded_profile_match == production_parameters_match, ...
    'The recorded production-profile flag is inconsistent.');

proof = local_struct(manifest,'proof_representation','manifest');
local_require(local_flag(proof, ...
    'exact_rational_interval_exponents','proof_representation'), ...
    'The artifact does not require exact rational interval exponents.');
local_require(local_flag(proof, ...
    'decimal_parameters_enter_intlab_as_text','proof_representation'), ...
    'The artifact does not preserve decimal input endpoints.');
local_require(local_flag(proof, ...
    'replay_does_not_recompute_eigenvectors','proof_representation'), ...
    'The artifact is not a frozen-trial replay.');
local_require(local_flag(proof, ...
    'decimal_extrema_are_display_only','proof_representation'), ...
    'Decimal proof endpoints must not be treated as authoritative.');
local_require(strcmp(local_text(proof, ...
    'frozen_coefficient_encoding','proof_representation'), ...
    'IEEE-754 binary64 hex via num2hex'), ...
    'The frozen coefficient encoding is not lossless binary64 hex.');
local_require(strcmp(local_text(proof, ...
    'interval_endpoint_encoding','proof_representation'), ...
    'directed binary64 endpoint hex'), ...
    'The interval endpoint encoding is not the certified encoding.');
local_require(strcmp(local_text(proof, ...
    'binary64_trial_generation_rounding','proof_representation'), ...
    'nearest via INTLAB setround(0)'), ...
    'The trial-generation rounding mode is not fixed to nearest.');
local_require(strcmp(local_text(proof, ...
    'authoritative_trial_form','proof_representation'), ...
    'phi(z)=(1-z^2)*p(z)'), ...
    'The authoritative trial-function form is missing.');

[q,p_lower,p_upper] = local_read_frozen_trials( ...
    paths.coefficients_csv,n_s,degree);
replay = muhat1_rayleigh_cover( ...
    'mode','interval', ...
    't',t_text, ...
    'degree',degree, ...
    's_cells',n_s, ...
    's_lo',s_lo_text, ...
    's_hi',s_hi_text, ...
    'down_y_max',y_max_text, ...
    'down_y_cells',n_r, ...
    'progress_every',0, ...
    'frozen_coefficients',q, ...
    'frozen_polynomial_lower',p_lower, ...
    'frozen_polynomial_upper',p_upper);

local_validate_replay_ranges(replay,s_lo_text,s_hi_text,y_max_text);
local_compare_cells(paths.cells_csv,replay,n_s);
local_compare_down_cells(paths.down_cells_csv,replay,n_s,n_r);

mass_lower = [replay.cells.mass_lower];
rayleigh_lower = [replay.cells.rayleigh_lower];
rayleigh_upper = [replay.cells.rayleigh_upper];
local_require(all(isfinite(mass_lower)) && all(mass_lower > 0), ...
    'A replayed trial mass is not strictly positive.');
local_require(all(isfinite(rayleigh_lower)) ...
    && all(isfinite(rayleigh_upper)), ...
    'A replayed Rayleigh enclosure is nonfinite.');
local_require(all(isfinite(replay.down_scaled_lower_grid(:))) ...
    && all(isfinite(replay.down_scaled_upper_grid(:))), ...
    'A replayed thin-functional enclosure is nonfinite.');
local_require(all(replay.down_scaled_upper_grid(:) < 0), ...
    'At least one replayed thin-functional upper bound is not negative.');
local_require(replay.down_conjecture_verified, ...
    'The replay did not certify the thin-sector inequality.');

summary = local_struct(manifest,'summary','manifest');
local_require(local_integer(summary,'number_of_s_cells','summary') == n_s, ...
    'The summary s-cell count is inconsistent.');
local_require(local_integer(summary, ...
    'number_of_r_cells_per_s_cell','summary') == n_r, ...
    'The summary r-cell count is inconsistent.');
local_require(local_integer(summary,'number_of_down_cells','summary') ...
    == n_s*n_r,'The summary down-cell count is inconsistent.');
local_require(local_flag(summary, ...
    'all_masses_strictly_positive','summary'), ...
    'The summary does not assert positive masses.');
local_require(local_flag(summary, ...
    'all_rayleigh_bounds_finite','summary'), ...
    'The summary does not assert finite Rayleigh bounds.');
local_require(local_flag(summary, ...
    'all_down_bounds_finite','summary'), ...
    'The summary does not assert finite down bounds.');
local_require(local_flag(summary, ...
    'all_down_upper_bounds_strictly_negative','summary'), ...
    'The summary does not assert strict negativity.');
local_require(local_flag(summary,'down_conjecture_verified','summary'), ...
    'The summary does not assert the replayed theorem.');
local_compare_summary_endpoint( ...
    summary,'max_rayleigh_upper_display','max_rayleigh_upper_hex', ...
    replay.max_rayleigh_upper);
local_compare_summary_endpoint( ...
    summary,'max_down_scaled_upper_display','max_down_scaled_upper_hex', ...
    replay.max_down_scaled_upper);
local_require(local_integer(summary,'max_rayleigh_cell_id','summary') ...
    == replay.max_cell_id,'The maximum-Rayleigh cell ID is inconsistent.');
local_require(local_integer(summary,'max_down_s_cell_id','summary') ...
    == replay.max_down_cell_id, ...
    'The maximum thin-functional s-cell ID is inconsistent.');

cover = local_struct(manifest,'cover','manifest');
local_require(local_text_pair_equals( ...
    local_field(cover,'s_closed_hull_text','cover'), ...
    {s_lo_text,s_hi_text}), ...
    'The recorded s cover disagrees with the configuration.');
local_require(local_text_pair_equals( ...
    local_field(cover,'y_closed_hull_text','cover'), ...
    {'0',y_max_text}), ...
    'The recorded y cover disagrees with the configuration.');
local_require(local_flag(cover,'closed_hull_is_safe_superset','cover'), ...
    'The endpoint convention is not recorded as a safe closed hull.');
local_require(local_flag(cover,'exact_s_cell_id_coverage','cover') ...
    && local_flag(cover,'exact_r_cell_id_coverage','cover'), ...
    'The manifest does not assert exact cell-ID coverage.');

self_validation = local_struct(manifest,'self_validation','manifest');
local_require(local_flag(self_validation,'required','self_validation'), ...
    'Independent replay is not required by the manifest.');
local_require(strcmp(local_sha256( ...
    self_validation,'validator_sha256','self_validation'), ...
    current_source_hashes.validator), ...
    'The self-validation hash does not bind the current validator.');
self_status = local_text(self_validation,'status','self_validation');
if opt.allow_pending_self_validation
    local_require(ismember(self_status,{'pending','passed'}), ...
        'The self-validation status is invalid.');
else
    local_require(strcmp(self_status,'passed'), ...
        'The artifact was not finalized after its replay.');
    local_require(strcmp(local_hex(replay.max_down_scaled_upper), ...
        local_hex_field(self_validation, ...
            'replayed_max_down_scaled_upper_hex','self_validation')), ...
        'The self-validation replayed maximum is inconsistent.');
    local_require(local_integer(self_validation, ...
        'replayed_s_cells','self_validation') == n_s, ...
        'The self-validation s-cell count is inconsistent.');
    local_require(local_integer(self_validation, ...
        'replayed_down_cells','self_validation') == n_s*n_r, ...
        'The self-validation down-cell count is inconsistent.');
end

manifest_complete = local_flag( ...
    manifest,'complete_certificate','manifest');
if manifest_complete
    local_require(production_requested && production_parameters_match, ...
        'A complete artifact must use the canonical production profile.');
    local_require(strcmp(self_status,'passed'), ...
        'A complete artifact must have passed self-validation.');
    local_validate_source_record(source,true);
end
if opt.require_complete_certificate
    local_require(manifest_complete, ...
        'The manifest is not a complete production certificate.');
end
if manifest_complete || opt.require_complete_certificate
    current_source = ver10_source_provenance(project_root);
    local_require(current_source.git_status_available ...
        && ~current_source.git_dirty, ...
        ['A complete replay must run from a clean Git checkout whose ', ...
         'proof-source file hashes match the artifact.']);
end

validation_runtime_after = ver10_runtime_metadata();
validation_runtime_after_payload = jsonencode(validation_runtime_after);
validation_runtime_after_sha256 = local_sha256_bytes( ...
    uint8(validation_runtime_after_payload));
local_compare_runtime(recorded_runtime,validation_runtime_after);
local_require(strcmp(validation_runtime_before_payload, ...
        validation_runtime_after_payload) ...
    && strcmp(validation_runtime_before_sha256, ...
        validation_runtime_after_sha256) ...
    && strcmp(recorded_runtime_sha256, ...
        validation_runtime_after_sha256), ...
    ['The runtime changed during independent replay or no longer matches ', ...
     'the generation runtime.']);

% Detect mutations that occurred while the replay was running.
local_verify_artifact_hashes(paths,recorded_hashes);
local_verify_checksums(paths,recorded_hashes);
local_verify_source_files(project_root,source_files);

report = struct();
report.schema = 'lowerboundsineq.muhat1-rayleigh.validation.v1';
report.complete = true;
report.manifest_complete_certificate = manifest_complete;
report.production_parameters_match = production_parameters_match;
report.number_of_s_cells = n_s;
report.number_of_down_cells = n_s*n_r;
report.replayed_max_rayleigh_upper_hex = ...
    local_hex(replay.max_rayleigh_upper);
report.replayed_max_down_scaled_upper_hex = ...
    local_hex(replay.max_down_scaled_upper);
report.all_masses_strictly_positive = true;
report.all_down_upper_bounds_strictly_negative = true;
report.hashes_rechecked_after_replay = true;
end


function [q,p_lower,p_upper] = ...
        local_read_frozen_trials(filename,n_s,degree)
[header,rows] = local_read_csv(filename);
expected = {'id'};
for j = 1:degree
    expected{end+1} = sprintf('q%02d_hex',j); %#ok<AGROW>
end
for j = 1:degree+2
    expected{end+1} = sprintf('p%02d_lo_hex',j); %#ok<AGROW>
    expected{end+1} = sprintf('p%02d_hi_hex',j); %#ok<AGROW>
end
local_require(isequal(header,expected), ...
    'The frozen-trial CSV header is not canonical.');
local_require(size(rows,1) == n_s, ...
    'The frozen-trial CSV has the wrong row count.');
q = zeros(n_s,degree);
p_lower = zeros(n_s,degree+2);
p_upper = zeros(n_s,degree+2);
for i = 1:n_s
    local_require(local_parse_integer(rows{i,1},'trial ID') == i, ...
        'Frozen-trial IDs must be exactly 1:s_cells in order.');
    offset = 1;
    for j = 1:degree
        q(i,j) = local_decode_hex(rows{i,offset+j},'trial coefficient');
    end
    offset = 1+degree;
    for j = 1:degree+2
        p_lower(i,j) = local_decode_hex( ...
            rows{i,offset+2*j-1},'polynomial lower endpoint');
        p_upper(i,j) = local_decode_hex( ...
            rows{i,offset+2*j},'polynomial upper endpoint');
    end
end
local_require(all(isfinite(q(:))) && ~any(all(q == 0,2)), ...
    'Frozen q vectors must be finite and nonzero.');
local_require(all(isfinite(p_lower(:))) ...
    && all(isfinite(p_upper(:))) ...
    && all(p_lower(:) <= p_upper(:)), ...
    'Frozen polynomial intervals must be finite and ordered.');
local_require(~any(all(p_lower == 0 & p_upper == 0,2)), ...
    'A frozen proof polynomial is identically zero.');
end


function local_compare_cells(filename,replay,n_s)
[header,rows] = local_read_csv(filename);
expected = { ...
    'id','s_left_index','s_right_index','s_partition_count', ...
    's_eval_lo_hex','s_eval_hi_hex','mass_lower_hex','mass_upper_hex', ...
    'midpoint_ritz_hex','rayleigh_lower_hex','rayleigh_upper_hex', ...
    'target_11_5_verified','down_scaled_upper_hex'};
local_require(isequal(header,expected), ...
    'The s-cell CSV header is not canonical.');
local_require(size(rows,1) == n_s, ...
    'The s-cell CSV has the wrong row count.');
for i = 1:n_s
    c = replay.cells(i);
    local_require(local_parse_integer(rows{i,1},'s-cell ID') == i ...
        && local_parse_integer(rows{i,2},'s left index') == i-1 ...
        && local_parse_integer(rows{i,3},'s right index') == i ...
        && local_parse_integer(rows{i,4},'s partition count') == n_s, ...
        'The s-cell partition indices are not exact.');
    values = [ ...
        c.s_eval_lo,c.s_eval_hi,c.mass_lower,c.mass_upper, ...
        c.midpoint_ritz,c.rayleigh_lower,c.rayleigh_upper];
    for j = 1:numel(values)
        local_require(strcmp(local_hex(values(j)), ...
            local_hex_token(rows{i,4+j},'s-cell endpoint')), ...
            'A serialized s-cell endpoint differs from the replay.');
    end
    verified = local_parse_bit(rows{i,12},'target flag');
    local_require(verified == logical(c.target_11_5_verified), ...
        'A serialized target flag differs from the replay.');
    local_require(strcmp(local_hex(c.down_scaled_upper), ...
        local_hex_token(rows{i,13},'down-cell maximum')), ...
        'A serialized s-cell down maximum differs from the replay.');
end
end


function local_compare_down_cells(filename,replay,n_s,n_r)
[header,rows] = local_read_csv(filename);
expected = { ...
    's_cell_id','r_cell_id','r_eval_lo_hex','r_eval_hi_hex', ...
    'scaled_lower_hex','scaled_upper_hex'};
local_require(isequal(header,expected), ...
    'The down-cell CSV header is not canonical.');
local_require(size(rows,1) == n_s*n_r, ...
    'The down-cell CSV has the wrong row count.');
row = 0;
for i = 1:n_s
    for j = 1:n_r
        row = row+1;
        local_require(local_parse_integer(rows{row,1},'down s ID') == i ...
            && local_parse_integer(rows{row,2},'down r ID') == j, ...
            'Down-cell IDs must be the exact Cartesian product in order.');
        values = [ ...
            replay.r_eval_lo(j),replay.r_eval_hi(j), ...
            replay.down_scaled_lower_grid(i,j), ...
            replay.down_scaled_upper_grid(i,j)];
        for k = 1:numel(values)
            local_require(strcmp(local_hex(values(k)), ...
                local_hex_token(rows{row,2+k},'down endpoint')), ...
                'A serialized down-cell endpoint differs from the replay.');
        end
    end
end
end


function local_validate_replay_ranges(replay,s_lo_text,s_hi_text,y_max_text)
n_s = numel(replay.cells);
local_require(n_s >= 1 && ~isempty(replay.r_eval_lo), ...
    'The replay did not produce both partitions.');
for i = 1:n_s-1
    local_require(replay.cells(i).s_eval_hi ...
        >= replay.cells(i+1).s_eval_lo, ...
        'The replayed s intervals contain a gap.');
end
s_lo = intval(s_lo_text);
s_hi = intval(s_hi_text);
local_require(replay.cells(1).s_eval_lo <= inf(s_lo) ...
    && replay.cells(end).s_eval_hi >= sup(s_hi), ...
    'The replayed s intervals do not cover the exact decimal domain.');
local_require(replay.r_eval_lo(1) <= 0, ...
    'The replayed r intervals do not begin at zero.');
for j = 1:numel(replay.r_eval_lo)-1
    local_require(replay.r_eval_hi(j) >= replay.r_eval_lo(j+1), ...
        'The replayed r intervals contain a gap.');
end
root_limit = intval(y_max_text)^(intval('1')/intval('3'));
local_require(replay.r_eval_hi(end) >= sup(root_limit), ...
    'The replayed r intervals do not cover the exact y endpoint.');
end


function local_compare_summary_endpoint( ...
        summary,display_field,hex_field,replayed)
display_value = local_number(summary,display_field,'summary');
hex_value = local_hex_field(summary,hex_field,'summary');
local_require(strcmp(local_hex(display_value),hex_value), ...
    'A display endpoint does not round-trip to its authoritative hex value.');
local_require(strcmp(local_hex(replayed),hex_value), ...
    'A summary endpoint differs from the replay.');
end


function local_validate_source_record(source,require_clean)
git_available = local_flag(source,'git_status_available','source');
dirty = local_flag(source,'git_dirty','source');
captured = local_flag(source,'provenance_captured_before_run','source');
rechecked = local_flag(source,'provenance_rechecked_after_run','source');
unchanged = local_flag(source,'source_unchanged_after_run','source');
commit = local_text(source,'git_commit','source');
commit_after = local_text(source,'git_commit_after_run','source');
dirty_after = local_flag(source,'git_dirty_after_run','source');
local_require(captured && rechecked, ...
    'Source provenance was not checked before and after the run.');
local_require(git_available && unchanged, ...
    'The certificate source was not identified by Git throughout the run.');
local_require(~isempty(regexp(commit,'^[0-9a-f]{40}$','once')) ...
    && strcmp(commit,commit_after) && dirty == dirty_after, ...
    'The before/after source records disagree.');
if require_clean
    local_require(~dirty, ...
        'A complete production certificate must use a clean source tree.');
end
end


function hashes = local_verify_source_files(project_root,source_files)
entries = { ...
    'algorithm','src/degenerate/muhat1_rayleigh_cover.m'; ...
    'driver','scripts_run/run_muhat1_rayleigh_certificate.m'; ...
    'production_wrapper','scripts_run/run_muhat1_rayleigh_hpc.m'; ...
    'validator','src/degenerate/validate_muhat1_rayleigh_certificate.m'; ...
    'source_provenance','scripts_run/ver10_source_provenance.m'; ...
    'source_unchanged','scripts_run/ver10_assert_source_unchanged.m'; ...
    'runtime_metadata','scripts_run/ver10_runtime_metadata.m'; ...
    'runtime_tree_hash','scripts_run/ver10_directory_sha256.m'; ...
    'intlab_init_lock','scripts_run/ver10_acquire_intlab_init_lock.m'; ...
    'intlab_config','my_intlab_config.m'; ...
    'intlab_worker_config','scripts_run/my_intlab_config_worker.m'; ...
    'runtime_prepare_worker','scripts_run/omega_up_all_prepare_worker.m'; ...
    'file_sha256','scripts_run/ver10_file_sha256.m'};
hashes = struct();
for k = 1:size(entries,1)
    key = entries{k,1};
    expected_path = entries{k,2};
    record = local_struct(source_files,key,'source_files');
    local_require(strcmp(local_text(record,'path',['source_files.',key]), ...
        expected_path),'A recorded source path is not canonical.');
    recorded = local_sha256(record,'sha256',['source_files.',key]);
    actual = ver10_file_sha256(fullfile( ...
        project_root,strrep(expected_path,'/',filesep)));
    local_require(strcmp(recorded,actual), ...
        ['The current ',key,' source hash differs from the artifact.']);
    hashes.(key) = actual;
end
end


function local_compare_runtime(recorded,current)
text_fields = { ...
    'engine','engine_version','release','computer','interval_toolbox', ...
    'startintlab_file','intval_constructor_file'};
for k = 1:numel(text_fields)
    key = text_fields{k};
    local_require(strcmp(local_text(recorded,key,'runtime'), ...
        local_text(current,key,'current runtime')), ...
        ['Runtime field ',key,' differs from the recorded run.']);
end
hash_fields = { ...
    'startintlab_sha256','intval_constructor_sha256', ...
    'intlab_tree_sha256'};
for k = 1:numel(hash_fields)
    key = hash_fields{k};
    local_require(strcmp(local_sha256(recorded,key,'runtime'), ...
        local_sha256(current,key,'current runtime')), ...
        ['Runtime hash ',key,' differs from the recorded run.']);
end
numeric_fields = {'intlab_tree_file_count','intlab_tree_total_bytes'};
for k = 1:numel(numeric_fields)
    key = numeric_fields{k};
    local_require(local_number(recorded,key,'runtime') ...
        == local_number(current,key,'current runtime'), ...
        ['Runtime field ',key,' differs from the recorded run.']);
end
end


function local_verify_artifact_hashes(paths,hashes)
local_require(strcmp(ver10_file_sha256(paths.coefficients_csv), ...
    hashes.coefficients_csv),'The frozen-trial CSV hash is wrong.');
local_require(strcmp(ver10_file_sha256(paths.cells_csv), ...
    hashes.cells_csv),'The s-cell CSV hash is wrong.');
local_require(strcmp(ver10_file_sha256(paths.down_cells_csv), ...
    hashes.down_cells_csv),'The down-cell CSV hash is wrong.');
end


function local_verify_checksums(paths,hashes)
text_value = fileread(paths.checksums_sha256);
lines = regexp(strrep(text_value,sprintf('\r\n'),sprintf('\n')), ...
    '\n','split');
while ~isempty(lines) && isempty(lines{end})
    lines(end) = [];
end
expected_names = { ...
    'manifest.json','frozen_coefficients.csv','cells.csv','down_cells.csv'};
expected_hashes = { ...
    ver10_file_sha256(paths.manifest_json), ...
    hashes.coefficients_csv,hashes.cells_csv,hashes.down_cells_csv};
local_require(numel(lines) == numel(expected_names), ...
    'The checksum inventory has the wrong number of entries.');
for k = 1:numel(lines)
    token = regexp(lines{k}, ...
        '^([0-9a-f]{64})  ([A-Za-z0-9_.-]+)$','tokens','once');
    local_require(~isempty(token),'A checksum line is malformed.');
    local_require(strcmp(token{1},expected_hashes{k}) ...
        && strcmp(token{2},expected_names{k}), ...
        'The checksum inventory does not match the artifact.');
end
end


function [header,rows] = local_read_csv(filename)
local_require(isfile(filename),'A required CSV artifact is missing.');
value = fileread(filename);
value = strrep(value,sprintf('\r\n'),sprintf('\n'));
value = strrep(value,sprintf('\r'),sprintf('\n'));
lines = regexp(value,'\n','split');
while ~isempty(lines) && isempty(lines{end})
    lines(end) = [];
end
local_require(~isempty(lines),'A CSV artifact is empty.');
local_require(~any(cellfun(@isempty,lines)), ...
    'Blank CSV rows are not permitted.');
header = strsplit(lines{1},',','CollapseDelimiters',false);
rows = cell(numel(lines)-1,numel(header));
for i = 2:numel(lines)
    values = strsplit(lines{i},',','CollapseDelimiters',false);
    local_require(numel(values) == numel(header), ...
        'A CSV row has the wrong number of columns.');
    rows(i-1,:) = values;
end
end


function path_value = local_resolve_sibling(directory,recorded)
local_require(isempty(fileparts(recorded)) ...
    && isempty(strfind(recorded,'..')) ... %#ok<STREMP>
    && ~startsWith(recorded,filesep), ...
    'Artifact paths must be simple sibling basenames.');
path_value = fullfile(directory,recorded);
local_require(isfile(path_value),'A required artifact file is missing.');
end


function value = local_parse_integer(token,description)
local_require(~isempty(regexp(token,'^(0|[1-9][0-9]*)$','once')), ...
    [description,' is not a canonical nonnegative integer.']);
value = str2double(token);
local_require(isfinite(value) && value <= flintmax, ...
    [description,' cannot be represented exactly.']);
end


function value = local_parse_bit(token,description)
local_require(strcmp(token,'0') || strcmp(token,'1'), ...
    [description,' must be 0 or 1.']);
value = strcmp(token,'1');
end


function value = local_decode_hex(token,description)
token = local_hex_token(token,description);
value = hex2num(token);
local_require(isreal(value) && isscalar(value) && isfinite(value), ...
    [description,' must decode to a finite binary64 value.']);
end


function token = local_hex_token(token,description)
token = lower(char(token));
local_require(~isempty(regexp(token,'^[0-9a-f]{16}$','once')), ...
    [description,' is not a canonical binary64 hex token.']);
end


function value = local_hex_field(parent,name,context)
value = local_hex_token(local_text(parent,name,context), ...
    [context,'.',name]);
end


function value = local_hex(number)
value = lower(num2hex(double(number)));
end


function value = local_sha256(parent,name,context)
value = local_text(parent,name,context);
local_require(~isempty(regexp(value,'^[0-9a-f]{64}$','once')), ...
    [context,'.',name,' is not a lowercase SHA-256 digest.']);
end


function value = local_decimal(parent,name,context)
value = local_text(parent,name,context);
local_require(~isempty(regexp(value, ...
    '^[+-]?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[eE][+-]?[0-9]+)?$', ...
    'once')) && isfinite(str2double(value)), ...
    [context,'.',name,' is not a finite decimal string.']);
end


function value = local_integer(parent,name,context)
value = local_number(parent,name,context);
local_require(value >= 0 && value == floor(value) && value <= flintmax, ...
    [context,'.',name,' is not an exact nonnegative integer.']);
end


function value = local_number(parent,name,context)
value = local_field(parent,name,context);
local_require(isnumeric(value) && isreal(value) ...
    && isscalar(value) && isfinite(value), ...
    [context,'.',name,' must be a finite real scalar.']);
value = double(value);
end


function value = local_flag(parent,name,context)
value = local_field(parent,name,context);
local_require(islogical(value) && isscalar(value), ...
    [context,'.',name,' must be a JSON boolean.']);
end


function value = local_text(parent,name,context)
value = local_field(parent,name,context);
local_require(ischar(value) || (isstring(value) && isscalar(value)), ...
    [context,'.',name,' must be text.']);
value = char(value);
end


function value = local_struct(parent,name,context)
value = local_field(parent,name,context);
local_require(isstruct(value) && isscalar(value), ...
    [context,'.',name,' must be an object.']);
end


function value = local_field(parent,name,context)
local_require(isstruct(parent) && isscalar(parent) && isfield(parent,name), ...
    [context,' is missing required field ',name,'.']);
value = parent.(name);
end


function tf = local_text_pair_equals(value,expected)
if isstring(value)
    value = cellstr(value(:));
elseif ischar(value)
    value = {value};
elseif iscell(value)
    value = value(:);
else
    tf = false;
    return
end
if numel(value) ~= 2
    tf = false;
    return
end
tf = all(cellfun(@(x) ischar(x) || (isstring(x) && isscalar(x)),value)) ...
    && strcmp(char(value{1}),expected{1}) ...
    && strcmp(char(value{2}),expected{2});
end


function canonical = local_canonical_path(filename)
try
    file_object = javaObject('java.io.File',char(filename));
    canonical = char(file_object.getCanonicalPath());
catch
    canonical = char(filename);
end
end


function digest = local_sha256_bytes(bytes)
try
    engine = javaMethod( ...
        'getInstance','java.security.MessageDigest','SHA-256');
catch ME
    error('validate_muhat1_rayleigh_certificate:NoSHA256', ...
        'Cannot initialize SHA-256: %s',ME.message);
end
bytes = uint8(bytes(:));
if ~isempty(bytes)
    engine.update(typecast(bytes,'int8'));
end
raw = typecast(engine.digest(),'uint8');
digest = lower(reshape(dec2hex(raw,2).',1,[]));
end


function local_require(condition,message)
if ~condition
    error('validate_muhat1_rayleigh_certificate:InvalidCertificate', ...
        '%s',message);
end
end
